/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin.dialogs.step08.obsolete;

import hvv_admin.HVV_Admin;
import hvv_admin.HVV_AdminConstants;
import hvv_admin.steps.info.GettersActivationProgram;
import java.util.LinkedList;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class TechProcessStep08_2_Dlg_3_Panel extends javax.swing.JPanel {

    static Logger logger = Logger.getLogger(TechProcessStep08_2_Dlg_3_Panel.class);
    final private HVV_Admin theApp;
    
    TechProcessStep08_2_Dlg_3_StepTemplate pnlDev1;
    TechProcessStep08_2_Dlg_3_StepTemplate pnlDev2;
    TechProcessStep08_2_Dlg_3_StepTemplate pnlDev3;
    TechProcessStep08_2_Dlg_3_StepTemplate pnlDev4;
    TechProcessStep08_2_Dlg_3_StepTemplate pnlDev5;
    TechProcessStep08_2_Dlg_3_StepTemplate pnlDev6;
    TechProcessStep08_2_Dlg_3_StepTemplate pnlDev7;
    TechProcessStep08_2_Dlg_3_StepTemplate pnlDev8;
    
    /**
     * Creates new form TechProcessStep08_2_Dlg_3_Panel2
     */
    public TechProcessStep08_2_Dlg_3_Panel( HVV_Admin app) {
        theApp = app;
        initComponents();
        
        pnlDev1 = new TechProcessStep08_2_Dlg_3_StepTemplate( app, HVV_AdminConstants.DEVICE1);
        pnlDev1.setVisible( true);
        pnlDev1.setBounds( 0, 0, 930, 150);
        jPanel1.add( pnlDev1);
        
        pnlDev2 = new TechProcessStep08_2_Dlg_3_StepTemplate( app, HVV_AdminConstants.DEVICE2);
        pnlDev2.setVisible( true);
        pnlDev2.setBounds( 0, 0, 930, 150);
        jPanel2.add( pnlDev2);
        
        pnlDev3 = new TechProcessStep08_2_Dlg_3_StepTemplate( app, HVV_AdminConstants.DEVICE3);
        pnlDev3.setVisible( true);
        pnlDev3.setBounds( 0, 0, 930, 150);
        jPanel3.add( pnlDev3);
        
        pnlDev4 = new TechProcessStep08_2_Dlg_3_StepTemplate( app, HVV_AdminConstants.DEVICE4);
        pnlDev4.setVisible( true);
        pnlDev4.setBounds( 0, 0, 930, 150);
        jPanel4.add( pnlDev4);
        
        pnlDev5 = new TechProcessStep08_2_Dlg_3_StepTemplate( app, HVV_AdminConstants.DEVICE5);
        pnlDev5.setVisible( true);
        pnlDev5.setBounds( 0, 0, 930, 150);
        jPanel5.add( pnlDev5);
        
        pnlDev6 = new TechProcessStep08_2_Dlg_3_StepTemplate( app, HVV_AdminConstants.DEVICE6);
        pnlDev6.setVisible( true);
        pnlDev6.setBounds( 0, 0, 930, 150);
        jPanel6.add( pnlDev6);
        
        pnlDev7 = new TechProcessStep08_2_Dlg_3_StepTemplate( app, HVV_AdminConstants.DEVICE7);
        pnlDev7.setVisible( true);
        pnlDev7.setBounds( 0, 0, 930, 150);
        jPanel7.add( pnlDev7);
        
        pnlDev8 = new TechProcessStep08_2_Dlg_3_StepTemplate( app, HVV_AdminConstants.DEVICE8);
        pnlDev8.setVisible( true);
        pnlDev8.setBounds( 0, 0, 930, 150);
        jPanel8.add( pnlDev8);
    }

    public void RefreshData() {
        pnlDev1.RefreshData();
        pnlDev2.RefreshData();
        pnlDev3.RefreshData();
        pnlDev4.RefreshData();
        pnlDev5.RefreshData();
        pnlDev6.RefreshData();
        pnlDev7.RefreshData();
        pnlDev8.RefreshData();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(930, 1020));
        setMinimumSize(new java.awt.Dimension(930, 1020));
        setName(""); // NOI18N
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("<html><u>ПРИБОР1</u></html>");
        add(jLabel1);
        jLabel1.setBounds(100, 0, 100, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(jPanel1);
        jPanel1.setBounds(0, 30, 930, 150);

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setText("<html><u>ПРИБОР 2</u></html>");
        add(jLabel2);
        jLabel2.setBounds(100, 180, 100, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(jPanel2);
        jPanel2.setBounds(0, 210, 930, 150);

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setText("<html><u>ПРИБОР 3</u></html>");
        add(jLabel3);
        jLabel3.setBounds(100, 360, 100, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(jPanel3);
        jPanel3.setBounds(0, 390, 930, 150);

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel4.setText("<html><u>ПРИБОР 4</u></html>");
        add(jLabel4);
        jLabel4.setBounds(100, 540, 100, 30);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(jPanel4);
        jPanel4.setBounds(0, 570, 930, 150);

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel5.setText("<html><u>ПРИБОР 5</u></html>");
        add(jLabel5);
        jLabel5.setBounds(100, 720, 100, 30);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(jPanel5);
        jPanel5.setBounds(0, 750, 930, 150);

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel6.setText("<html><u>ПРИБОР 6</u></html>");
        add(jLabel6);
        jLabel6.setBounds(100, 900, 100, 30);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(jPanel6);
        jPanel6.setBounds(0, 930, 930, 150);

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel7.setText("<html><u>ПРИБОР 8</u></html>");
        add(jLabel7);
        jLabel7.setBounds(100, 1260, 100, 30);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(jPanel7);
        jPanel7.setBounds(0, 1110, 930, 150);

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel8.setText("<html><u>ПРИБОР 7</u></html>");
        add(jLabel8);
        jLabel8.setBounds(100, 1080, 100, 30);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        add(jPanel8);
        jPanel8.setBounds(0, 1290, 930, 150);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
