package hvv_admin.dialogs.step05;

import hvv_admin.HVV_Admin;
import hvv_admin.steps.info.TechProcessStepInfo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.Timer;
import org.apache.log4j.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yaroslav
 */
public class TechProcessStep05_1_Dlg extends javax.swing.JDialog {

    static Logger logger = Logger.getLogger( TechProcessStep05_1_Dlg.class);
    final private HVV_Admin theApp;
    /**
     * Creates new form TechProcessStep2_1_Dlg
     */
    
    public Timer m_tmrRefreshTimer;
    
    final GregorianCalendar m_gdtmDate;

    public void initOnStart() {
        m_gdtmDate.setTime( theApp.GetLocalDate());
        m_gdtmDate.add( Calendar.HOUR, 25);
        
        updateData();
        
        m_tmrRefreshTimer = new Timer( 60000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                updateData();
            }
        });
        m_tmrRefreshTimer.start();
    }
    
    public TechProcessStep05_1_Dlg( HVV_Admin app, java.awt.Frame parent, boolean modal) {
        super( parent, modal);
        theApp = app;
        initComponents();
        m_gdtmDate = new GregorianCalendar();
        m_gdtmDate.setTime( theApp.GetLocalDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrGet1 = new javax.swing.ButtonGroup();
        btnGrGet2 = new javax.swing.ButtonGroup();
        btnGrGet3 = new javax.swing.ButtonGroup();
        btnGrGet4 = new javax.swing.ButtonGroup();
        btnGrGet5 = new javax.swing.ButtonGroup();
        btnGrGet6 = new javax.swing.ButtonGroup();
        btnGrGet7 = new javax.swing.ButtonGroup();
        btnGrGet8 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnYes = new javax.swing.JButton();
        lblDoW = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblTimerPointYM = new javax.swing.JLabel();
        lblMonth = new javax.swing.JLabel();
        lblPointMD = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();
        lblPointHM = new javax.swing.JLabel();
        lblMinute = new javax.swing.JLabel();
        lblFinish = new javax.swing.JLabel();
        lblFinishValue = new javax.swing.JLabel();
        lblFinishMin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("5.1 Установка печек");
        setMaximumSize(new java.awt.Dimension(640, 330));
        setMinimumSize(new java.awt.Dimension(640, 330));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Установите печки на приборы. Рассчитайте длительность процесса.");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 620, 30);

        btnYes.setText("Печки установлены. Перейти к пункту 5.2");
        btnYes.setToolTipText("");
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });
        getContentPane().add(btnYes);
        btnYes.setBounds(10, 230, 620, 60);

        lblDoW.setFont(new java.awt.Font("Cantarell", 0, 50)); // NOI18N
        lblDoW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoW.setText("чт");
        lblDoW.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        lblDoW.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDoWMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDoW);
        lblDoW.setBounds(20, 60, 80, 110);

        lblYear.setFont(new java.awt.Font("Cantarell", 0, 50)); // NOI18N
        lblYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYear.setText("2016");
        lblYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        lblYear.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblYearMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblYear);
        lblYear.setBounds(300, 60, 150, 110);

        lblTimerPointYM.setFont(new java.awt.Font("Cantarell", 0, 50)); // NOI18N
        lblTimerPointYM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimerPointYM.setText(".");
        lblTimerPointYM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        getContentPane().add(lblTimerPointYM);
        lblTimerPointYM.setBounds(200, 60, 10, 110);

        lblMonth.setFont(new java.awt.Font("Cantarell", 0, 50)); // NOI18N
        lblMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMonth.setText("09");
        lblMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        lblMonth.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblMonthMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblMonth);
        lblMonth.setBounds(210, 60, 80, 110);

        lblPointMD.setFont(new java.awt.Font("Cantarell", 0, 50)); // NOI18N
        lblPointMD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPointMD.setText(".");
        lblPointMD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        getContentPane().add(lblPointMD);
        lblPointMD.setBounds(290, 60, 10, 110);

        lblDay.setFont(new java.awt.Font("Cantarell", 0, 50)); // NOI18N
        lblDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDay.setText("29");
        lblDay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        lblDay.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDayMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDay);
        lblDay.setBounds(120, 60, 80, 110);

        lblHour.setFont(new java.awt.Font("Cantarell", 0, 50)); // NOI18N
        lblHour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHour.setText("16");
        lblHour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        lblHour.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblHourMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblHour);
        lblHour.setBounds(470, 60, 70, 110);

        lblPointHM.setFont(new java.awt.Font("Cantarell", 0, 50)); // NOI18N
        lblPointHM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPointHM.setText(":");
        lblPointHM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        getContentPane().add(lblPointHM);
        lblPointHM.setBounds(540, 60, 20, 110);

        lblMinute.setFont(new java.awt.Font("Cantarell", 0, 50)); // NOI18N
        lblMinute.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinute.setText("41");
        lblMinute.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        lblMinute.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblMinuteMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblMinute);
        lblMinute.setBounds(560, 60, 70, 110);

        lblFinish.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        lblFinish.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFinish.setText("<html>Завершение термообезгаживания:</html>");
        lblFinish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        getContentPane().add(lblFinish);
        lblFinish.setBounds(10, 180, 390, 40);

        lblFinishValue.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblFinishValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinishValue.setText("9940");
        lblFinishValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        getContentPane().add(lblFinishValue);
        lblFinishValue.setBounds(420, 180, 130, 40);

        lblFinishMin.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        lblFinishMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinishMin.setText("<html>мин</thml>");
        lblFinishMin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        getContentPane().add(lblFinishMin);
        lblFinishMin.setBounds(570, 180, 60, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        m_tmrRefreshTimer.stop();        
        
        //т.к. подэтап 5.1 ручной, мы просто переходим к следующему подэтапу (5.2), а он ручной
        if( theApp.IsStepMapContainsKey( "081")) {
            TechProcessStepInfo info = theApp.GetStepInfo( "081");
            
            info.SetStopDateAsCurrent();
            info.SetStopReportTitle( "");
            info.SetStopP5( theApp.GetDoubleFromPoller( "005.01"));
            info.SetStopP6( theApp.GetDoubleFromPoller( "006.01"));
            info.SetStopP7( theApp.GetDoubleFromPoller( "007.01"));
            
            theApp.NextCurrentStep();
            
            info = new TechProcessStepInfo( theApp);
            
            info.SetStartDateAsCurrent();
            info.SetStartReportTitle( "Старт термообезгаживания");
            info.SetStartP5( theApp.GetDoubleFromPoller( "005.01"));
            info.SetStartP6( theApp.GetDoubleFromPoller( "006.01"));
            info.SetStartP7( theApp.GetDoubleFromPoller( "007.01"));
            
            theApp.SaveStepInfo( "082", info, true);
            
            theApp.ShowDlg5_2();
            
            theApp.m_pMainWnd.m_pPanel.SetStates();
            theApp.m_pMainWnd.m_pPanel.Reposition();
        }
        else {
            logger.fatal( "Мы заканчиваем этап 081, а инфы на него до сих пор нет!");
        }
        dispose();
    }//GEN-LAST:event_btnYesActionPerformed

    public void updateData() {
        lblDay.setText( ( m_gdtmDate.get( Calendar.DAY_OF_MONTH) < 10 ? "0" : "") +
                        m_gdtmDate.get( Calendar.DAY_OF_MONTH));
        
        lblMonth.setText( ( m_gdtmDate.get( Calendar.MONTH) + 1 < 10 ? "0" : "") +
                          ( m_gdtmDate.get( Calendar.MONTH) + 1));
        
        lblYear.setText( ( m_gdtmDate.get( Calendar.YEAR) < 10 ? "0" : "") +
                         m_gdtmDate.get( Calendar.YEAR));
        
        lblHour.setText( ( m_gdtmDate.get( Calendar.HOUR_OF_DAY) < 10 ? "0" : "") +
                         m_gdtmDate.get( Calendar.HOUR_OF_DAY));
        
        lblMinute.setText( ( m_gdtmDate.get( Calendar.MINUTE) < 10 ? "0" : "") +
                            m_gdtmDate.get( Calendar.MINUTE));
        
        switch( m_gdtmDate.get( Calendar.DAY_OF_WEEK)) {
            case Calendar.SUNDAY:   lblDoW.setText( "вс"); break;
            case Calendar.MONDAY:   lblDoW.setText( "пн"); break;
            case Calendar.TUESDAY:  lblDoW.setText( "вт"); break;
            case Calendar.WEDNESDAY:lblDoW.setText( "ср"); break;
            case Calendar.THURSDAY: lblDoW.setText( "чт"); break;
            case Calendar.FRIDAY:   lblDoW.setText( "пт"); break;
            case Calendar.SATURDAY: lblDoW.setText( "сб"); break;
            default: lblDoW.setText( "-"); break;
        }
        
        Date dtNow = theApp.GetLocalDate();
        Date dtFinish = m_gdtmDate.getTime();
        
        //окончание ТО
        long nSpan = ( long) ( Math.ceil( ( dtFinish.getTime() - dtNow.getTime()) / 1000. / 60. / 10.)) * 10;
        logger.trace( "dtFinish(msec): " + dtFinish.getTime() + "  dtNow(msec): " + dtNow.getTime() + "  SPAN(10m): " + nSpan);
        
        if( nSpan < 0) nSpan = 0;
        lblFinishValue.setText( "" + nSpan);
    }
    
    private void lblDoWMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblDoWMouseWheelMoved
        m_gdtmDate.add( Calendar.DAY_OF_MONTH, -1 * evt.getWheelRotation());
        updateData();
    }//GEN-LAST:event_lblDoWMouseWheelMoved

    private void lblYearMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblYearMouseWheelMoved
        m_gdtmDate.add( Calendar.YEAR, -1 * evt.getWheelRotation());
        updateData();
    }//GEN-LAST:event_lblYearMouseWheelMoved

    private void lblMonthMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblMonthMouseWheelMoved
        m_gdtmDate.add( Calendar.MONTH, -1 * evt.getWheelRotation());
        updateData();
    }//GEN-LAST:event_lblMonthMouseWheelMoved

    private void lblDayMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblDayMouseWheelMoved
        m_gdtmDate.add( Calendar.DAY_OF_MONTH, -1 * evt.getWheelRotation());
        updateData();
    }//GEN-LAST:event_lblDayMouseWheelMoved

    private void lblHourMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblHourMouseWheelMoved
        m_gdtmDate.add( Calendar.HOUR, -1 * evt.getWheelRotation());
        updateData();
    }//GEN-LAST:event_lblHourMouseWheelMoved

    private void lblMinuteMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblMinuteMouseWheelMoved
        m_gdtmDate.add( Calendar.MINUTE, -1 * evt.getWheelRotation());
        updateData();
    }//GEN-LAST:event_lblMinuteMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_1_Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_1_Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_1_Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_1_Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TechProcessStep05_1_Dlg dialog = new TechProcessStep05_1_Dlg( null, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrGet1;
    private javax.swing.ButtonGroup btnGrGet2;
    private javax.swing.ButtonGroup btnGrGet3;
    private javax.swing.ButtonGroup btnGrGet4;
    private javax.swing.ButtonGroup btnGrGet5;
    private javax.swing.ButtonGroup btnGrGet6;
    private javax.swing.ButtonGroup btnGrGet7;
    private javax.swing.ButtonGroup btnGrGet8;
    private javax.swing.JButton btnYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblDoW;
    private javax.swing.JLabel lblFinish;
    private javax.swing.JLabel lblFinishMin;
    private javax.swing.JLabel lblFinishValue;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblMinute;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblPointHM;
    private javax.swing.JLabel lblPointMD;
    private javax.swing.JLabel lblTimerPointYM;
    private javax.swing.JLabel lblYear;
    // End of variables declaration//GEN-END:variables
}
