package hvv_admin.dialogs.step05;

import hvv_admin.HVV_Admin;
import hvv_admin.comm.executor.to.StartProgramExecutor;
import hvv_admin.steps.info.TechProcessStepInfo;
import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;
import static java.util.concurrent.TimeUnit.SECONDS;
import org.apache.log4j.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yaroslav
 */
public class TechProcessStep05_2_DlgSet extends javax.swing.JDialog {

    static Logger logger = Logger.getLogger(TechProcessStep05_2_DlgSet.class);
    final private HVV_Admin theApp;
    
    public GregorianCalendar m_gdtmDate;
    
    private final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
    ScheduledFuture <?> taskHandle;
    
    public void startPeriodicTask() {
        Runnable task = new Runnable() {
            @Override
            public void run() {
                
                switch( m_gdtmDate.get( Calendar.DAY_OF_WEEK)) {
                    case Calendar.SUNDAY:   lblGetterOpenDow.setText( "вс"); break;
                    case Calendar.MONDAY:   lblGetterOpenDow.setText( "пн"); break;
                    case Calendar.TUESDAY:  lblGetterOpenDow.setText( "вт"); break;
                    case Calendar.WEDNESDAY:lblGetterOpenDow.setText( "ср"); break;
                    case Calendar.THURSDAY: lblGetterOpenDow.setText( "чт"); break;
                    case Calendar.FRIDAY:   lblGetterOpenDow.setText( "пт"); break;
                    case Calendar.SATURDAY: lblGetterOpenDow.setText( "сб"); break;
                    default: lblGetterOpenDow.setText( "-"); break;
                }
                
                lblGetterOpenDay.setText( "" + m_gdtmDate.get( Calendar.DAY_OF_MONTH));
                        
                switch( m_gdtmDate.get( Calendar.MONTH)) {
                    case Calendar.JANUARY:  lblGetterOpenMonth.setText("янв");  break;
                    case Calendar.FEBRUARY: lblGetterOpenMonth.setText("фев");  break;
                    case Calendar.MARCH:    lblGetterOpenMonth.setText("мар");  break;
                    case Calendar.APRIL:    lblGetterOpenMonth.setText("апр");  break;
                    case Calendar.MAY:      lblGetterOpenMonth.setText("май");  break;
                    case Calendar.JUNE:     lblGetterOpenMonth.setText("июн");  break;
                    case Calendar.JULY:     lblGetterOpenMonth.setText("июл");  break;
                    case Calendar.AUGUST:   lblGetterOpenMonth.setText("авг");  break;
                    case Calendar.SEPTEMBER:lblGetterOpenMonth.setText("сен");  break;
                    case Calendar.OCTOBER:  lblGetterOpenMonth.setText("окт");  break;
                    case Calendar.NOVEMBER: lblGetterOpenMonth.setText("ноя");  break;
                    case Calendar.DECEMBER: lblGetterOpenMonth.setText("дек");  break;
                    default:                lblGetterOpenMonth.setText("-");    break;
                }
                
                lblGetterOpenYear.setText( "" + m_gdtmDate.get( Calendar.YEAR));

                lblGetterOpenHour.setText( String.format( "%02d", m_gdtmDate.get( Calendar.HOUR_OF_DAY)));
                lblGetterOpenMinutes.setText( String.format( "%02d", m_gdtmDate.get( Calendar.MINUTE)));
            }
            
        };
        
        taskHandle = scheduler.scheduleAtFixedRate( task, 0, 200, TimeUnit.MILLISECONDS);
    }
    
    public void stopPeriodicTask() {
        taskHandle.cancel( true);
    }
    /**
     * Creates new form TechProcessStep2_1_Dlg
     */
    public TechProcessStep05_2_DlgSet( HVV_Admin app, java.awt.Frame parent, boolean modal, GregorianCalendar clndr) {
        super( parent, modal);
        theApp = app;
        initComponents();
        
        m_gdtmDate = clndr;
        
        startPeriodicTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrGet1 = new javax.swing.ButtonGroup();
        btnGrGet2 = new javax.swing.ButtonGroup();
        btnGrGet3 = new javax.swing.ButtonGroup();
        btnGrGet4 = new javax.swing.ButtonGroup();
        btnGrGet5 = new javax.swing.ButtonGroup();
        btnGrGet6 = new javax.swing.ButtonGroup();
        btnGrGet7 = new javax.swing.ButtonGroup();
        btnGrGet8 = new javax.swing.ButtonGroup();
        lblIOpenGetterTitle = new javax.swing.JLabel();
        lblGetterOpenDow = new javax.swing.JLabel();
        lblGetterOpenDay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblGetterOpenMonth = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblGetterOpenYear = new javax.swing.JLabel();
        lblGetterOpenHour = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblGetterOpenMinutes = new javax.swing.JLabel();
        btnSet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("5.2 Термообезгаживание");
        setMaximumSize(new java.awt.Dimension(350, 180));
        setMinimumSize(new java.awt.Dimension(350, 180));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        getContentPane().setLayout(null);

        lblIOpenGetterTitle.setText("Запустить программу открытия геттера:");
        lblIOpenGetterTitle.setToolTipText("");
        getContentPane().add(lblIOpenGetterTitle);
        lblIOpenGetterTitle.setBounds(10, 0, 330, 40);

        lblGetterOpenDow.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenDow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenDow.setText("-");
        lblGetterOpenDow.setToolTipText("");
        lblGetterOpenDow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenDow.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenDowMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenDow);
        lblGetterOpenDow.setBounds(10, 50, 40, 30);

        lblGetterOpenDay.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenDay.setText("-");
        lblGetterOpenDay.setToolTipText("");
        lblGetterOpenDay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenDay.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenDayMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenDay);
        lblGetterOpenDay.setBounds(50, 50, 40, 30);

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(".");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 50, 10, 30);

        lblGetterOpenMonth.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenMonth.setText("-");
        lblGetterOpenMonth.setToolTipText("");
        lblGetterOpenMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenMonth.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenMonthMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenMonth);
        lblGetterOpenMonth.setBounds(100, 50, 50, 30);

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(".");
        jLabel7.setToolTipText("");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 50, 10, 30);

        lblGetterOpenYear.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenYear.setText("-");
        lblGetterOpenYear.setToolTipText("");
        lblGetterOpenYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenYear.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenYearMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenYear);
        lblGetterOpenYear.setBounds(160, 50, 80, 30);

        lblGetterOpenHour.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenHour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenHour.setText("-");
        lblGetterOpenHour.setToolTipText("");
        lblGetterOpenHour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenHour.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenHourMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenHour);
        lblGetterOpenHour.setBounds(250, 50, 40, 30);

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(":");
        jLabel10.setToolTipText("");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(290, 50, 10, 30);

        lblGetterOpenMinutes.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenMinutes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenMinutes.setText("-");
        lblGetterOpenMinutes.setToolTipText("");
        lblGetterOpenMinutes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenMinutes.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenMinutesMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenMinutes);
        lblGetterOpenMinutes.setBounds(300, 50, 40, 30);

        btnSet.setText("Задать");
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });
        getContentPane().add(btnSet);
        btnSet.setBounds(10, 90, 330, 40);

        getAccessibleContext().setAccessibleName("Дата время запуска программы открытия геттера");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        stopPeriodicTask();
        dispose();
    }//GEN-LAST:event_btnSetActionPerformed

    private void lblGetterOpenDowMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenDowMouseWheelMoved
        m_gdtmDate.add( Calendar.DAY_OF_MONTH, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenDowMouseWheelMoved

    private void lblGetterOpenDayMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenDayMouseWheelMoved
        m_gdtmDate.add( Calendar.DAY_OF_MONTH, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenDayMouseWheelMoved

    private void lblGetterOpenMonthMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenMonthMouseWheelMoved
        m_gdtmDate.add( Calendar.MONTH, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenMonthMouseWheelMoved

    private void lblGetterOpenYearMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenYearMouseWheelMoved
        m_gdtmDate.add( Calendar.YEAR, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenYearMouseWheelMoved

    private void lblGetterOpenHourMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenHourMouseWheelMoved
        m_gdtmDate.add( Calendar.HOUR, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenHourMouseWheelMoved

    private void lblGetterOpenMinutesMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenMinutesMouseWheelMoved
       m_gdtmDate.add( Calendar.MINUTE, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenMinutesMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_2_DlgSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_2_DlgSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_2_DlgSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_2_DlgSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GregorianCalendar gdtmDate = ( GregorianCalendar) Calendar.getInstance();
                gdtmDate.add( Calendar.HOUR, 23);
                TechProcessStep05_2_DlgSet dialog = new TechProcessStep05_2_DlgSet( null, new javax.swing.JFrame(), true, gdtmDate);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrGet1;
    private javax.swing.ButtonGroup btnGrGet2;
    private javax.swing.ButtonGroup btnGrGet3;
    private javax.swing.ButtonGroup btnGrGet4;
    private javax.swing.ButtonGroup btnGrGet5;
    private javax.swing.ButtonGroup btnGrGet6;
    private javax.swing.ButtonGroup btnGrGet7;
    private javax.swing.ButtonGroup btnGrGet8;
    private javax.swing.JButton btnSet;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblGetterOpenDay;
    private javax.swing.JLabel lblGetterOpenDow;
    private javax.swing.JLabel lblGetterOpenHour;
    private javax.swing.JLabel lblGetterOpenMinutes;
    private javax.swing.JLabel lblGetterOpenMonth;
    private javax.swing.JLabel lblGetterOpenYear;
    private javax.swing.JLabel lblIOpenGetterTitle;
    // End of variables declaration//GEN-END:variables
}
