package hvv_admin.dialogs.step05;

import hvv_admin.HVV_Admin;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;
import org.apache.log4j.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yaroslav
 */
public class TechProcessStep05_2_DlgSet extends javax.swing.JDialog {

    static Logger logger = Logger.getLogger(TechProcessStep05_2_DlgSet.class);
    final private HVV_Admin theApp;
    
    public GregorianCalendar m_gdtmDate;
    
    private final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
    ScheduledFuture <?> taskHandle;
    
    public void startPeriodicTask() {
        Runnable task = new Runnable() {
            @Override
            public void run() {
                
                switch( m_gdtmDate.get( Calendar.DAY_OF_WEEK)) {
                    case Calendar.SUNDAY:   lblGetterOpenDow.setText( "вс"); break;
                    case Calendar.MONDAY:   lblGetterOpenDow.setText( "пн"); break;
                    case Calendar.TUESDAY:  lblGetterOpenDow.setText( "вт"); break;
                    case Calendar.WEDNESDAY:lblGetterOpenDow.setText( "ср"); break;
                    case Calendar.THURSDAY: lblGetterOpenDow.setText( "чт"); break;
                    case Calendar.FRIDAY:   lblGetterOpenDow.setText( "пт"); break;
                    case Calendar.SATURDAY: lblGetterOpenDow.setText( "сб"); break;
                    default: lblGetterOpenDow.setText( "-"); break;
                }
                
                lblGetterOpenDay.setText( "" + m_gdtmDate.get( Calendar.DAY_OF_MONTH));
                        
                switch( m_gdtmDate.get( Calendar.MONTH)) {
                    case Calendar.JANUARY:  lblGetterOpenMonth.setText("янв");  break;
                    case Calendar.FEBRUARY: lblGetterOpenMonth.setText("фев");  break;
                    case Calendar.MARCH:    lblGetterOpenMonth.setText("мар");  break;
                    case Calendar.APRIL:    lblGetterOpenMonth.setText("апр");  break;
                    case Calendar.MAY:      lblGetterOpenMonth.setText("май");  break;
                    case Calendar.JUNE:     lblGetterOpenMonth.setText("июн");  break;
                    case Calendar.JULY:     lblGetterOpenMonth.setText("июл");  break;
                    case Calendar.AUGUST:   lblGetterOpenMonth.setText("авг");  break;
                    case Calendar.SEPTEMBER:lblGetterOpenMonth.setText("сен");  break;
                    case Calendar.OCTOBER:  lblGetterOpenMonth.setText("окт");  break;
                    case Calendar.NOVEMBER: lblGetterOpenMonth.setText("ноя");  break;
                    case Calendar.DECEMBER: lblGetterOpenMonth.setText("дек");  break;
                    default:                lblGetterOpenMonth.setText("-");    break;
                }
                
                lblGetterOpenYear.setText( "" + m_gdtmDate.get( Calendar.YEAR));

                lblGetterOpenHour.setText( String.format( "%02d", m_gdtmDate.get( Calendar.HOUR_OF_DAY)));
                lblGetterOpenMinutes.setText( String.format( "%02d", m_gdtmDate.get( Calendar.MINUTE)));
            }
            
        };
        
        taskHandle = scheduler.scheduleAtFixedRate( task, 0, 200, TimeUnit.MILLISECONDS);
    }
    
    public void stopPeriodicTask() {
        taskHandle.cancel( true);
    }
    /**
     * Creates new form TechProcessStep2_1_Dlg
     * @param app
     * @param parent
     * @param modal
     * @param clndr
     */
    public TechProcessStep05_2_DlgSet( HVV_Admin app, java.awt.Frame parent, boolean modal, GregorianCalendar clndr) {
        super( parent, modal);
        theApp = app;
        initComponents();
        
        btnUpDay.setIcon( theApp.GetResources().getIconUp());
        btnUpMonth.setIcon( theApp.GetResources().getIconUp());
        btnUpYear.setIcon( theApp.GetResources().getIconUp());
        btnUpHours.setIcon( theApp.GetResources().getIconUp());
        btnUpMinutes.setIcon( theApp.GetResources().getIconUp());
        
        btnDownDay.setIcon( theApp.GetResources().getIconDown());
        btnDownMonth.setIcon( theApp.GetResources().getIconDown());
        btnDownYear.setIcon( theApp.GetResources().getIconDown());
        btnDownHours.setIcon( theApp.GetResources().getIconDown());
        btnDownMinutes.setIcon( theApp.GetResources().getIconDown());
        
        m_gdtmDate = clndr;
        
        startPeriodicTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrGet1 = new javax.swing.ButtonGroup();
        btnGrGet2 = new javax.swing.ButtonGroup();
        btnGrGet3 = new javax.swing.ButtonGroup();
        btnGrGet4 = new javax.swing.ButtonGroup();
        btnGrGet5 = new javax.swing.ButtonGroup();
        btnGrGet6 = new javax.swing.ButtonGroup();
        btnGrGet7 = new javax.swing.ButtonGroup();
        btnGrGet8 = new javax.swing.ButtonGroup();
        lblIOpenGetterTitle = new javax.swing.JLabel();
        btnUpDay = new javax.swing.JButton();
        btnUpMonth = new javax.swing.JButton();
        btnUpYear = new javax.swing.JButton();
        btnUpHours = new javax.swing.JButton();
        btnUpMinutes = new javax.swing.JButton();
        lblGetterOpenDow = new javax.swing.JLabel();
        lblGetterOpenDay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblGetterOpenMonth = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblGetterOpenYear = new javax.swing.JLabel();
        lblGetterOpenHour = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblGetterOpenMinutes = new javax.swing.JLabel();
        btnDownDay = new javax.swing.JButton();
        btnDownMonth = new javax.swing.JButton();
        btnDownYear = new javax.swing.JButton();
        btnDownHours = new javax.swing.JButton();
        btnDownMinutes = new javax.swing.JButton();
        btnSet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("5.2 Термообезгаживание");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(350, 180));
        setResizable(false);
        getContentPane().setLayout(null);

        lblIOpenGetterTitle.setText("Запустить программу открытия геттера:");
        lblIOpenGetterTitle.setToolTipText("");
        getContentPane().add(lblIOpenGetterTitle);
        lblIOpenGetterTitle.setBounds(10, 0, 330, 40);

        btnUpDay.setIcon(new javax.swing.ImageIcon("/home/yaroslav/HVV_HOME/res/images/up.gif")); // NOI18N
        btnUpDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpDayActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpDay);
        btnUpDay.setBounds(50, 45, 40, 20);

        btnUpMonth.setIcon(new javax.swing.ImageIcon("/home/yaroslav/HVV_HOME/res/images/up.gif")); // NOI18N
        btnUpMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpMonthActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpMonth);
        btnUpMonth.setBounds(100, 45, 50, 20);

        btnUpYear.setIcon(new javax.swing.ImageIcon("/home/yaroslav/HVV_HOME/res/images/up.gif")); // NOI18N
        btnUpYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpYearActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpYear);
        btnUpYear.setBounds(160, 45, 80, 20);

        btnUpHours.setIcon(new javax.swing.ImageIcon("/home/yaroslav/HVV_HOME/res/images/up.gif")); // NOI18N
        btnUpHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpHoursActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpHours);
        btnUpHours.setBounds(250, 45, 40, 20);

        btnUpMinutes.setIcon(new javax.swing.ImageIcon("/home/yaroslav/HVV_HOME/res/images/up.gif")); // NOI18N
        btnUpMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpMinutesActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpMinutes);
        btnUpMinutes.setBounds(300, 45, 40, 20);

        lblGetterOpenDow.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenDow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenDow.setText("-");
        lblGetterOpenDow.setToolTipText("");
        lblGetterOpenDow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenDow.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenDowMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenDow);
        lblGetterOpenDow.setBounds(10, 70, 40, 30);

        lblGetterOpenDay.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenDay.setText("-");
        lblGetterOpenDay.setToolTipText("");
        lblGetterOpenDay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenDay.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenDayMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenDay);
        lblGetterOpenDay.setBounds(50, 70, 40, 30);

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(".");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 70, 10, 30);

        lblGetterOpenMonth.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenMonth.setText("-");
        lblGetterOpenMonth.setToolTipText("");
        lblGetterOpenMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenMonth.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenMonthMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenMonth);
        lblGetterOpenMonth.setBounds(100, 70, 50, 30);

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(".");
        jLabel7.setToolTipText("");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 70, 10, 30);

        lblGetterOpenYear.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenYear.setText("-");
        lblGetterOpenYear.setToolTipText("");
        lblGetterOpenYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenYear.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenYearMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenYear);
        lblGetterOpenYear.setBounds(160, 70, 80, 30);

        lblGetterOpenHour.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenHour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenHour.setText("-");
        lblGetterOpenHour.setToolTipText("");
        lblGetterOpenHour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenHour.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenHourMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenHour);
        lblGetterOpenHour.setBounds(250, 70, 40, 30);

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(":");
        jLabel10.setToolTipText("");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(290, 70, 10, 30);

        lblGetterOpenMinutes.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblGetterOpenMinutes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetterOpenMinutes.setText("-");
        lblGetterOpenMinutes.setToolTipText("");
        lblGetterOpenMinutes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lblGetterOpenMinutes.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblGetterOpenMinutesMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblGetterOpenMinutes);
        lblGetterOpenMinutes.setBounds(300, 70, 40, 30);

        btnDownDay.setIcon(new javax.swing.ImageIcon("/home/yaroslav/HVV_HOME/res/images/down.gif")); // NOI18N
        btnDownDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownDayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDownDay);
        btnDownDay.setBounds(50, 105, 40, 20);

        btnDownMonth.setIcon(new javax.swing.ImageIcon("/home/yaroslav/HVV_HOME/res/images/down.gif")); // NOI18N
        btnDownMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownMonthActionPerformed(evt);
            }
        });
        getContentPane().add(btnDownMonth);
        btnDownMonth.setBounds(100, 105, 50, 20);

        btnDownYear.setIcon(new javax.swing.ImageIcon("/home/yaroslav/HVV_HOME/res/images/down.gif")); // NOI18N
        btnDownYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownYearActionPerformed(evt);
            }
        });
        getContentPane().add(btnDownYear);
        btnDownYear.setBounds(160, 105, 80, 20);

        btnDownHours.setIcon(new javax.swing.ImageIcon("/home/yaroslav/HVV_HOME/res/images/down.gif")); // NOI18N
        btnDownHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownHoursActionPerformed(evt);
            }
        });
        getContentPane().add(btnDownHours);
        btnDownHours.setBounds(250, 105, 40, 20);

        btnDownMinutes.setIcon(new javax.swing.ImageIcon("/home/yaroslav/HVV_HOME/res/images/down.gif")); // NOI18N
        btnDownMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownMinutesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDownMinutes);
        btnDownMinutes.setBounds(300, 105, 40, 20);

        btnSet.setText("Задать");
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });
        getContentPane().add(btnSet);
        btnSet.setBounds(10, 130, 330, 40);

        getAccessibleContext().setAccessibleName("Дата время запуска программы открытия геттера");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        stopPeriodicTask();
        dispose();
    }//GEN-LAST:event_btnSetActionPerformed

    private void lblGetterOpenDowMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenDowMouseWheelMoved
        m_gdtmDate.add( Calendar.DAY_OF_MONTH, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenDowMouseWheelMoved

    private void lblGetterOpenDayMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenDayMouseWheelMoved
        m_gdtmDate.add( Calendar.DAY_OF_MONTH, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenDayMouseWheelMoved

    private void lblGetterOpenMonthMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenMonthMouseWheelMoved
        m_gdtmDate.add( Calendar.MONTH, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenMonthMouseWheelMoved

    private void lblGetterOpenYearMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenYearMouseWheelMoved
        m_gdtmDate.add( Calendar.YEAR, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenYearMouseWheelMoved

    private void lblGetterOpenHourMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenHourMouseWheelMoved
        m_gdtmDate.add( Calendar.HOUR, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenHourMouseWheelMoved

    private void lblGetterOpenMinutesMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblGetterOpenMinutesMouseWheelMoved
       m_gdtmDate.add( Calendar.MINUTE, -1 * evt.getWheelRotation());
    }//GEN-LAST:event_lblGetterOpenMinutesMouseWheelMoved

    private void btnUpDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpDayActionPerformed
        m_gdtmDate.add( Calendar.DAY_OF_MONTH, 1);
    }//GEN-LAST:event_btnUpDayActionPerformed

    private void btnUpMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpMonthActionPerformed
        m_gdtmDate.add( Calendar.MONTH, 1);
    }//GEN-LAST:event_btnUpMonthActionPerformed

    private void btnUpYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpYearActionPerformed
        m_gdtmDate.add( Calendar.YEAR, 1);
    }//GEN-LAST:event_btnUpYearActionPerformed

    private void btnUpHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpHoursActionPerformed
        m_gdtmDate.add( Calendar.HOUR, 1);
    }//GEN-LAST:event_btnUpHoursActionPerformed

    private void btnUpMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpMinutesActionPerformed
        m_gdtmDate.add( Calendar.MINUTE, 1);
    }//GEN-LAST:event_btnUpMinutesActionPerformed

    private void btnDownDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownDayActionPerformed
        m_gdtmDate.add( Calendar.DAY_OF_MONTH, -1);
    }//GEN-LAST:event_btnDownDayActionPerformed

    private void btnDownMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownMonthActionPerformed
        m_gdtmDate.add( Calendar.MONTH, -1);
    }//GEN-LAST:event_btnDownMonthActionPerformed

    private void btnDownYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownYearActionPerformed
        m_gdtmDate.add( Calendar.YEAR, -1);
    }//GEN-LAST:event_btnDownYearActionPerformed

    private void btnDownHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownHoursActionPerformed
        m_gdtmDate.add( Calendar.HOUR, -1);
    }//GEN-LAST:event_btnDownHoursActionPerformed

    private void btnDownMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownMinutesActionPerformed
        m_gdtmDate.add( Calendar.MINUTE, -1);
    }//GEN-LAST:event_btnDownMinutesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_2_DlgSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_2_DlgSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_2_DlgSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep05_2_DlgSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GregorianCalendar gdtmDate = ( GregorianCalendar) Calendar.getInstance();
                gdtmDate.add( Calendar.HOUR, 23);
                TechProcessStep05_2_DlgSet dialog = new TechProcessStep05_2_DlgSet( null, new javax.swing.JFrame(), true, gdtmDate);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownDay;
    private javax.swing.JButton btnDownHours;
    private javax.swing.JButton btnDownMinutes;
    private javax.swing.JButton btnDownMonth;
    private javax.swing.JButton btnDownYear;
    private javax.swing.ButtonGroup btnGrGet1;
    private javax.swing.ButtonGroup btnGrGet2;
    private javax.swing.ButtonGroup btnGrGet3;
    private javax.swing.ButtonGroup btnGrGet4;
    private javax.swing.ButtonGroup btnGrGet5;
    private javax.swing.ButtonGroup btnGrGet6;
    private javax.swing.ButtonGroup btnGrGet7;
    private javax.swing.ButtonGroup btnGrGet8;
    private javax.swing.JButton btnSet;
    private javax.swing.JButton btnUpDay;
    private javax.swing.JButton btnUpHours;
    private javax.swing.JButton btnUpMinutes;
    private javax.swing.JButton btnUpMonth;
    private javax.swing.JButton btnUpYear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblGetterOpenDay;
    private javax.swing.JLabel lblGetterOpenDow;
    private javax.swing.JLabel lblGetterOpenHour;
    private javax.swing.JLabel lblGetterOpenMinutes;
    private javax.swing.JLabel lblGetterOpenMonth;
    private javax.swing.JLabel lblGetterOpenYear;
    private javax.swing.JLabel lblIOpenGetterTitle;
    // End of variables declaration//GEN-END:variables
}
