/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin.dialogs.step05;

import hvv_admin.HVV_Admin;
import hvv_admin.steps.info.TechProcessStepInfo;
import hvv_admin.comm.executor.to.StartProgramExecutor;
import hvv_admin.dialogs.TechProcessStepPanelTemplate;
import java.awt.event.MouseEvent;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class TechProcessStep05Panel extends TechProcessStepPanelTemplate {
    public final int MAXIMIZED_HEIGHT = 180;
    static Logger logger = Logger.getLogger(TechProcessStep05Panel.class);
    /**
     * Creates new form TechProcessStep1Panel
     */
    public TechProcessStep05Panel( HVV_Admin app, boolean bCollapsed) {
        initComponents();
        theApp = app;
        m_bCollapsed = bCollapsed;
        m_nPageNumber = 4;
        m_bFirstOfDoubleClickHeaderDateTime = false;
        
        String strTitle = theApp.GetStepName( 80);
        if( strTitle != null) lbl_05_00_Title.setText( "5. " + strTitle);
        strTitle = theApp.GetStepName( 81);
        if( strTitle != null) lbl_05_01_Title.setText( "5.1 " + strTitle);
        strTitle = theApp.GetStepName( 82);
        if( strTitle != null) lbl_05_02_Title.setText( "5.2 " + strTitle);
        strTitle = theApp.GetStepName( 83);
        if( strTitle != null) lbl_05_03_Title.setText( "5.3 " + strTitle);
        strTitle = theApp.GetStepName( 84);
        if( strTitle != null) lbl_05_04_Title.setText( "5.4 " + strTitle);
        strTitle = theApp.GetStepName( 85);
        if( strTitle != null) lbl_05_05_Title.setText( "5.5 " + strTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_05_00_Date_start = new javax.swing.JLabel();
        lbl_05_00_Time_start = new javax.swing.JLabel();
        lbl_05_00_IcoStep = new javax.swing.JLabel();
        lbl_05_00_Title = new javax.swing.JLabel();
        lbl_05_00_Date_stop = new javax.swing.JLabel();
        lbl_05_00_Time_stop = new javax.swing.JLabel();
        lbl_05_01_Date_start = new javax.swing.JLabel();
        lbl_05_01_Time_start = new javax.swing.JLabel();
        lblAnimation_05_01 = new javax.swing.JLabel();
        lbl_05_01_Title = new javax.swing.JLabel();
        chk_05_04_AutoStart = new javax.swing.JCheckBox();
        lbl_05_01_IcoStep = new javax.swing.JLabel();
        btn_05_01_Next = new javax.swing.JButton();
        lbl_05_01_Date_stop = new javax.swing.JLabel();
        lbl_05_01_Time_stop = new javax.swing.JLabel();
        lbl_05_02_Date_start = new javax.swing.JLabel();
        lbl_05_02_Time_start = new javax.swing.JLabel();
        lblAnimation_05_02 = new javax.swing.JLabel();
        lbl_05_02_Title = new javax.swing.JLabel();
        btn_05_02_Next = new javax.swing.JButton();
        lbl_05_02_Date_stop = new javax.swing.JLabel();
        lbl_05_02_Time_stop = new javax.swing.JLabel();
        lbl_05_03_Date_start = new javax.swing.JLabel();
        lbl_05_03_Time_start = new javax.swing.JLabel();
        lblAnimation_05_03 = new javax.swing.JLabel();
        lbl_05_03_Title = new javax.swing.JLabel();
        lbl_05_04_IcoStep = new javax.swing.JLabel();
        btn_05_03_Next = new javax.swing.JButton();
        lbl_05_03_Date_stop = new javax.swing.JLabel();
        lbl_05_03_Time_stop = new javax.swing.JLabel();
        lbl_05_04_Date_start = new javax.swing.JLabel();
        lbl_05_04_Time_start = new javax.swing.JLabel();
        lblAnimation_05_04 = new javax.swing.JLabel();
        lbl_05_04_Title = new javax.swing.JLabel();
        btn_05_04_Next = new javax.swing.JButton();
        lbl_05_04_Date_stop = new javax.swing.JLabel();
        lbl_05_04_Time_stop = new javax.swing.JLabel();
        lbl_05_05_Date_start = new javax.swing.JLabel();
        lbl_05_05_Time_start = new javax.swing.JLabel();
        lblAnimation_05_05 = new javax.swing.JLabel();
        lbl_05_05_Title = new javax.swing.JLabel();
        chk_05_05_AutoStart = new javax.swing.JCheckBox();
        lbl_05_05_IcoStep = new javax.swing.JLabel();
        btn_05_05_Next = new javax.swing.JButton();
        lbl_05_05_Date_stop = new javax.swing.JLabel();
        lbl_05_05_Time_stop = new javax.swing.JLabel();
        chk_05_01_AutoStart = new javax.swing.JCheckBox();
        chk_05_03_AutoStart = new javax.swing.JCheckBox();
        lbl_05_03_IcoStep = new javax.swing.JLabel();
        btn_05_01_Start = new javax.swing.JButton();
        btn_05_02_Start = new javax.swing.JButton();
        btn_05_03_Start = new javax.swing.JButton();
        btn_05_04_Start = new javax.swing.JButton();
        btn_05_05_Start = new javax.swing.JButton();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1000, 210));
        setMinimumSize(new java.awt.Dimension(1000, 30));
        setLayout(null);

        lbl_05_00_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_00_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_00_Date_start.setText("-");
        lbl_05_00_Date_start.setBorder(null);
        lbl_05_00_Date_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_05_00_Date_startMouseClicked(evt);
            }
        });
        add(lbl_05_00_Date_start);
        lbl_05_00_Date_start.setBounds(0, 0, 90, 25);

        lbl_05_00_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_00_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_00_Time_start.setText("-");
        lbl_05_00_Time_start.setBorder(null);
        lbl_05_00_Time_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_05_00_Time_startMouseClicked(evt);
            }
        });
        add(lbl_05_00_Time_start);
        lbl_05_00_Time_start.setBounds(90, 0, 60, 25);

        lbl_05_00_IcoStep.setBorder(null);
        lbl_05_00_IcoStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_05_00_IcoStepMouseClicked(evt);
            }
        });
        add(lbl_05_00_IcoStep);
        lbl_05_00_IcoStep.setBounds(150, 0, 30, 25);

        lbl_05_00_Title.setText("5. Термообезгаживание");
        lbl_05_00_Title.setBorder(null);
        lbl_05_00_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_05_00_TitleMouseClicked(evt);
            }
        });
        add(lbl_05_00_Title);
        lbl_05_00_Title.setBounds(180, 0, 470, 25);

        lbl_05_00_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_00_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_00_Date_stop.setText("-");
        lbl_05_00_Date_stop.setBorder(null);
        add(lbl_05_00_Date_stop);
        lbl_05_00_Date_stop.setBounds(840, 0, 90, 25);

        lbl_05_00_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_00_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_00_Time_stop.setText("-");
        lbl_05_00_Time_stop.setBorder(null);
        add(lbl_05_00_Time_stop);
        lbl_05_00_Time_stop.setBounds(930, 0, 60, 25);

        lbl_05_01_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_01_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_01_Date_start.setText("-");
        lbl_05_01_Date_start.setBorder(null);
        add(lbl_05_01_Date_start);
        lbl_05_01_Date_start.setBounds(0, 30, 90, 25);

        lbl_05_01_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_01_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_01_Time_start.setText("-");
        lbl_05_01_Time_start.setBorder(null);
        add(lbl_05_01_Time_start);
        lbl_05_01_Time_start.setBounds(90, 30, 60, 25);

        lblAnimation_05_01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_05_01);
        lblAnimation_05_01.setBounds(230, 30, 25, 25);

        lbl_05_01_Title.setText("5.1 Установка печек");
        lbl_05_01_Title.setBorder(null);
        lbl_05_01_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_05_01_TitleMouseClicked(evt);
            }
        });
        add(lbl_05_01_Title);
        lbl_05_01_Title.setBounds(260, 30, 440, 25);

        chk_05_04_AutoStart.setToolTipText("При включённой опции, когда дойдёт очередь, этап 5.4 будет пропущен. При выключенной опции придётся подтвердить.снятие печек.");
        chk_05_04_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_05_04_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_05_04_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_05_04_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_05_04_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_05_04_AutoStart);
        chk_05_04_AutoStart.setBounds(700, 120, 30, 30);

        lbl_05_01_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_01_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_05_01_IcoStep);
        lbl_05_01_IcoStep.setBounds(730, 30, 30, 25);

        btn_05_01_Next.setText("Далее");
        btn_05_01_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_05_01_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_05_01_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_05_01_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_05_01_NextActionPerformed(evt);
            }
        });
        add(btn_05_01_Next);
        btn_05_01_Next.setBounds(770, 30, 60, 30);

        lbl_05_01_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_01_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_01_Date_stop.setText("-");
        lbl_05_01_Date_stop.setBorder(null);
        add(lbl_05_01_Date_stop);
        lbl_05_01_Date_stop.setBounds(840, 30, 90, 25);

        lbl_05_01_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_01_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_01_Time_stop.setText("-");
        lbl_05_01_Time_stop.setBorder(null);
        add(lbl_05_01_Time_stop);
        lbl_05_01_Time_stop.setBounds(930, 30, 60, 25);

        lbl_05_02_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_02_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_02_Date_start.setText("-");
        lbl_05_02_Date_start.setBorder(null);
        add(lbl_05_02_Date_start);
        lbl_05_02_Date_start.setBounds(0, 60, 90, 25);

        lbl_05_02_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_02_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_02_Time_start.setText("-");
        lbl_05_02_Time_start.setBorder(null);
        add(lbl_05_02_Time_start);
        lbl_05_02_Time_start.setBounds(90, 60, 60, 25);

        lblAnimation_05_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_05_02);
        lblAnimation_05_02.setBounds(230, 60, 25, 25);

        lbl_05_02_Title.setText("5.2 Включение PID-регулирования печек");
        lbl_05_02_Title.setBorder(null);
        lbl_05_02_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_05_02_TitleMouseClicked(evt);
            }
        });
        add(lbl_05_02_Title);
        lbl_05_02_Title.setBounds(260, 60, 440, 25);

        btn_05_02_Next.setText("Далее");
        btn_05_02_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_05_02_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_05_02_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        add(btn_05_02_Next);
        btn_05_02_Next.setBounds(770, 60, 60, 30);

        lbl_05_02_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_02_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_02_Date_stop.setText("-");
        lbl_05_02_Date_stop.setBorder(null);
        add(lbl_05_02_Date_stop);
        lbl_05_02_Date_stop.setBounds(840, 60, 90, 25);

        lbl_05_02_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_02_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_02_Time_stop.setText("-");
        lbl_05_02_Time_stop.setBorder(null);
        add(lbl_05_02_Time_stop);
        lbl_05_02_Time_stop.setBounds(930, 60, 60, 25);

        lbl_05_03_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_03_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_03_Date_start.setText("-");
        lbl_05_03_Date_start.setBorder(null);
        add(lbl_05_03_Date_start);
        lbl_05_03_Date_start.setBounds(0, 90, 90, 25);

        lbl_05_03_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_03_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_03_Time_start.setText("-");
        lbl_05_03_Time_start.setBorder(null);
        add(lbl_05_03_Time_start);
        lbl_05_03_Time_start.setBounds(90, 90, 60, 25);

        lblAnimation_05_03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_05_03);
        lblAnimation_05_03.setBounds(230, 90, 25, 25);

        lbl_05_03_Title.setText("5.3 Снятие печек");
        lbl_05_03_Title.setBorder(null);
        lbl_05_03_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_05_03_TitleMouseClicked(evt);
            }
        });
        add(lbl_05_03_Title);
        lbl_05_03_Title.setBounds(260, 90, 440, 25);

        lbl_05_04_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_04_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_05_04_IcoStep);
        lbl_05_04_IcoStep.setBounds(730, 120, 30, 25);

        btn_05_03_Next.setText("Далее");
        btn_05_03_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_05_03_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_05_03_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        add(btn_05_03_Next);
        btn_05_03_Next.setBounds(770, 90, 60, 30);

        lbl_05_03_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_03_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_03_Date_stop.setText("-");
        lbl_05_03_Date_stop.setBorder(null);
        add(lbl_05_03_Date_stop);
        lbl_05_03_Date_stop.setBounds(840, 90, 90, 25);

        lbl_05_03_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_03_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_03_Time_stop.setText("-");
        lbl_05_03_Time_stop.setBorder(null);
        add(lbl_05_03_Time_stop);
        lbl_05_03_Time_stop.setBounds(930, 90, 60, 25);

        lbl_05_04_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_04_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_04_Date_start.setText("-");
        lbl_05_04_Date_start.setBorder(null);
        add(lbl_05_04_Date_start);
        lbl_05_04_Date_start.setBounds(0, 120, 90, 25);

        lbl_05_04_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_04_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_04_Time_start.setText("-");
        lbl_05_04_Time_start.setBorder(null);
        add(lbl_05_04_Time_start);
        lbl_05_04_Time_start.setBounds(90, 120, 60, 25);

        lblAnimation_05_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_05_04);
        lblAnimation_05_04.setBounds(230, 120, 25, 25);

        lbl_05_04_Title.setText("5.4 Заполнение рабочей смесью");
        lbl_05_04_Title.setBorder(null);
        lbl_05_04_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_05_04_TitleMouseClicked(evt);
            }
        });
        add(lbl_05_04_Title);
        lbl_05_04_Title.setBounds(260, 120, 440, 25);

        btn_05_04_Next.setText("Далее");
        btn_05_04_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_05_04_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_05_04_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_05_04_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_05_04_NextActionPerformed(evt);
            }
        });
        add(btn_05_04_Next);
        btn_05_04_Next.setBounds(770, 120, 60, 30);

        lbl_05_04_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_04_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_04_Date_stop.setText("-");
        lbl_05_04_Date_stop.setBorder(null);
        add(lbl_05_04_Date_stop);
        lbl_05_04_Date_stop.setBounds(840, 120, 90, 25);

        lbl_05_04_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_04_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_04_Time_stop.setText("-");
        lbl_05_04_Time_stop.setBorder(null);
        add(lbl_05_04_Time_stop);
        lbl_05_04_Time_stop.setBounds(930, 120, 60, 25);

        lbl_05_05_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_05_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_05_Date_start.setText("-");
        lbl_05_05_Date_start.setBorder(null);
        add(lbl_05_05_Date_start);
        lbl_05_05_Date_start.setBounds(0, 150, 90, 25);

        lbl_05_05_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_05_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_05_Time_start.setText("-");
        lbl_05_05_Time_start.setBorder(null);
        add(lbl_05_05_Time_start);
        lbl_05_05_Time_start.setBounds(90, 150, 60, 25);

        lblAnimation_05_05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_05_05);
        lblAnimation_05_05.setBounds(230, 150, 25, 25);

        lbl_05_05_Title.setText("5.5 Выдержка");
        lbl_05_05_Title.setBorder(null);
        lbl_05_05_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_05_05_TitleMouseClicked(evt);
            }
        });
        add(lbl_05_05_Title);
        lbl_05_05_Title.setBounds(260, 150, 440, 25);

        chk_05_05_AutoStart.setToolTipText("При включённой опции, когда дойдёт очередь, этап 5.5 начнётся автоматически. При выключенной опции этап придётся запустить вручную.");
        chk_05_05_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_05_05_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_05_05_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_05_05_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_05_05_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_05_05_AutoStart);
        chk_05_05_AutoStart.setBounds(700, 150, 30, 30);

        lbl_05_05_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_05_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_05_05_IcoStep);
        lbl_05_05_IcoStep.setBounds(730, 150, 30, 25);

        btn_05_05_Next.setText("Далее");
        btn_05_05_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_05_05_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_05_05_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_05_05_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_05_05_NextActionPerformed(evt);
            }
        });
        add(btn_05_05_Next);
        btn_05_05_Next.setBounds(770, 150, 60, 30);

        lbl_05_05_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_05_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_05_Date_stop.setText("-");
        lbl_05_05_Date_stop.setBorder(null);
        add(lbl_05_05_Date_stop);
        lbl_05_05_Date_stop.setBounds(840, 150, 90, 25);

        lbl_05_05_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_05_05_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_05_Time_stop.setText("-");
        lbl_05_05_Time_stop.setBorder(null);
        add(lbl_05_05_Time_stop);
        lbl_05_05_Time_stop.setBounds(930, 150, 60, 25);

        chk_05_01_AutoStart.setToolTipText("При включённой опции, когда дойдёт очередь, этап 5.1 начнётся автоматически. При выключенной опции этап придётся запустить вручную.");
        chk_05_01_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_05_01_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_05_01_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_05_01_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_05_01_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_05_01_AutoStart);
        chk_05_01_AutoStart.setBounds(700, 30, 30, 30);

        chk_05_03_AutoStart.setToolTipText("При включённой опции, когда дойдёт очередь, этап 5.2 будет пропущен. При выключенной опции придётся подтвердить.установку печек.");
        chk_05_03_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_05_03_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_05_03_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_05_03_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_05_03_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_05_03_AutoStart);
        chk_05_03_AutoStart.setBounds(700, 90, 30, 30);

        lbl_05_03_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_05_03_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_05_03_IcoStep);
        lbl_05_03_IcoStep.setBounds(730, 90, 30, 25);

        btn_05_01_Start.setText("Старт");
        btn_05_01_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_05_01_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_05_01_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_05_01_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_05_01_StartActionPerformed(evt);
            }
        });
        add(btn_05_01_Start);
        btn_05_01_Start.setBounds(160, 30, 60, 30);

        btn_05_02_Start.setText("Старт");
        btn_05_02_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_05_02_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_05_02_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_05_02_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_05_02_StartActionPerformed(evt);
            }
        });
        add(btn_05_02_Start);
        btn_05_02_Start.setBounds(160, 60, 60, 30);

        btn_05_03_Start.setText("Старт");
        btn_05_03_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_05_03_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_05_03_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_05_03_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_05_03_StartActionPerformed(evt);
            }
        });
        add(btn_05_03_Start);
        btn_05_03_Start.setBounds(160, 90, 60, 30);

        btn_05_04_Start.setText("Старт");
        btn_05_04_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_05_04_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_05_04_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_05_04_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_05_04_StartActionPerformed(evt);
            }
        });
        add(btn_05_04_Start);
        btn_05_04_Start.setBounds(160, 120, 60, 30);

        btn_05_05_Start.setText("Старт");
        btn_05_05_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_05_05_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_05_05_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_05_05_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_05_05_StartActionPerformed(evt);
            }
        });
        add(btn_05_05_Start);
        btn_05_05_Start.setBounds(160, 150, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_05_00_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_05_00_TitleMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_05_00_TitleMouseClicked

    private void lbl_05_00_IcoStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_05_00_IcoStepMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_05_00_IcoStepMouseClicked

    private void btn_05_01_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_05_01_NextActionPerformed
        // STUB - ручной этап
        /*
        if( theApp.m_pMainWnd.m_EmuTimer.isRunning()) {
            //мы в процессе исполнения подэтапа 5.1 переходим к следующему подэтапу 5.2 или 5.3
            theApp.m_pMainWnd.m_EmuTimer.stop();
            if( theApp.GetMapSteps().containsKey( "081")) {
                TechProcessStepInfo info = ( TechProcessStepInfo) theApp.GetMapSteps().get( "081");
                info.SetStopDateAsCurrent();
                theApp.NextCurrentStep();
                
                info = new TechProcessStepInfo( theApp);
                info.SetStartDateAsCurrent();
                theApp.GetMapSteps().put( "082", info);
                
                if( chk_05_02_AutoStart.isSelected()) {
                    //если отмечена опция - мы должны пропустить этап 5.2 установка печек
                    info.SetStopDateAsCurrent();
                    
                    //и в зависимости от опции начать или просто встать на этап 5.3
                    theApp.NextCurrentStep();
                    
                    if( chk_05_03_AutoStart.isSelected()) {
                        info = new TechProcessStepInfo( theApp);
                        info.SetStartDateAsCurrent();
                        theApp.GetMapSteps().put( "083", info);
                        theApp.m_pMainWnd.m_EmuTimer.start();
                    }
                    
                }
                else {
                    theApp.ShowDlg5_2();
                }
                
                SetState();
                theApp.m_pMainWnd.m_pPanel.Reposition();
            }
            else {
                logger.fatal( "Мы заканчиваем этап 081, а инфы на него до сих пор нет!");
            }
        }
        else {
            //мы начинаем процесс
            TechProcessStepInfo info = new TechProcessStepInfo( theApp);
            info.SetStartDateAsCurrent();
            theApp.GetMapSteps().put( "081", info);
            theApp.m_pMainWnd.m_EmuTimer.start();
            SetState();
        }
        */
    }//GEN-LAST:event_btn_05_01_NextActionPerformed

    private void btn_05_05_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_05_05_NextActionPerformed
        if( theApp.IsCurrentStepInProgress() == false)
            return;
        
        //мы в процессе исполнения подэтапа 5.5 "выдержка", переходим к следующему подэтапу 6.1 "Измерение ВАХ" (процесс ручной)
        //theApp.m_pMainWnd.m_EmuTimer.stop();
        if( theApp.IsStepMapContainsKey("085")) {
            TechProcessStepInfo info = theApp.GetStepInfo( "085");

            info.SetStopDateAsCurrent();
            info.SetStopReportTitle( "Завершение выдержки");
            info.SetStopP5( theApp.GetFromPoller( "005.01"));
            info.SetStopP6( theApp.GetFromPoller( "006.01"));
            info.SetStopP7( theApp.GetFromPoller( "007.01"));

            theApp.NextCurrentStep();

            info = new TechProcessStepInfo( theApp);
            info.SetStartDateAsCurrent();
            info.SetStartReportTitle( "Измерение ВАХ");
            info.SetStartP5( theApp.GetFromPoller( "005.01"));
            info.SetStartP6( theApp.GetFromPoller( "006.01"));
            info.SetStartP7( theApp.GetFromPoller( "007.01"));

            theApp.SaveStepInfo( "101", info, true);

            theApp.m_pMainWnd.m_pPanel.SetStates();
            theApp.m_ReportGenerator.Generate();
            theApp.m_pMainWnd.m_pPanel.Reposition();

            theApp.ShowDlg6_1A();
        }
        else {
            logger.fatal( "Мы заканчиваем этап 085, а инфы на него до сих пор нет!");
        }   
    }//GEN-LAST:event_btn_05_05_NextActionPerformed

    private void btn_05_04_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_05_04_NextActionPerformed
        DefaultNextButtonProcessing( "084", "Старт напуска рабочей смеси", "Завершение напуска рабочей смеси",
                                       "085", "Старт выдержки", chk_05_05_AutoStart, logger, false);
    }//GEN-LAST:event_btn_05_04_NextActionPerformed

    private void btn_05_01_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_05_01_StartActionPerformed
        // STUB - ручной этап
    }//GEN-LAST:event_btn_05_01_StartActionPerformed

    private void btn_05_04_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_05_04_StartActionPerformed
        DefaultStartButtonProcessing( "084", "Старт напуска рабочей смеси", "Завершение напуска рабочей смеси",
                                       "085", "Старт выдержки", chk_05_05_AutoStart, logger, false);
    }//GEN-LAST:event_btn_05_04_StartActionPerformed

    private void btn_05_05_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_05_05_StartActionPerformed
        //мы начинаем процесс
        TechProcessStepInfo info = new TechProcessStepInfo( theApp);
        
        info.SetStartDateAsCurrent();
        info.SetStartReportTitle( "Старт выдержки");
        info.SetStartP5( theApp.GetFromPoller( "005.01"));
        info.SetStartP6( theApp.GetFromPoller( "006.01"));
        info.SetStartP7( theApp.GetFromPoller( "007.01"));

        theApp.SaveStepInfo( "085", info, true);

        theApp.m_ReportGenerator.Generate();

        theApp.SetCurrentStepInProgress( true);
        StartProgramExecutor executor = new StartProgramExecutor( theApp, "AdminStep_5.5.xml");
        executor.StartThread();

        SetState();
    }//GEN-LAST:event_btn_05_05_StartActionPerformed

    private void btn_05_02_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_05_02_StartActionPerformed
        // STUB - ручной этап
    }//GEN-LAST:event_btn_05_02_StartActionPerformed

    private void btn_05_03_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_05_03_StartActionPerformed
        // STUB - ручной этап
    }//GEN-LAST:event_btn_05_03_StartActionPerformed

    private void lbl_05_00_Date_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_05_00_Date_startMouseClicked
        ProcessHeaderDateTimeClick( 5);
    }//GEN-LAST:event_lbl_05_00_Date_startMouseClicked

    private void lbl_05_00_Time_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_05_00_Time_startMouseClicked
        ProcessHeaderDateTimeClick( 5);
    }//GEN-LAST:event_lbl_05_00_Time_startMouseClicked

    private void lbl_05_01_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_05_01_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 81);
        }
    }//GEN-LAST:event_lbl_05_01_TitleMouseClicked

    private void lbl_05_02_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_05_02_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 82);
        }
    }//GEN-LAST:event_lbl_05_02_TitleMouseClicked

    private void lbl_05_03_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_05_03_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 83);
        }
    }//GEN-LAST:event_lbl_05_03_TitleMouseClicked

    private void lbl_05_04_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_05_04_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 84);
        }
    }//GEN-LAST:event_lbl_05_04_TitleMouseClicked

    private void lbl_05_05_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_05_05_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 85);
        }
    }//GEN-LAST:event_lbl_05_05_TitleMouseClicked

    public void SetState() {
        if( theApp.GetCurrentStep() / 20 == m_nPageNumber)
            m_bCollapsed = false;
        
        //5. Термообезгаживание
        FillHeaderStepDates( "081", lbl_05_00_Date_start, lbl_05_00_Time_start, "085", lbl_05_00_Date_stop, lbl_05_00_Time_stop);
        
        lbl_05_00_IcoStep.setIcon( m_bCollapsed ? theApp.GetResources().getIconTriaRight() : theApp.GetResources().getIconTriaDown());
        
        lbl_05_00_Title.setFont( theApp.GetCurrentStep() / 20 == m_nPageNumber ? theApp.GetBoldFont() : theApp.GetUsualFont());
        lbl_05_00_Title.setEnabled( theApp.GetCurrentStep() / 20 <= m_nPageNumber);
        
        
        if( m_bCollapsed == false) {
            // 5.1 Установка печек (HAND STEP)
            FillStepDates( "081", lbl_05_01_Date_start, lbl_05_01_Time_start, lbl_05_01_Date_stop, lbl_05_01_Time_stop);

            lbl_05_01_Title.setFont( theApp.GetCurrentStep() == 81 ? theApp.GetBoldFont() : theApp.GetUsualFont());
            lbl_05_01_Title.setEnabled( theApp.GetCurrentStep() <= 81);
            
            chk_05_01_AutoStart.setEnabled( theApp.GetCurrentStep() < 81);
            
            btn_05_01_Start.setVisible( false);
            btn_05_01_Next.setVisible( false);
            
            
            // 5.2 Включение PID-регулирования печек (HAND STEP)
            FillStepDates( "082", lbl_05_02_Date_start, lbl_05_02_Time_start, lbl_05_02_Date_stop, lbl_05_02_Time_stop);

            lbl_05_02_Title.setFont( theApp.GetCurrentStep() == 82 ? theApp.GetBoldFont() : theApp.GetUsualFont());
            lbl_05_02_Title.setEnabled( theApp.GetCurrentStep() <= 82);

            btn_05_02_Start.setVisible( false);
            btn_05_02_Next.setVisible( false);
            
            
            // 5.3 Снятие печек (HAND STEP)
            FillStepDates( "083", lbl_05_03_Date_start, lbl_05_03_Time_start, lbl_05_03_Date_stop, lbl_05_03_Time_stop);

            lbl_05_03_Title.setFont( theApp.GetCurrentStep() == 83 ? theApp.GetBoldFont() : theApp.GetUsualFont());
            lbl_05_03_Title.setEnabled( theApp.GetCurrentStep() <= 83);

            chk_05_03_AutoStart.setEnabled( theApp.GetCurrentStep() < 83);
            
            btn_05_03_Start.setVisible( false);
            btn_05_03_Next.setVisible( false);
            
            
            //5.4 Заполнение рабочей смесью
            FillAutoExecutedSubStep(84,
                                    lbl_05_04_Date_start, lbl_05_04_Time_start, lblAnimation_05_04,
                                    btn_05_04_Start, lbl_05_04_Title, chk_05_04_AutoStart, lbl_05_04_IcoStep, btn_05_04_Next,
                                    lbl_05_04_Date_stop, lbl_05_04_Time_stop);
            
            //5.5 Выдержка
            FillAutoExecutedSubStep(85,
                                    lbl_05_05_Date_start, lbl_05_05_Time_start, lblAnimation_05_05,
                                    btn_05_05_Start, lbl_05_05_Title, chk_05_05_AutoStart, lbl_05_05_IcoStep, btn_05_05_Next,
                                    lbl_05_05_Date_stop, lbl_05_05_Time_stop);

        }
        
        chk_05_03_AutoStart.setEnabled( false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_05_01_Next;
    public javax.swing.JButton btn_05_01_Start;
    private javax.swing.JButton btn_05_02_Next;
    public javax.swing.JButton btn_05_02_Start;
    private javax.swing.JButton btn_05_03_Next;
    public javax.swing.JButton btn_05_03_Start;
    private javax.swing.JButton btn_05_04_Next;
    public javax.swing.JButton btn_05_04_Start;
    private javax.swing.JButton btn_05_05_Next;
    public javax.swing.JButton btn_05_05_Start;
    public javax.swing.JCheckBox chk_05_01_AutoStart;
    public javax.swing.JCheckBox chk_05_03_AutoStart;
    public javax.swing.JCheckBox chk_05_04_AutoStart;
    public javax.swing.JCheckBox chk_05_05_AutoStart;
    public javax.swing.JLabel lblAnimation_05_01;
    public javax.swing.JLabel lblAnimation_05_02;
    public javax.swing.JLabel lblAnimation_05_03;
    public javax.swing.JLabel lblAnimation_05_04;
    public javax.swing.JLabel lblAnimation_05_05;
    public javax.swing.JLabel lbl_05_00_Date_start;
    private javax.swing.JLabel lbl_05_00_Date_stop;
    private javax.swing.JLabel lbl_05_00_IcoStep;
    public javax.swing.JLabel lbl_05_00_Time_start;
    private javax.swing.JLabel lbl_05_00_Time_stop;
    private javax.swing.JLabel lbl_05_00_Title;
    private javax.swing.JLabel lbl_05_01_Date_start;
    private javax.swing.JLabel lbl_05_01_Date_stop;
    public javax.swing.JLabel lbl_05_01_IcoStep;
    private javax.swing.JLabel lbl_05_01_Time_start;
    private javax.swing.JLabel lbl_05_01_Time_stop;
    private javax.swing.JLabel lbl_05_01_Title;
    private javax.swing.JLabel lbl_05_02_Date_start;
    private javax.swing.JLabel lbl_05_02_Date_stop;
    private javax.swing.JLabel lbl_05_02_Time_start;
    private javax.swing.JLabel lbl_05_02_Time_stop;
    private javax.swing.JLabel lbl_05_02_Title;
    private javax.swing.JLabel lbl_05_03_Date_start;
    private javax.swing.JLabel lbl_05_03_Date_stop;
    public javax.swing.JLabel lbl_05_03_IcoStep;
    private javax.swing.JLabel lbl_05_03_Time_start;
    private javax.swing.JLabel lbl_05_03_Time_stop;
    private javax.swing.JLabel lbl_05_03_Title;
    private javax.swing.JLabel lbl_05_04_Date_start;
    private javax.swing.JLabel lbl_05_04_Date_stop;
    public javax.swing.JLabel lbl_05_04_IcoStep;
    private javax.swing.JLabel lbl_05_04_Time_start;
    private javax.swing.JLabel lbl_05_04_Time_stop;
    private javax.swing.JLabel lbl_05_04_Title;
    private javax.swing.JLabel lbl_05_05_Date_start;
    private javax.swing.JLabel lbl_05_05_Date_stop;
    public javax.swing.JLabel lbl_05_05_IcoStep;
    private javax.swing.JLabel lbl_05_05_Time_start;
    private javax.swing.JLabel lbl_05_05_Time_stop;
    private javax.swing.JLabel lbl_05_05_Title;
    // End of variables declaration//GEN-END:variables
}
