/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin.dialogs.step09;

import hvv_admin.HVV_Admin;
import hvv_admin.comm.executor.to.StartProgramExecutor;
import hvv_admin.dialogs.TechProcessStepPanelTemplate;
import hvv_admin.steps.info.TechProcessStepInfo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.Timer;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class TechProcessStep09Panel extends TechProcessStepPanelTemplate {
    public final int MAXIMIZED_HEIGHT = 300;
    static Logger logger = Logger.getLogger(TechProcessStep09Panel.class);
    
    /**
     * Creates new form TechProcessStep1Panel
     */
    public TechProcessStep09Panel( HVV_Admin app, boolean bCollapsed) {
        initComponents();
        theApp = app;
        m_bCollapsed = bCollapsed;
        m_nPageNumber = 8;
        m_bFirstOfDoubleClickHeaderDateTime = false;
        
        String strTitle = theApp.GetStepName( 160);
        if( strTitle != null) lbl_09_00_Title.setText( "9. " + strTitle);
        strTitle = theApp.GetStepName( 161);
        if( strTitle != null) lbl_09_01_Title.setText( "9.1 " + strTitle);
        strTitle = theApp.GetStepName( 162);
        if( strTitle != null) lbl_09_02_Title.setText( "9.2 " + strTitle);
        strTitle = theApp.GetStepName( 163);
        if( strTitle != null) lbl_09_03_Title.setText( "9.3 " + strTitle);
        strTitle = theApp.GetStepName( 164);
        if( strTitle != null) lbl_09_04_Title.setText( "9.4 " + strTitle);
        strTitle = theApp.GetStepName( 165);
        if( strTitle != null) lbl_09_05_Title.setText( "9.5 " + strTitle);
        strTitle = theApp.GetStepName( 166);
        if( strTitle != null) lbl_09_06_Title.setText( "9.6 " + strTitle);
        strTitle = theApp.GetStepName( 167);
        if( strTitle != null) lbl_09_07_Title.setText( "9.7 " + strTitle);
        strTitle = theApp.GetStepName( 168);
        if( strTitle != null) lbl_09_08_Title.setText( "9.8 " + strTitle);
        strTitle = theApp.GetStepName( 169);
        if( strTitle != null) lbl_09_09_Title.setText( "9.9 " + strTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_09_00_Date_start = new javax.swing.JLabel();
        lbl_09_00_Time_start = new javax.swing.JLabel();
        lbl_09_00_IcoStep = new javax.swing.JLabel();
        lbl_09_00_Title = new javax.swing.JLabel();
        lbl_09_00_Date_stop = new javax.swing.JLabel();
        lbl_09_00_Time_stop = new javax.swing.JLabel();
        lbl_09_01_Date_start = new javax.swing.JLabel();
        lbl_09_01_Time_start = new javax.swing.JLabel();
        lblAnimation_09_01 = new javax.swing.JLabel();
        lbl_09_01_Title = new javax.swing.JLabel();
        chk_09_01_AutoStart = new javax.swing.JCheckBox();
        lbl_09_01_IcoStep = new javax.swing.JLabel();
        btn_09_01_Next = new javax.swing.JButton();
        lbl_09_01_Date_stop = new javax.swing.JLabel();
        lbl_09_01_Time_stop = new javax.swing.JLabel();
        lbl_09_02_Date_start = new javax.swing.JLabel();
        lbl_09_02_Time_start = new javax.swing.JLabel();
        lblAnimation_09_02 = new javax.swing.JLabel();
        lbl_09_02_Title = new javax.swing.JLabel();
        lbl_09_02_IcoStep = new javax.swing.JLabel();
        chk_09_02_AutoStart = new javax.swing.JCheckBox();
        btn_09_02_Next = new javax.swing.JButton();
        lbl_09_02_Date_stop = new javax.swing.JLabel();
        lbl_09_02_Time_stop = new javax.swing.JLabel();
        lbl_09_03_Date_start = new javax.swing.JLabel();
        lbl_09_03_Time_start = new javax.swing.JLabel();
        lblAnimation_09_03 = new javax.swing.JLabel();
        lbl_09_03_Title = new javax.swing.JLabel();
        chk_09_03_AutoStart = new javax.swing.JCheckBox();
        lbl_09_03_IcoStep = new javax.swing.JLabel();
        btn_09_03_Next = new javax.swing.JButton();
        lbl_09_03_Date_stop = new javax.swing.JLabel();
        lbl_09_03_Time_stop = new javax.swing.JLabel();
        lbl_09_04_Date_start = new javax.swing.JLabel();
        lbl_09_04_Time_start = new javax.swing.JLabel();
        lblAnimation_09_04 = new javax.swing.JLabel();
        lbl_09_04_Title = new javax.swing.JLabel();
        chk_09_04_AutoStart = new javax.swing.JCheckBox();
        lbl_09_04_IcoStep = new javax.swing.JLabel();
        btn_09_04_Next = new javax.swing.JButton();
        lbl_09_04_Date_stop = new javax.swing.JLabel();
        lbl_09_04_Time_stop = new javax.swing.JLabel();
        lbl_09_05_Date_start = new javax.swing.JLabel();
        lbl_09_05_Time_start = new javax.swing.JLabel();
        lblAnimation_09_05 = new javax.swing.JLabel();
        lbl_09_05_Title = new javax.swing.JLabel();
        chk_09_05_AutoStart = new javax.swing.JCheckBox();
        lbl_09_05_IcoStep = new javax.swing.JLabel();
        btn_09_05_Next = new javax.swing.JButton();
        lbl_09_05_Date_stop = new javax.swing.JLabel();
        lbl_09_05_Time_stop = new javax.swing.JLabel();
        lbl_09_06_Date_start = new javax.swing.JLabel();
        lbl_09_06_Time_start = new javax.swing.JLabel();
        lblAnimation_09_06 = new javax.swing.JLabel();
        lbl_09_06_Title = new javax.swing.JLabel();
        chk_09_06_AutoStart = new javax.swing.JCheckBox();
        lbl_09_06_IcoStep = new javax.swing.JLabel();
        btn_09_06_Next = new javax.swing.JButton();
        lbl_09_06_Date_stop = new javax.swing.JLabel();
        lbl_09_06_Time_stop = new javax.swing.JLabel();
        lbl_09_07_Date_start = new javax.swing.JLabel();
        lbl_09_07_Time_start = new javax.swing.JLabel();
        lblAnimation_09_07 = new javax.swing.JLabel();
        lbl_09_07_Title = new javax.swing.JLabel();
        chk_09_07_AutoStart = new javax.swing.JCheckBox();
        lbl_09_07_IcoStep = new javax.swing.JLabel();
        btn_09_07_Next = new javax.swing.JButton();
        lbl_09_07_Date_stop = new javax.swing.JLabel();
        lbl_09_07_Time_stop = new javax.swing.JLabel();
        lbl_09_08_Date_start = new javax.swing.JLabel();
        lbl_09_08_Time_start = new javax.swing.JLabel();
        lblAnimation_09_08 = new javax.swing.JLabel();
        lbl_09_08_Title = new javax.swing.JLabel();
        chk_09_08_AutoStart = new javax.swing.JCheckBox();
        lbl_09_08_IcoStep = new javax.swing.JLabel();
        btn_09_08_Next = new javax.swing.JButton();
        lbl_09_08_Date_stop = new javax.swing.JLabel();
        lbl_09_08_Time_stop = new javax.swing.JLabel();
        lbl_09_09_Date_start = new javax.swing.JLabel();
        lbl_09_09_Time_start = new javax.swing.JLabel();
        lblAnimation_09_09 = new javax.swing.JLabel();
        lbl_09_09_Title = new javax.swing.JLabel();
        chk_09_09_AutoStart = new javax.swing.JCheckBox();
        lbl_09_09_IcoStep = new javax.swing.JLabel();
        btn_09_09_Next = new javax.swing.JButton();
        lbl_09_09_Date_stop = new javax.swing.JLabel();
        lbl_09_09_Time_stop = new javax.swing.JLabel();
        btn_09_01_Start = new javax.swing.JButton();
        btn_09_02_Start = new javax.swing.JButton();
        btn_09_03_Start = new javax.swing.JButton();
        btn_09_04_Start = new javax.swing.JButton();
        btn_09_05_Start = new javax.swing.JButton();
        btn_09_06_Start = new javax.swing.JButton();
        btn_09_07_Start = new javax.swing.JButton();
        btn_09_08_Start = new javax.swing.JButton();
        btn_09_09_Start = new javax.swing.JButton();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1000, 300));
        setMinimumSize(new java.awt.Dimension(1000, 30));
        setLayout(null);

        lbl_09_00_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_00_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_00_Date_start.setText("-");
        lbl_09_00_Date_start.setBorder(null);
        lbl_09_00_Date_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_00_Date_startMouseClicked(evt);
            }
        });
        add(lbl_09_00_Date_start);
        lbl_09_00_Date_start.setBounds(0, 0, 90, 25);

        lbl_09_00_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_00_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_00_Time_start.setText("-");
        lbl_09_00_Time_start.setBorder(null);
        lbl_09_00_Time_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_00_Time_startMouseClicked(evt);
            }
        });
        add(lbl_09_00_Time_start);
        lbl_09_00_Time_start.setBounds(90, 0, 60, 25);

        lbl_09_00_IcoStep.setBorder(null);
        lbl_09_00_IcoStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_00_IcoStepMouseClicked(evt);
            }
        });
        add(lbl_09_00_IcoStep);
        lbl_09_00_IcoStep.setBounds(150, 0, 30, 25);

        lbl_09_00_Title.setText("9. Тренировка в тренировочной смеси");
        lbl_09_00_Title.setBorder(null);
        lbl_09_00_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_00_TitleMouseClicked(evt);
            }
        });
        add(lbl_09_00_Title);
        lbl_09_00_Title.setBounds(180, 0, 470, 25);

        lbl_09_00_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_00_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_00_Date_stop.setText("-");
        lbl_09_00_Date_stop.setBorder(null);
        add(lbl_09_00_Date_stop);
        lbl_09_00_Date_stop.setBounds(840, 0, 90, 25);

        lbl_09_00_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_00_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_00_Time_stop.setText("-");
        lbl_09_00_Time_stop.setBorder(null);
        add(lbl_09_00_Time_stop);
        lbl_09_00_Time_stop.setBounds(930, 0, 60, 25);

        lbl_09_01_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_01_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_01_Date_start.setText("-");
        lbl_09_01_Date_start.setBorder(null);
        add(lbl_09_01_Date_start);
        lbl_09_01_Date_start.setBounds(0, 30, 90, 25);

        lbl_09_01_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_01_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_01_Time_start.setText("-");
        lbl_09_01_Time_start.setBorder(null);
        add(lbl_09_01_Time_start);
        lbl_09_01_Time_start.setBounds(90, 30, 60, 25);

        lblAnimation_09_01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_09_01);
        lblAnimation_09_01.setBounds(230, 30, 25, 25);

        lbl_09_01_Title.setText("9.1  Напуск тренировочной смеси в приборы");
        lbl_09_01_Title.setBorder(null);
        lbl_09_01_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_01_TitleMouseClicked(evt);
            }
        });
        add(lbl_09_01_Title);
        lbl_09_01_Title.setBounds(260, 30, 440, 25);

        chk_09_01_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_09_01_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_09_01_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_09_01_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_09_01_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_09_01_AutoStart);
        chk_09_01_AutoStart.setBounds(700, 30, 30, 30);

        lbl_09_01_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_01_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_09_01_IcoStep);
        lbl_09_01_IcoStep.setBounds(730, 30, 30, 25);

        btn_09_01_Next.setText("Далее");
        btn_09_01_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_01_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_01_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_01_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_01_NextActionPerformed(evt);
            }
        });
        add(btn_09_01_Next);
        btn_09_01_Next.setBounds(770, 30, 60, 30);

        lbl_09_01_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_01_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_01_Date_stop.setText("-");
        lbl_09_01_Date_stop.setBorder(null);
        add(lbl_09_01_Date_stop);
        lbl_09_01_Date_stop.setBounds(840, 30, 90, 25);

        lbl_09_01_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_01_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_01_Time_stop.setText("-");
        lbl_09_01_Time_stop.setBorder(null);
        add(lbl_09_01_Time_stop);
        lbl_09_01_Time_stop.setBounds(930, 30, 60, 25);

        lbl_09_02_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_02_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_02_Date_start.setText("-");
        lbl_09_02_Date_start.setBorder(null);
        add(lbl_09_02_Date_start);
        lbl_09_02_Date_start.setBounds(0, 60, 90, 25);

        lbl_09_02_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_02_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_02_Time_start.setText("-");
        lbl_09_02_Time_start.setBorder(null);
        add(lbl_09_02_Time_start);
        lbl_09_02_Time_start.setBounds(90, 60, 60, 25);

        lblAnimation_09_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_09_02);
        lblAnimation_09_02.setBounds(230, 60, 25, 25);

        lbl_09_02_Title.setText("9.2 Выдержка");
        lbl_09_02_Title.setBorder(null);
        lbl_09_02_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_02_TitleMouseClicked(evt);
            }
        });
        add(lbl_09_02_Title);
        lbl_09_02_Title.setBounds(260, 60, 440, 25);

        lbl_09_02_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_02_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_09_02_IcoStep);
        lbl_09_02_IcoStep.setBounds(730, 60, 30, 25);

        chk_09_02_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_09_02_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_09_02_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_09_02_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_09_02_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_09_02_AutoStart);
        chk_09_02_AutoStart.setBounds(700, 60, 30, 30);

        btn_09_02_Next.setText("Далее");
        btn_09_02_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_02_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_02_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_02_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_02_NextActionPerformed(evt);
            }
        });
        add(btn_09_02_Next);
        btn_09_02_Next.setBounds(770, 60, 60, 30);

        lbl_09_02_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_02_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_02_Date_stop.setText("-");
        lbl_09_02_Date_stop.setBorder(null);
        add(lbl_09_02_Date_stop);
        lbl_09_02_Date_stop.setBounds(840, 60, 90, 25);

        lbl_09_02_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_02_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_02_Time_stop.setText("-");
        lbl_09_02_Time_stop.setBorder(null);
        add(lbl_09_02_Time_stop);
        lbl_09_02_Time_stop.setBounds(930, 60, 60, 25);

        lbl_09_03_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_03_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_03_Date_start.setText("-");
        lbl_09_03_Date_start.setBorder(null);
        add(lbl_09_03_Date_start);
        lbl_09_03_Date_start.setBounds(0, 90, 90, 25);

        lbl_09_03_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_03_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_03_Time_start.setText("-");
        lbl_09_03_Time_start.setBorder(null);
        add(lbl_09_03_Time_start);
        lbl_09_03_Time_start.setBounds(90, 90, 60, 25);

        lblAnimation_09_03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_09_03);
        lblAnimation_09_03.setBounds(230, 90, 25, 25);

        lbl_09_03_Title.setText("9.3 Обработка. 1ый цикл");
        lbl_09_03_Title.setBorder(null);
        lbl_09_03_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_03_TitleMouseClicked(evt);
            }
        });
        add(lbl_09_03_Title);
        lbl_09_03_Title.setBounds(260, 90, 440, 25);

        chk_09_03_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_09_03_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_09_03_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_09_03_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_09_03_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_09_03_AutoStart);
        chk_09_03_AutoStart.setBounds(700, 90, 30, 30);

        lbl_09_03_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_03_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_09_03_IcoStep);
        lbl_09_03_IcoStep.setBounds(730, 90, 30, 25);

        btn_09_03_Next.setText("Далее");
        btn_09_03_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_03_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_03_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_03_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_03_NextActionPerformed(evt);
            }
        });
        add(btn_09_03_Next);
        btn_09_03_Next.setBounds(770, 90, 60, 30);

        lbl_09_03_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_03_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_03_Date_stop.setText("-");
        lbl_09_03_Date_stop.setBorder(null);
        add(lbl_09_03_Date_stop);
        lbl_09_03_Date_stop.setBounds(840, 90, 90, 25);

        lbl_09_03_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_03_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_03_Time_stop.setText("-");
        lbl_09_03_Time_stop.setBorder(null);
        add(lbl_09_03_Time_stop);
        lbl_09_03_Time_stop.setBounds(930, 90, 60, 25);

        lbl_09_04_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_04_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_04_Date_start.setText("-");
        lbl_09_04_Date_start.setBorder(null);
        add(lbl_09_04_Date_start);
        lbl_09_04_Date_start.setBounds(0, 120, 90, 25);

        lbl_09_04_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_04_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_04_Time_start.setText("-");
        lbl_09_04_Time_start.setBorder(null);
        add(lbl_09_04_Time_start);
        lbl_09_04_Time_start.setBounds(90, 120, 60, 25);

        lblAnimation_09_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_09_04);
        lblAnimation_09_04.setBounds(230, 120, 25, 25);

        lbl_09_04_Title.setText("9.4 Откачка тренировочной смеси");
        lbl_09_04_Title.setBorder(null);
        lbl_09_04_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_04_TitleMouseClicked(evt);
            }
        });
        add(lbl_09_04_Title);
        lbl_09_04_Title.setBounds(260, 120, 440, 25);

        chk_09_04_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_09_04_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_09_04_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_09_04_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_09_04_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_09_04_AutoStart);
        chk_09_04_AutoStart.setBounds(700, 120, 30, 30);

        lbl_09_04_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_04_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_09_04_IcoStep);
        lbl_09_04_IcoStep.setBounds(730, 120, 30, 25);

        btn_09_04_Next.setText("Далее");
        btn_09_04_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_04_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_04_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_04_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_04_NextActionPerformed(evt);
            }
        });
        add(btn_09_04_Next);
        btn_09_04_Next.setBounds(770, 120, 60, 30);

        lbl_09_04_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_04_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_04_Date_stop.setText("-");
        lbl_09_04_Date_stop.setBorder(null);
        add(lbl_09_04_Date_stop);
        lbl_09_04_Date_stop.setBounds(840, 120, 90, 25);

        lbl_09_04_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_04_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_04_Time_stop.setText("-");
        lbl_09_04_Time_stop.setBorder(null);
        add(lbl_09_04_Time_stop);
        lbl_09_04_Time_stop.setBounds(930, 120, 60, 25);

        lbl_09_05_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_05_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_05_Date_start.setText("-");
        lbl_09_05_Date_start.setBorder(null);
        add(lbl_09_05_Date_start);
        lbl_09_05_Date_start.setBounds(0, 150, 90, 25);

        lbl_09_05_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_05_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_05_Time_start.setText("-");
        lbl_09_05_Time_start.setBorder(null);
        add(lbl_09_05_Time_start);
        lbl_09_05_Time_start.setBounds(90, 150, 60, 25);

        lblAnimation_09_05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_09_05);
        lblAnimation_09_05.setBounds(230, 150, 25, 25);

        lbl_09_05_Title.setText("9.5 Напуск тренировочной смеси в приборы");
        lbl_09_05_Title.setBorder(null);
        lbl_09_05_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_05_TitleMouseClicked(evt);
            }
        });
        add(lbl_09_05_Title);
        lbl_09_05_Title.setBounds(260, 150, 440, 25);

        chk_09_05_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_09_05_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_09_05_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_09_05_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_09_05_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_09_05_AutoStart);
        chk_09_05_AutoStart.setBounds(700, 150, 30, 30);

        lbl_09_05_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_05_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_09_05_IcoStep);
        lbl_09_05_IcoStep.setBounds(730, 150, 30, 25);

        btn_09_05_Next.setText("Далее");
        btn_09_05_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_05_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_05_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_05_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_05_NextActionPerformed(evt);
            }
        });
        add(btn_09_05_Next);
        btn_09_05_Next.setBounds(770, 150, 60, 30);

        lbl_09_05_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_05_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_05_Date_stop.setText("-");
        lbl_09_05_Date_stop.setBorder(null);
        add(lbl_09_05_Date_stop);
        lbl_09_05_Date_stop.setBounds(840, 150, 90, 25);

        lbl_09_05_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_05_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_05_Time_stop.setText("-");
        lbl_09_05_Time_stop.setBorder(null);
        add(lbl_09_05_Time_stop);
        lbl_09_05_Time_stop.setBounds(930, 150, 60, 25);

        lbl_09_06_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_06_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_06_Date_start.setText("-");
        lbl_09_06_Date_start.setBorder(null);
        add(lbl_09_06_Date_start);
        lbl_09_06_Date_start.setBounds(0, 180, 90, 25);

        lbl_09_06_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_06_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_06_Time_start.setText("-");
        lbl_09_06_Time_start.setBorder(null);
        add(lbl_09_06_Time_start);
        lbl_09_06_Time_start.setBounds(90, 180, 60, 25);

        lblAnimation_09_06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_09_06);
        lblAnimation_09_06.setBounds(230, 180, 25, 25);

        lbl_09_06_Title.setText("9.6 Выдержка");
        lbl_09_06_Title.setBorder(null);
        lbl_09_06_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_06_TitleMouseClicked(evt);
            }
        });
        add(lbl_09_06_Title);
        lbl_09_06_Title.setBounds(260, 180, 440, 25);

        chk_09_06_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_09_06_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_09_06_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_09_06_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_09_06_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_09_06_AutoStart);
        chk_09_06_AutoStart.setBounds(700, 180, 30, 30);

        lbl_09_06_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_06_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_09_06_IcoStep);
        lbl_09_06_IcoStep.setBounds(730, 180, 30, 25);

        btn_09_06_Next.setText("Далее");
        btn_09_06_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_06_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_06_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_06_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_06_NextActionPerformed(evt);
            }
        });
        add(btn_09_06_Next);
        btn_09_06_Next.setBounds(770, 180, 60, 30);

        lbl_09_06_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_06_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_06_Date_stop.setText("-");
        lbl_09_06_Date_stop.setBorder(null);
        add(lbl_09_06_Date_stop);
        lbl_09_06_Date_stop.setBounds(840, 180, 90, 25);

        lbl_09_06_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_06_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_06_Time_stop.setText("-");
        lbl_09_06_Time_stop.setBorder(null);
        add(lbl_09_06_Time_stop);
        lbl_09_06_Time_stop.setBounds(930, 180, 60, 25);

        lbl_09_07_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_07_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_07_Date_start.setText("-");
        lbl_09_07_Date_start.setBorder(null);
        add(lbl_09_07_Date_start);
        lbl_09_07_Date_start.setBounds(0, 210, 90, 25);

        lbl_09_07_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_07_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_07_Time_start.setText("-");
        lbl_09_07_Time_start.setBorder(null);
        add(lbl_09_07_Time_start);
        lbl_09_07_Time_start.setBounds(90, 210, 60, 25);

        lblAnimation_09_07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_09_07);
        lblAnimation_09_07.setBounds(230, 210, 25, 25);

        lbl_09_07_Title.setText("9.7 Обработка. 2ой цикл");
        lbl_09_07_Title.setBorder(null);
        lbl_09_07_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_07_TitleMouseClicked(evt);
            }
        });
        add(lbl_09_07_Title);
        lbl_09_07_Title.setBounds(260, 210, 440, 25);

        chk_09_07_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_09_07_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_09_07_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_09_07_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_09_07_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_09_07_AutoStart);
        chk_09_07_AutoStart.setBounds(700, 210, 30, 30);

        lbl_09_07_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_07_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_09_07_IcoStep);
        lbl_09_07_IcoStep.setBounds(730, 210, 30, 25);

        btn_09_07_Next.setText("Далее");
        btn_09_07_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_07_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_07_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_07_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_07_NextActionPerformed(evt);
            }
        });
        add(btn_09_07_Next);
        btn_09_07_Next.setBounds(770, 210, 60, 30);

        lbl_09_07_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_07_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_07_Date_stop.setText("-");
        lbl_09_07_Date_stop.setBorder(null);
        add(lbl_09_07_Date_stop);
        lbl_09_07_Date_stop.setBounds(840, 210, 90, 25);

        lbl_09_07_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_07_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_07_Time_stop.setText("-");
        lbl_09_07_Time_stop.setBorder(null);
        add(lbl_09_07_Time_stop);
        lbl_09_07_Time_stop.setBounds(930, 210, 60, 25);

        lbl_09_08_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_08_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_08_Date_start.setText("-");
        lbl_09_08_Date_start.setBorder(null);
        add(lbl_09_08_Date_start);
        lbl_09_08_Date_start.setBounds(0, 240, 90, 25);

        lbl_09_08_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_08_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_08_Time_start.setText("-");
        lbl_09_08_Time_start.setBorder(null);
        add(lbl_09_08_Time_start);
        lbl_09_08_Time_start.setBounds(90, 240, 60, 25);

        lblAnimation_09_08.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_09_08);
        lblAnimation_09_08.setBounds(230, 240, 25, 25);

        lbl_09_08_Title.setText("9.8 Откачка тренировочной смеси");
        lbl_09_08_Title.setBorder(null);
        lbl_09_08_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_08_TitleMouseClicked(evt);
            }
        });
        add(lbl_09_08_Title);
        lbl_09_08_Title.setBounds(260, 240, 440, 25);

        chk_09_08_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_09_08_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_09_08_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_09_08_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_09_08_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_09_08_AutoStart);
        chk_09_08_AutoStart.setBounds(700, 240, 30, 30);

        lbl_09_08_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_08_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_09_08_IcoStep);
        lbl_09_08_IcoStep.setBounds(730, 240, 30, 25);

        btn_09_08_Next.setText("Далее");
        btn_09_08_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_08_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_08_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_08_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_08_NextActionPerformed(evt);
            }
        });
        add(btn_09_08_Next);
        btn_09_08_Next.setBounds(770, 240, 60, 30);

        lbl_09_08_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_08_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_08_Date_stop.setText("-");
        lbl_09_08_Date_stop.setBorder(null);
        add(lbl_09_08_Date_stop);
        lbl_09_08_Date_stop.setBounds(840, 240, 90, 25);

        lbl_09_08_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_08_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_08_Time_stop.setText("-");
        lbl_09_08_Time_stop.setBorder(null);
        add(lbl_09_08_Time_stop);
        lbl_09_08_Time_stop.setBounds(930, 240, 60, 25);

        lbl_09_09_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_09_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_09_Date_start.setText("-");
        lbl_09_09_Date_start.setBorder(null);
        add(lbl_09_09_Date_start);
        lbl_09_09_Date_start.setBounds(0, 270, 90, 25);

        lbl_09_09_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_09_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_09_Time_start.setText("-");
        lbl_09_09_Time_start.setBorder(null);
        add(lbl_09_09_Time_start);
        lbl_09_09_Time_start.setBounds(90, 270, 60, 25);

        lblAnimation_09_09.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_09_09);
        lblAnimation_09_09.setBounds(230, 270, 25, 25);

        lbl_09_09_Title.setText("9.9 Переход на основную откачку");
        lbl_09_09_Title.setBorder(null);
        lbl_09_09_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_09_09_TitleMouseClicked(evt);
            }
        });
        add(lbl_09_09_Title);
        lbl_09_09_Title.setBounds(260, 270, 440, 25);

        chk_09_09_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_09_09_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_09_09_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_09_09_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_09_09_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_09_09_AutoStart);
        chk_09_09_AutoStart.setBounds(700, 270, 30, 30);

        lbl_09_09_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_09_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_09_09_IcoStep);
        lbl_09_09_IcoStep.setBounds(730, 270, 30, 25);

        btn_09_09_Next.setText("Далее");
        btn_09_09_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_09_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_09_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_09_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_09_NextActionPerformed(evt);
            }
        });
        add(btn_09_09_Next);
        btn_09_09_Next.setBounds(770, 270, 60, 30);

        lbl_09_09_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_09_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_09_Date_stop.setText("-");
        lbl_09_09_Date_stop.setBorder(null);
        add(lbl_09_09_Date_stop);
        lbl_09_09_Date_stop.setBounds(840, 270, 90, 25);

        lbl_09_09_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_09_09_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_09_09_Time_stop.setText("-");
        lbl_09_09_Time_stop.setBorder(null);
        add(lbl_09_09_Time_stop);
        lbl_09_09_Time_stop.setBounds(930, 270, 60, 25);

        btn_09_01_Start.setText("Старт");
        btn_09_01_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_01_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_01_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_01_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_01_StartActionPerformed(evt);
            }
        });
        add(btn_09_01_Start);
        btn_09_01_Start.setBounds(160, 30, 60, 30);

        btn_09_02_Start.setText("Старт");
        btn_09_02_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_02_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_02_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_02_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_02_StartActionPerformed(evt);
            }
        });
        add(btn_09_02_Start);
        btn_09_02_Start.setBounds(160, 60, 60, 30);

        btn_09_03_Start.setText("Старт");
        btn_09_03_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_03_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_03_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_03_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_03_StartActionPerformed(evt);
            }
        });
        add(btn_09_03_Start);
        btn_09_03_Start.setBounds(160, 90, 60, 30);

        btn_09_04_Start.setText("Старт");
        btn_09_04_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_04_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_04_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_04_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_04_StartActionPerformed(evt);
            }
        });
        add(btn_09_04_Start);
        btn_09_04_Start.setBounds(160, 120, 60, 30);

        btn_09_05_Start.setText("Старт");
        btn_09_05_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_05_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_05_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_05_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_05_StartActionPerformed(evt);
            }
        });
        add(btn_09_05_Start);
        btn_09_05_Start.setBounds(160, 150, 60, 30);

        btn_09_06_Start.setText("Старт");
        btn_09_06_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_06_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_06_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_06_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_06_StartActionPerformed(evt);
            }
        });
        add(btn_09_06_Start);
        btn_09_06_Start.setBounds(160, 180, 60, 30);

        btn_09_07_Start.setText("Старт");
        btn_09_07_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_07_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_07_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_07_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_07_StartActionPerformed(evt);
            }
        });
        add(btn_09_07_Start);
        btn_09_07_Start.setBounds(160, 210, 60, 30);

        btn_09_08_Start.setText("Старт");
        btn_09_08_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_08_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_08_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_08_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_08_StartActionPerformed(evt);
            }
        });
        add(btn_09_08_Start);
        btn_09_08_Start.setBounds(160, 240, 60, 30);

        btn_09_09_Start.setText("Старт");
        btn_09_09_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_09_09_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_09_09_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_09_09_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09_09_StartActionPerformed(evt);
            }
        });
        add(btn_09_09_Start);
        btn_09_09_Start.setBounds(160, 270, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_09_00_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_00_TitleMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_09_00_TitleMouseClicked

    private void lbl_09_00_IcoStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_00_IcoStepMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_09_00_IcoStepMouseClicked

    private void btn_09_01_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_01_NextActionPerformed
        DefaultNextButtonProcessing( "161", "Старт напуска тренировочной смеси", "Завершение напуска тренировочной смеси",
                                       "162", "Старт выдержки", chk_09_02_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_01_NextActionPerformed

    private void btn_09_02_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_02_NextActionPerformed
        DefaultNextButtonProcessing( "162", "Старт выдержки", "Завершение выдержки",
                                       "163", "Старт 1-го цикла тренировки", chk_09_03_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_02_NextActionPerformed

    private void btn_09_03_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_03_NextActionPerformed
        DefaultNextButtonProcessing( "163", "Старт 1-го цикла тренировки", "Завершение 1-го цикла тренировки",
                                       "164", "Старт откачки тренировочной смеси", chk_09_04_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_03_NextActionPerformed

    private void btn_09_04_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_04_NextActionPerformed
        DefaultNextButtonProcessing( "164", "Старт откачки тренировочной смеси", "Завершение откачки тренировочной смеси",
                                       "165", "Старт напуска тренировочной смеси", chk_09_05_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_04_NextActionPerformed

    private void btn_09_05_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_05_NextActionPerformed
        DefaultNextButtonProcessing( "165", "Старт напуска тренировочной смеси", "Завершение напуска тренировочной смеси",
                                       "166", "Старт выдержки", chk_09_06_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_05_NextActionPerformed

    private void btn_09_06_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_06_NextActionPerformed
        DefaultNextButtonProcessing( "166", "Старт выдержки", "Завершение выдержки",
                                       "167", "Старт 2-го цикла тренировки", chk_09_07_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_06_NextActionPerformed

    private void btn_09_07_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_07_NextActionPerformed
        DefaultNextButtonProcessing( "167", "Старт 2-го цикла тренировки", "Завершение 2-го цикла тренировки",
                                       "168", "Старт откачки тренировочной смеси", chk_09_08_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_07_NextActionPerformed

    private void btn_09_08_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_08_NextActionPerformed
        DefaultNextButtonProcessing( "168", "Старт откачки тренировочной смеси", "Завершение откачки тренировочной смеси",
                                       "169", "Старт программы перехода на основную откачку", chk_09_09_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_08_NextActionPerformed

    private void btn_09_09_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_09_NextActionPerformed
        if( theApp.IsCurrentStepInProgress() == false)
            return;
        
        //мы в процессе исполнения подэтапа XXX, переходим к следующему подэтапу XXX+1
        if( theApp.IsStepMapContainsKey( "169")) {
            TechProcessStepInfo info = theApp.GetStepInfo( "169");

            info.SetStopDateAsCurrent();
            info.SetStopReportTitle( "Завершение программы перехода на основную откачку");
            info.SetStopP5( theApp.GetDoubleFromPoller( "005.01"));
            info.SetStopP6( theApp.GetDoubleFromPoller( "006.01"));
            info.SetStopP7( theApp.GetDoubleFromPoller( "007.01"));

            theApp.NextCurrentStep();

            info = new TechProcessStepInfo( theApp);
            
            info.SetStartDateAsCurrent();
            info.SetStartReportTitle( "Начало процесса активации");
            info.SetStartP5( theApp.GetDoubleFromPoller( "005.01"));
            info.SetStartP6( theApp.GetDoubleFromPoller( "006.01"));
            info.SetStartP7( theApp.GetDoubleFromPoller( "007.01"));

            theApp.SaveStepInfo( "181", info, true);

            //обновляем экран и отчёт, и только потом закроем экран диалогами обезгаживания
            theApp.m_pMainWnd.m_pPanel.SetStates();
            theApp.m_ReportGenerator.Generate();
            theApp.m_pMainWnd.m_pPanel.Reposition();

            theApp.SetCurrentStepInProgress( true);

            new Timer( 100, new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    Timer timer = ( Timer) e.getSource();
                    timer.stop();
                    theApp.ShowDlg10( 10);
                }
            }).start();

        }
        else {
            logger.fatal( "Мы заканчиваем этап 169, а инфы на него до сих пор нет!");
        }
    }//GEN-LAST:event_btn_09_09_NextActionPerformed

    private void btn_09_01_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_01_StartActionPerformed
        DefaultStartButtonProcessing( "161", "Старт напуска тренировочной смеси", "Завершение напуска тренировочной смеси",
                                       "162", "Старт выдержки", chk_09_02_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_01_StartActionPerformed

    private void btn_09_02_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_02_StartActionPerformed
        DefaultStartButtonProcessing( "162", "Старт выдержки", "Завершение выдержки",
                                       "163", "Старт 1-го цикла тренировки", chk_09_03_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_02_StartActionPerformed

    private void btn_09_03_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_03_StartActionPerformed
        DefaultStartButtonProcessing( "163", "Старт 1-го цикла тренировки", "Завершение 1-го цикла тренировки",
                                       "164", "Старт откачки тренировочной смеси", chk_09_04_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_03_StartActionPerformed
    
    private void btn_09_04_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_04_StartActionPerformed
        DefaultStartButtonProcessing( "164", "Старт откачки тренировочной смеси", "Завершение откачки тренировочной смеси",
                                       "165", "Старт напуска тренировочной смеси", chk_09_05_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_04_StartActionPerformed

    private void btn_09_05_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_05_StartActionPerformed
        DefaultStartButtonProcessing( "165", "Старт напуска тренировочной смеси", "Завершение напуска тренировочной смеси",
                                       "166", "Старт выдержки", chk_09_06_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_05_StartActionPerformed

    private void btn_09_06_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_06_StartActionPerformed
        DefaultStartButtonProcessing( "166", "Старт выдержки", "Завершение выдержки",
                                       "167", "Старт 2-го цикла тренировки", chk_09_07_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_06_StartActionPerformed

    private void btn_09_07_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_07_StartActionPerformed
        DefaultStartButtonProcessing( "167", "Старт 2-го цикла тренировки", "Завершение 2-го цикла тренировки",
                                       "168", "Старт откачки тренировочной смеси", chk_09_08_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_07_StartActionPerformed

    private void btn_09_08_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_08_StartActionPerformed
        DefaultStartButtonProcessing( "168", "Старт откачки тренировочной смеси", "Завершение откачки тренировочной смеси",
                                       "169", "Старт программы перехода на основную откачку", chk_09_09_AutoStart, logger, false);
    }//GEN-LAST:event_btn_09_08_StartActionPerformed

    private void btn_09_09_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_09_09_StartActionPerformed
        /*
        //мы начинаем процесс
        TechProcessStepInfo info = new TechProcessStepInfo( theApp);
        
        info.SetStartDateAsCurrent();
        info.SetStartReportTitle( "Старт программы перехода на основную откачку");
        info.SetStartP5( theApp.GetFromPoller( "005.01"));
        info.SetStartP6( theApp.GetFromPoller( "006.01"));
        info.SetStartP7( theApp.GetFromPoller( "007.01"));

        theApp.SaveStepInfo( "169", info);

        theApp.m_ReportGenerator.Generate();

        theApp.SetCurrentStepInProgress( true);

        //StartProgramExecutor executor = new StartProgramExecutor( theApp, "AdminStep_" + theApp.HumanNameForStep( "133") + ".xml");
        StartProgramExecutor executor = new StartProgramExecutor( theApp, "AdminStep_9.9.xml");
        executor.StartThread();

        SetState();
        */
        DefaultStartButtonProcessing( "169", "Старт программы перехода на основную откачку", "Завершение программы перехода на основную откачку",
                                      "180", "Старт активации", null, logger, false);
    }//GEN-LAST:event_btn_09_09_StartActionPerformed

    private void lbl_09_00_Date_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_00_Date_startMouseClicked
        ProcessHeaderDateTimeClick( 9);
    }//GEN-LAST:event_lbl_09_00_Date_startMouseClicked

    private void lbl_09_00_Time_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_00_Time_startMouseClicked
        ProcessHeaderDateTimeClick( 9);
    }//GEN-LAST:event_lbl_09_00_Time_startMouseClicked

    private void lbl_09_01_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_01_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 161);
        }
    }//GEN-LAST:event_lbl_09_01_TitleMouseClicked

    private void lbl_09_02_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_02_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 162);
        }
    }//GEN-LAST:event_lbl_09_02_TitleMouseClicked

    private void lbl_09_03_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_03_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 163);
        }
    }//GEN-LAST:event_lbl_09_03_TitleMouseClicked

    private void lbl_09_04_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_04_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 164);
        }
    }//GEN-LAST:event_lbl_09_04_TitleMouseClicked

    private void lbl_09_05_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_05_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 165);
        }
    }//GEN-LAST:event_lbl_09_05_TitleMouseClicked

    private void lbl_09_06_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_06_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 166);
        }
    }//GEN-LAST:event_lbl_09_06_TitleMouseClicked

    private void lbl_09_07_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_07_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 167);
        }
    }//GEN-LAST:event_lbl_09_07_TitleMouseClicked

    private void lbl_09_08_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_08_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 168);
        }
    }//GEN-LAST:event_lbl_09_08_TitleMouseClicked

    private void lbl_09_09_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_09_09_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 169);
        }
    }//GEN-LAST:event_lbl_09_09_TitleMouseClicked

    public void SetState() {
        if( theApp.GetCurrentStep() / 20 == m_nPageNumber)
            m_bCollapsed = false;
        
        //9. Тренировка в тренировочной смеси

        FillHeaderStepDates( "161", lbl_09_00_Date_start, lbl_09_00_Time_start, "169", lbl_09_00_Date_stop, lbl_09_00_Time_stop);
        
        lbl_09_00_IcoStep.setIcon( m_bCollapsed ? theApp.GetResources().getIconTriaRight() : theApp.GetResources().getIconTriaDown());
        
        lbl_09_00_Title.setFont( theApp.GetCurrentStep() / 20 == m_nPageNumber ? theApp.GetBoldFont() : theApp.GetUsualFont());
        lbl_09_00_Title.setEnabled( theApp.GetCurrentStep() / 20 <= m_nPageNumber);
        
        
        if( m_bCollapsed == false) {
            //9.1 Напуск тренировочной смеси в приборы
            FillAutoExecutedSubStep( 161,
                                    lbl_09_01_Date_start, lbl_09_01_Time_start, lblAnimation_09_01,
                                    btn_09_01_Start, lbl_09_01_Title, chk_09_01_AutoStart, lbl_09_01_IcoStep, btn_09_01_Next,
                                    lbl_09_01_Date_stop, lbl_09_01_Time_stop);
            
            //9.2 Выдержка
            FillAutoExecutedSubStep(162,
                                    lbl_09_02_Date_start, lbl_09_02_Time_start, lblAnimation_09_02,
                                    btn_09_02_Start, lbl_09_02_Title, chk_09_02_AutoStart, lbl_09_02_IcoStep, btn_09_02_Next,
                                    lbl_09_02_Date_stop, lbl_09_02_Time_stop);
            
            //9.3 Обработка. 1ый цикл.
            FillAutoExecutedSubStep(163,
                                    lbl_09_03_Date_start, lbl_09_03_Time_start, lblAnimation_09_03,
                                    btn_09_03_Start, lbl_09_03_Title, chk_09_03_AutoStart, lbl_09_03_IcoStep, btn_09_03_Next,
                                    lbl_09_03_Date_stop, lbl_09_03_Time_stop);
            
            //9.4 Откачка тренировочной смеси
            FillAutoExecutedSubStep(164,
                                    lbl_09_04_Date_start, lbl_09_04_Time_start, lblAnimation_09_04,
                                    btn_09_04_Start, lbl_09_04_Title, chk_09_04_AutoStart, lbl_09_04_IcoStep, btn_09_04_Next,
                                    lbl_09_04_Date_stop, lbl_09_04_Time_stop);
            
            //9.5 Напуск тренировочной смеси в приборы
            FillAutoExecutedSubStep(165,
                                    lbl_09_05_Date_start, lbl_09_05_Time_start, lblAnimation_09_05,
                                    btn_09_05_Start, lbl_09_05_Title, chk_09_05_AutoStart, lbl_09_05_IcoStep, btn_09_05_Next,
                                    lbl_09_05_Date_stop, lbl_09_05_Time_stop);
            
            //9.6 Выдержка
            FillAutoExecutedSubStep(166,
                                    lbl_09_06_Date_start, lbl_09_06_Time_start, lblAnimation_09_06,
                                    btn_09_06_Start, lbl_09_06_Title, chk_09_06_AutoStart, lbl_09_06_IcoStep, btn_09_06_Next,
                                    lbl_09_06_Date_stop, lbl_09_06_Time_stop);
            
            //9.7 Обработка. 2ой цикл.
            FillAutoExecutedSubStep(167,
                                    lbl_09_07_Date_start, lbl_09_07_Time_start, lblAnimation_09_07,
                                    btn_09_07_Start, lbl_09_07_Title, chk_09_07_AutoStart, lbl_09_07_IcoStep, btn_09_07_Next,
                                    lbl_09_07_Date_stop, lbl_09_07_Time_stop);
            
            //9.8 Откачка тренировочной смеси
            FillAutoExecutedSubStep(168,
                                    lbl_09_08_Date_start, lbl_09_08_Time_start, lblAnimation_09_08,
                                    btn_09_08_Start, lbl_09_08_Title, chk_09_08_AutoStart, lbl_09_08_IcoStep, btn_09_08_Next,
                                    lbl_09_08_Date_stop, lbl_09_08_Time_stop);
            chk_09_08_AutoStart.setEnabled( false);
            
            //9.9 Переход на основную откачку
            FillAutoExecutedSubStep(169,
                                    lbl_09_09_Date_start, lbl_09_09_Time_start, lblAnimation_09_09,
                                    btn_09_09_Start, lbl_09_09_Title, chk_09_09_AutoStart, lbl_09_09_IcoStep, btn_09_09_Next,
                                    lbl_09_09_Date_stop, lbl_09_09_Time_stop);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_09_01_Next;
    public javax.swing.JButton btn_09_01_Start;
    private javax.swing.JButton btn_09_02_Next;
    public javax.swing.JButton btn_09_02_Start;
    private javax.swing.JButton btn_09_03_Next;
    public javax.swing.JButton btn_09_03_Start;
    private javax.swing.JButton btn_09_04_Next;
    public javax.swing.JButton btn_09_04_Start;
    private javax.swing.JButton btn_09_05_Next;
    public javax.swing.JButton btn_09_05_Start;
    private javax.swing.JButton btn_09_06_Next;
    public javax.swing.JButton btn_09_06_Start;
    private javax.swing.JButton btn_09_07_Next;
    public javax.swing.JButton btn_09_07_Start;
    private javax.swing.JButton btn_09_08_Next;
    public javax.swing.JButton btn_09_08_Start;
    private javax.swing.JButton btn_09_09_Next;
    public javax.swing.JButton btn_09_09_Start;
    public javax.swing.JCheckBox chk_09_01_AutoStart;
    public javax.swing.JCheckBox chk_09_02_AutoStart;
    public javax.swing.JCheckBox chk_09_03_AutoStart;
    public javax.swing.JCheckBox chk_09_04_AutoStart;
    public javax.swing.JCheckBox chk_09_05_AutoStart;
    public javax.swing.JCheckBox chk_09_06_AutoStart;
    public javax.swing.JCheckBox chk_09_07_AutoStart;
    public javax.swing.JCheckBox chk_09_08_AutoStart;
    public javax.swing.JCheckBox chk_09_09_AutoStart;
    public javax.swing.JLabel lblAnimation_09_01;
    public javax.swing.JLabel lblAnimation_09_02;
    public javax.swing.JLabel lblAnimation_09_03;
    public javax.swing.JLabel lblAnimation_09_04;
    public javax.swing.JLabel lblAnimation_09_05;
    public javax.swing.JLabel lblAnimation_09_06;
    public javax.swing.JLabel lblAnimation_09_07;
    public javax.swing.JLabel lblAnimation_09_08;
    public javax.swing.JLabel lblAnimation_09_09;
    public javax.swing.JLabel lbl_09_00_Date_start;
    private javax.swing.JLabel lbl_09_00_Date_stop;
    private javax.swing.JLabel lbl_09_00_IcoStep;
    public javax.swing.JLabel lbl_09_00_Time_start;
    private javax.swing.JLabel lbl_09_00_Time_stop;
    private javax.swing.JLabel lbl_09_00_Title;
    private javax.swing.JLabel lbl_09_01_Date_start;
    private javax.swing.JLabel lbl_09_01_Date_stop;
    public javax.swing.JLabel lbl_09_01_IcoStep;
    private javax.swing.JLabel lbl_09_01_Time_start;
    private javax.swing.JLabel lbl_09_01_Time_stop;
    private javax.swing.JLabel lbl_09_01_Title;
    private javax.swing.JLabel lbl_09_02_Date_start;
    private javax.swing.JLabel lbl_09_02_Date_stop;
    public javax.swing.JLabel lbl_09_02_IcoStep;
    private javax.swing.JLabel lbl_09_02_Time_start;
    private javax.swing.JLabel lbl_09_02_Time_stop;
    private javax.swing.JLabel lbl_09_02_Title;
    private javax.swing.JLabel lbl_09_03_Date_start;
    private javax.swing.JLabel lbl_09_03_Date_stop;
    public javax.swing.JLabel lbl_09_03_IcoStep;
    private javax.swing.JLabel lbl_09_03_Time_start;
    private javax.swing.JLabel lbl_09_03_Time_stop;
    private javax.swing.JLabel lbl_09_03_Title;
    private javax.swing.JLabel lbl_09_04_Date_start;
    private javax.swing.JLabel lbl_09_04_Date_stop;
    public javax.swing.JLabel lbl_09_04_IcoStep;
    private javax.swing.JLabel lbl_09_04_Time_start;
    private javax.swing.JLabel lbl_09_04_Time_stop;
    private javax.swing.JLabel lbl_09_04_Title;
    private javax.swing.JLabel lbl_09_05_Date_start;
    private javax.swing.JLabel lbl_09_05_Date_stop;
    public javax.swing.JLabel lbl_09_05_IcoStep;
    private javax.swing.JLabel lbl_09_05_Time_start;
    private javax.swing.JLabel lbl_09_05_Time_stop;
    private javax.swing.JLabel lbl_09_05_Title;
    private javax.swing.JLabel lbl_09_06_Date_start;
    private javax.swing.JLabel lbl_09_06_Date_stop;
    public javax.swing.JLabel lbl_09_06_IcoStep;
    private javax.swing.JLabel lbl_09_06_Time_start;
    private javax.swing.JLabel lbl_09_06_Time_stop;
    private javax.swing.JLabel lbl_09_06_Title;
    private javax.swing.JLabel lbl_09_07_Date_start;
    private javax.swing.JLabel lbl_09_07_Date_stop;
    public javax.swing.JLabel lbl_09_07_IcoStep;
    private javax.swing.JLabel lbl_09_07_Time_start;
    private javax.swing.JLabel lbl_09_07_Time_stop;
    private javax.swing.JLabel lbl_09_07_Title;
    private javax.swing.JLabel lbl_09_08_Date_start;
    private javax.swing.JLabel lbl_09_08_Date_stop;
    public javax.swing.JLabel lbl_09_08_IcoStep;
    private javax.swing.JLabel lbl_09_08_Time_start;
    private javax.swing.JLabel lbl_09_08_Time_stop;
    private javax.swing.JLabel lbl_09_08_Title;
    private javax.swing.JLabel lbl_09_09_Date_start;
    private javax.swing.JLabel lbl_09_09_Date_stop;
    public javax.swing.JLabel lbl_09_09_IcoStep;
    private javax.swing.JLabel lbl_09_09_Time_start;
    private javax.swing.JLabel lbl_09_09_Time_stop;
    private javax.swing.JLabel lbl_09_09_Title;
    // End of variables declaration//GEN-END:variables
}
