/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin.dialogs.step10;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author yaroslav
 */
public class TechProcessStep10_1_Dlg_A_StepsPanelFake extends javax.swing.JPanel {

    private final int m_nDevice;
    private final TechProcessStep10_1_Dlg_A m_pParent;
    
    /**
     * Creates new form TechProcessStep10_1_Dlg_A_StepsPanelFake
     */
    public TechProcessStep10_1_Dlg_A_StepsPanelFake( TechProcessStep10_1_Dlg_A pParent, int nDevice) {
        m_pParent = pParent;
        initComponents();
        m_nDevice = nDevice;
        
        
        new Timer( 1000, new ActionListener() {

            int nCounter = 0;
            
            @Override
            public void actionPerformed(ActionEvent e) {
                JLabel lbl = null;
                
                switch( nCounter) {
                    case 0: lbl = jLabel1; break;
                    case 1: lbl = jLabel2; break;
                    case 2: lbl = jLabel3; break;
                    case 3: lbl = jLabel4; break;
                    case 4: lbl = jLabel5; break;
                    case 5: lbl = jLabel6; break;
                    case 6: lbl = jLabel7; break;
                    case 7: lbl = jLabel8; break;
                    case 8: lbl = jLabel9; break;
                    case 9: lbl = jLabel10; break;
                        
                    case 10: lbl = jLabel11; break;
                    case 11: lbl = jLabel12; break;
                    case 12: lbl = jLabel13; break;
                    case 13: lbl = jLabel14; break;
                    case 14: lbl = jLabel15; break;
                    case 15: lbl = jLabel16; break;
                    case 16: lbl = jLabel17; break;
                    case 17: lbl = jLabel18; break;
                    case 18: lbl = jLabel19; break;
                    case 19: lbl = jLabel20; break;
                        
                    case 20: lbl = jLabel21; break;
                    case 21: lbl = jLabel22; break;
                    case 22: lbl = jLabel23; break;
                    case 23: lbl = jLabel24; break;
                    case 24: lbl = jLabel25; break;
                }
                
                
                if( lbl != null) {
                    if( ( nCounter % 2) == 1)
                        lbl.setBackground( new Color( 0, 100, 0));
                    else
                        lbl.setBackground( null);

                    if( ( nCounter % 5) == 0) {
                        String str = lbl.getText();
                        str += " " + nCounter;
                        lbl.setText( str);
                    }
                    
                    nCounter = ( ++nCounter) % 25;
                }
            }
        }).start();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 990));
        setMinimumSize(new java.awt.Dimension(400, 990));
        setPreferredSize(new java.awt.Dimension(400, 990));
        setLayout(null);

        jLabel1.setBackground(new java.awt.Color(223, 205, 187));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel1.setOpaque(true);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 30);

        jLabel2.setBackground(new java.awt.Color(223, 205, 187));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel2.setOpaque(true);
        add(jLabel2);
        jLabel2.setBounds(0, 40, 400, 30);

        jLabel3.setBackground(new java.awt.Color(223, 205, 187));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel3.setOpaque(true);
        add(jLabel3);
        jLabel3.setBounds(0, 80, 400, 30);

        jLabel4.setBackground(new java.awt.Color(223, 205, 187));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel4.setOpaque(true);
        add(jLabel4);
        jLabel4.setBounds(0, 120, 400, 30);

        jLabel5.setBackground(new java.awt.Color(223, 205, 187));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel5.setOpaque(true);
        add(jLabel5);
        jLabel5.setBounds(0, 160, 400, 30);

        jLabel6.setBackground(new java.awt.Color(223, 205, 187));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel6.setOpaque(true);
        add(jLabel6);
        jLabel6.setBounds(0, 200, 400, 30);

        jLabel7.setBackground(new java.awt.Color(223, 205, 187));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel7.setOpaque(true);
        add(jLabel7);
        jLabel7.setBounds(0, 240, 400, 30);

        jLabel8.setBackground(new java.awt.Color(223, 205, 187));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel8.setOpaque(true);
        add(jLabel8);
        jLabel8.setBounds(0, 280, 400, 30);

        jLabel9.setBackground(new java.awt.Color(223, 205, 187));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel9.setOpaque(true);
        add(jLabel9);
        jLabel9.setBounds(0, 320, 400, 30);

        jLabel10.setBackground(new java.awt.Color(223, 205, 187));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel10.setOpaque(true);
        add(jLabel10);
        jLabel10.setBounds(0, 360, 400, 30);

        jLabel11.setBackground(new java.awt.Color(223, 205, 187));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel11.setOpaque(true);
        add(jLabel11);
        jLabel11.setBounds(0, 400, 400, 30);

        jLabel12.setBackground(new java.awt.Color(223, 205, 187));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel12.setOpaque(true);
        add(jLabel12);
        jLabel12.setBounds(0, 440, 400, 30);

        jLabel13.setBackground(new java.awt.Color(223, 205, 187));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel13.setOpaque(true);
        add(jLabel13);
        jLabel13.setBounds(0, 480, 400, 30);

        jLabel14.setBackground(new java.awt.Color(223, 205, 187));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel14.setOpaque(true);
        add(jLabel14);
        jLabel14.setBounds(0, 520, 400, 30);

        jLabel15.setBackground(new java.awt.Color(223, 205, 187));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel15.setOpaque(true);
        add(jLabel15);
        jLabel15.setBounds(0, 560, 400, 30);

        jLabel16.setBackground(new java.awt.Color(223, 205, 187));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel16.setOpaque(true);
        add(jLabel16);
        jLabel16.setBounds(0, 600, 400, 30);

        jLabel17.setBackground(new java.awt.Color(223, 205, 187));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel17.setOpaque(true);
        add(jLabel17);
        jLabel17.setBounds(0, 640, 400, 30);

        jLabel18.setBackground(new java.awt.Color(223, 205, 187));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel18.setOpaque(true);
        add(jLabel18);
        jLabel18.setBounds(0, 680, 400, 30);

        jLabel19.setBackground(new java.awt.Color(223, 205, 187));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel19.setOpaque(true);
        add(jLabel19);
        jLabel19.setBounds(0, 720, 400, 30);

        jLabel20.setBackground(new java.awt.Color(223, 205, 187));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel20.setOpaque(true);
        add(jLabel20);
        jLabel20.setBounds(0, 760, 400, 30);

        jLabel21.setBackground(new java.awt.Color(223, 205, 187));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel21.setOpaque(true);
        add(jLabel21);
        jLabel21.setBounds(0, 800, 400, 30);

        jLabel22.setBackground(new java.awt.Color(223, 205, 187));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel22.setOpaque(true);
        add(jLabel22);
        jLabel22.setBounds(0, 840, 400, 30);

        jLabel23.setBackground(new java.awt.Color(223, 205, 187));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel23.setOpaque(true);
        add(jLabel23);
        jLabel23.setBounds(0, 880, 400, 30);

        jLabel24.setBackground(new java.awt.Color(223, 205, 187));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel24.setOpaque(true);
        add(jLabel24);
        jLabel24.setBounds(0, 920, 400, 30);

        jLabel25.setBackground(new java.awt.Color(223, 205, 187));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jLabel25.setOpaque(true);
        add(jLabel25);
        jLabel25.setBounds(0, 960, 400, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
