/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin.dialogs.step10;

import hvv_admin.HVV_Admin;
import hvv_admin.HVV_AdminConstants;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class TechProcessStep10_1_Dlg_M_HalfPanel extends javax.swing.JPanel {

    static Logger logger = Logger.getLogger(TechProcessStep10_1_Dlg_M_HalfPanel.class);
    final private HVV_Admin theApp;
    
    int m_nBase;
    TechProcessStep10_1_Dlg_M_StepsPanel pnlDev1;
    TechProcessStep10_1_Dlg_M_StepsPanel pnlDev2;
    TechProcessStep10_1_Dlg_M_StepsPanel pnlDev3;
    TechProcessStep10_1_Dlg_M_StepsPanel pnlDev4;
    
    public int m_nIntegralHeight;
    
    /**
     * Creates new form TechProcessStep08_2_Dlg_3_Panel2
     */
    public TechProcessStep10_1_Dlg_M_HalfPanel( HVV_Admin app, int nBase) {
        theApp = app;
        initComponents();
        
        m_nBase = nBase;
        
        m_nIntegralHeight = 1000;
        
        pnlDev1 = new TechProcessStep10_1_Dlg_M_StepsPanel( app, m_nBase);
        pnlDev1.setVisible( true);
        pnlDev1.setBounds( 0, 0, 930, m_nIntegralHeight);
        jPanel1.add( pnlDev1);
        
        pnlDev2 = new TechProcessStep10_1_Dlg_M_StepsPanel( app, m_nBase + 1);
        pnlDev2.setVisible( true);
        pnlDev2.setBounds( 0, 0, 930, m_nIntegralHeight);
        jPanel2.add( pnlDev2);
        
        pnlDev3 = new TechProcessStep10_1_Dlg_M_StepsPanel( app, m_nBase + 2);
        pnlDev3.setVisible( true);
        pnlDev3.setBounds( 0, 0, 930, m_nIntegralHeight);
        jPanel3.add( pnlDev3);
        
        pnlDev4 = new TechProcessStep10_1_Dlg_M_StepsPanel( app, m_nBase + 3);
        pnlDev4.setVisible( true);
        pnlDev4.setBounds( 0, 0, 930, m_nIntegralHeight);
        jPanel4.add( pnlDev4);
    }

    public void RefreshData() {
        pnlDev1.RefreshData();
        pnlDev2.RefreshData();
        pnlDev3.RefreshData();
        pnlDev4.RefreshData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(975, 1000));
        setMinimumSize(new java.awt.Dimension(975, 1000));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(975, 1000));
        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));
        jPanel1.setMaximumSize(new java.awt.Dimension(240, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(240, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 1000));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 240, 1000);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));
        jPanel2.setMaximumSize(new java.awt.Dimension(240, 1000));
        jPanel2.setMinimumSize(new java.awt.Dimension(240, 1000));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );

        add(jPanel2);
        jPanel2.setBounds(245, 0, 240, 1000);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));
        jPanel3.setMaximumSize(new java.awt.Dimension(240, 1000));
        jPanel3.setMinimumSize(new java.awt.Dimension(240, 1000));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );

        add(jPanel3);
        jPanel3.setBounds(490, 0, 240, 1000);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));
        jPanel4.setMaximumSize(new java.awt.Dimension(240, 1000));
        jPanel4.setMinimumSize(new java.awt.Dimension(240, 1000));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );

        add(jPanel4);
        jPanel4.setBounds(735, 0, 240, 1000);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
