/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin.dialogs.step04;

import hvv_admin.HVV_Admin;
import hvv_admin.comm.executor.to.StartProgramExecutor;
import hvv_admin.steps.info.TechProcessStepInfo;
import hvv_admin.dialogs.TechProcessStepPanelTemplate;
import java.awt.event.MouseEvent;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class TechProcessStep04Panel extends TechProcessStepPanelTemplate {
    public final int MAXIMIZED_HEIGHT = 240;
    static Logger logger = Logger.getLogger(TechProcessStep04Panel.class);
    
    /**
     * Creates new form TechProcessStep1Panel
     */
    public TechProcessStep04Panel( HVV_Admin app, boolean bCollapsed) {
        initComponents();
        theApp = app;
        m_bCollapsed = bCollapsed;
        m_nPageNumber = 3;
        m_bFirstOfDoubleClickHeaderDateTime = false;
        
        String strTitle = theApp.GetStepName( 60);
        if( strTitle != null) lbl_04_00_Title.setText( "4. " + strTitle);
        strTitle = theApp.GetStepName( 61);
        if( strTitle != null) lbl_04_01_Title.setText( "4.1 " + strTitle);
        strTitle = theApp.GetStepName( 62);
        if( strTitle != null) lbl_04_02_Title.setText( "4.2 " + strTitle);
        strTitle = theApp.GetStepName( 63);
        if( strTitle != null) lbl_04_03_Title.setText( "4.3 " + strTitle);
        strTitle = theApp.GetStepName( 64);
        if( strTitle != null) lbl_04_04_Title.setText( "4.4 " + strTitle);
        strTitle = theApp.GetStepName( 65);
        if( strTitle != null) lbl_04_05_Title.setText( "4.5 " + strTitle);
        strTitle = theApp.GetStepName( 66);
        if( strTitle != null) lbl_04_06_Title.setText( "4.6 " + strTitle);
        strTitle = theApp.GetStepName( 67);
        if( strTitle != null) lbl_04_07_Title.setText( "4.7 " + strTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_04_00_Date_start = new javax.swing.JLabel();
        lbl_04_00_Time_start = new javax.swing.JLabel();
        lbl_04_00_IcoStep = new javax.swing.JLabel();
        lbl_04_00_Title = new javax.swing.JLabel();
        lbl_04_00_Date_stop = new javax.swing.JLabel();
        lbl_04_00_Time_stop = new javax.swing.JLabel();
        lbl_04_01_Date_start = new javax.swing.JLabel();
        lbl_04_01_Time_start = new javax.swing.JLabel();
        lblAnimation_04_01 = new javax.swing.JLabel();
        lbl_04_01_Title = new javax.swing.JLabel();
        chk_04_01_AutoStart = new javax.swing.JCheckBox();
        lbl_04_01_IcoStep = new javax.swing.JLabel();
        btn_04_01_Next = new javax.swing.JButton();
        lbl_04_01_Date_stop = new javax.swing.JLabel();
        lbl_04_01_Time_stop = new javax.swing.JLabel();
        lbl_04_02_Date_start = new javax.swing.JLabel();
        lbl_04_02_Time_start = new javax.swing.JLabel();
        lblAnimation_04_02 = new javax.swing.JLabel();
        lbl_04_02_Title = new javax.swing.JLabel();
        chk_04_02_AutoStart = new javax.swing.JCheckBox();
        lbl_04_02_IcoStep = new javax.swing.JLabel();
        btn_04_02_Next = new javax.swing.JButton();
        lbl_04_02_Date_stop = new javax.swing.JLabel();
        lbl_04_02_Time_stop = new javax.swing.JLabel();
        lbl_04_03_Date_start = new javax.swing.JLabel();
        lbl_04_03_Time_start = new javax.swing.JLabel();
        lblAnimation_04_03 = new javax.swing.JLabel();
        lbl_04_03_Title = new javax.swing.JLabel();
        chk_04_03_AutoStart = new javax.swing.JCheckBox();
        lbl_04_03_IcoStep = new javax.swing.JLabel();
        btn_04_03_Next = new javax.swing.JButton();
        lbl_04_03_Date_stop = new javax.swing.JLabel();
        lbl_04_03_Time_stop = new javax.swing.JLabel();
        lbl_04_04_Date_start = new javax.swing.JLabel();
        lbl_04_04_Time_start = new javax.swing.JLabel();
        lblAnimation_04_04 = new javax.swing.JLabel();
        lbl_04_04_Title = new javax.swing.JLabel();
        chk_04_04_AutoStart = new javax.swing.JCheckBox();
        lbl_04_04_IcoStep = new javax.swing.JLabel();
        btn_04_04_Next = new javax.swing.JButton();
        lbl_04_04_Date_stop = new javax.swing.JLabel();
        lbl_04_04_Time_stop = new javax.swing.JLabel();
        lbl_04_05_Date_start = new javax.swing.JLabel();
        lbl_04_05_Time_start = new javax.swing.JLabel();
        lblAnimation_04_05 = new javax.swing.JLabel();
        lbl_04_05_Title = new javax.swing.JLabel();
        chk_04_05_AutoStart = new javax.swing.JCheckBox();
        lbl_04_05_IcoStep = new javax.swing.JLabel();
        btn_04_05_Next = new javax.swing.JButton();
        lbl_04_05_Date_stop = new javax.swing.JLabel();
        lbl_04_05_Time_stop = new javax.swing.JLabel();
        lbl_04_06_Date_start = new javax.swing.JLabel();
        lbl_04_06_Time_start = new javax.swing.JLabel();
        lblAnimation_04_06 = new javax.swing.JLabel();
        lbl_04_06_Title = new javax.swing.JLabel();
        chk_04_06_AutoStart = new javax.swing.JCheckBox();
        lbl_04_06_IcoStep = new javax.swing.JLabel();
        btn_04_06_Next = new javax.swing.JButton();
        lbl_04_06_Date_stop = new javax.swing.JLabel();
        lbl_04_06_Time_stop = new javax.swing.JLabel();
        lbl_04_07_Date_start = new javax.swing.JLabel();
        lbl_04_07_Time_start = new javax.swing.JLabel();
        lblAnimation_04_07 = new javax.swing.JLabel();
        lbl_04_07_Title = new javax.swing.JLabel();
        chk_04_07_AutoStart = new javax.swing.JCheckBox();
        lbl_04_07_IcoStep = new javax.swing.JLabel();
        btn_04_07_Next = new javax.swing.JButton();
        lbl_04_07_Date_stop = new javax.swing.JLabel();
        lbl_04_07_Time_stop = new javax.swing.JLabel();
        btn_04_01_Start = new javax.swing.JButton();
        btn_04_02_Start = new javax.swing.JButton();
        btn_04_03_Start = new javax.swing.JButton();
        btn_04_04_Start = new javax.swing.JButton();
        btn_04_05_Start = new javax.swing.JButton();
        btn_04_06_Start = new javax.swing.JButton();
        btn_04_07_Start = new javax.swing.JButton();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1000, 240));
        setMinimumSize(new java.awt.Dimension(1000, 30));
        setName(""); // NOI18N
        setLayout(null);

        lbl_04_00_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_00_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_00_Date_start.setText("-");
        lbl_04_00_Date_start.setBorder(null);
        lbl_04_00_Date_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04_00_Date_startMouseClicked(evt);
            }
        });
        add(lbl_04_00_Date_start);
        lbl_04_00_Date_start.setBounds(0, 0, 90, 25);

        lbl_04_00_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_00_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_00_Time_start.setText("-");
        lbl_04_00_Time_start.setBorder(null);
        lbl_04_00_Time_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04_00_Time_startMouseClicked(evt);
            }
        });
        add(lbl_04_00_Time_start);
        lbl_04_00_Time_start.setBounds(90, 0, 60, 25);

        lbl_04_00_IcoStep.setBorder(null);
        lbl_04_00_IcoStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04_00_IcoStepMouseClicked(evt);
            }
        });
        add(lbl_04_00_IcoStep);
        lbl_04_00_IcoStep.setBounds(150, 0, 30, 25);

        lbl_04_00_Title.setText("4. Обработка в среде кислород-неона");
        lbl_04_00_Title.setBorder(null);
        lbl_04_00_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04_00_TitleMouseClicked(evt);
            }
        });
        add(lbl_04_00_Title);
        lbl_04_00_Title.setBounds(180, 0, 470, 25);

        lbl_04_00_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_00_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_00_Date_stop.setText("-");
        lbl_04_00_Date_stop.setBorder(null);
        add(lbl_04_00_Date_stop);
        lbl_04_00_Date_stop.setBounds(840, 0, 90, 25);

        lbl_04_00_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_00_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_00_Time_stop.setText("-");
        lbl_04_00_Time_stop.setBorder(null);
        add(lbl_04_00_Time_stop);
        lbl_04_00_Time_stop.setBounds(930, 0, 60, 25);

        lbl_04_01_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_01_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_01_Date_start.setText("-");
        lbl_04_01_Date_start.setBorder(null);
        add(lbl_04_01_Date_start);
        lbl_04_01_Date_start.setBounds(0, 30, 90, 25);

        lbl_04_01_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_01_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_01_Time_start.setText("-");
        lbl_04_01_Time_start.setBorder(null);
        add(lbl_04_01_Time_start);
        lbl_04_01_Time_start.setBounds(90, 30, 60, 25);

        lblAnimation_04_01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_04_01);
        lblAnimation_04_01.setBounds(230, 30, 25, 25);

        lbl_04_01_Title.setText("4.1 Напуск кислород-неона в приборы");
        lbl_04_01_Title.setBorder(null);
        lbl_04_01_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04_01_TitleMouseClicked(evt);
            }
        });
        add(lbl_04_01_Title);
        lbl_04_01_Title.setBounds(260, 30, 440, 25);

        chk_04_01_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_04_01_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_04_01_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_04_01_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_04_01_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_04_01_AutoStart);
        chk_04_01_AutoStart.setBounds(700, 30, 30, 30);

        lbl_04_01_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_01_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_04_01_IcoStep);
        lbl_04_01_IcoStep.setBounds(730, 30, 30, 25);

        btn_04_01_Next.setText("Далее");
        btn_04_01_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_01_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_01_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_01_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_01_NextActionPerformed(evt);
            }
        });
        add(btn_04_01_Next);
        btn_04_01_Next.setBounds(770, 30, 60, 30);

        lbl_04_01_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_01_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_01_Date_stop.setText("-");
        lbl_04_01_Date_stop.setBorder(null);
        add(lbl_04_01_Date_stop);
        lbl_04_01_Date_stop.setBounds(840, 30, 90, 25);

        lbl_04_01_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_01_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_01_Time_stop.setText("-");
        lbl_04_01_Time_stop.setBorder(null);
        add(lbl_04_01_Time_stop);
        lbl_04_01_Time_stop.setBounds(930, 30, 60, 25);

        lbl_04_02_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_02_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_02_Date_start.setText("-");
        lbl_04_02_Date_start.setBorder(null);
        add(lbl_04_02_Date_start);
        lbl_04_02_Date_start.setBounds(0, 60, 90, 25);

        lbl_04_02_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_02_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_02_Time_start.setText("-");
        lbl_04_02_Time_start.setBorder(null);
        add(lbl_04_02_Time_start);
        lbl_04_02_Time_start.setBounds(90, 60, 60, 25);

        lblAnimation_04_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_04_02);
        lblAnimation_04_02.setBounds(230, 60, 25, 25);

        lbl_04_02_Title.setText("4.2 Обработка. 1ый цикл");
        lbl_04_02_Title.setBorder(null);
        lbl_04_02_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04_02_TitleMouseClicked(evt);
            }
        });
        add(lbl_04_02_Title);
        lbl_04_02_Title.setBounds(260, 60, 440, 25);

        chk_04_02_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_04_02_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_04_02_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_04_02_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_04_02_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_04_02_AutoStart);
        chk_04_02_AutoStart.setBounds(700, 60, 30, 30);

        lbl_04_02_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_02_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_04_02_IcoStep);
        lbl_04_02_IcoStep.setBounds(730, 60, 30, 25);

        btn_04_02_Next.setText("Далее");
        btn_04_02_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_02_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_02_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_02_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_02_NextActionPerformed(evt);
            }
        });
        add(btn_04_02_Next);
        btn_04_02_Next.setBounds(770, 60, 60, 30);

        lbl_04_02_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_02_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_02_Date_stop.setText("-");
        lbl_04_02_Date_stop.setBorder(null);
        add(lbl_04_02_Date_stop);
        lbl_04_02_Date_stop.setBounds(840, 60, 90, 25);

        lbl_04_02_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_02_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_02_Time_stop.setText("-");
        lbl_04_02_Time_stop.setBorder(null);
        add(lbl_04_02_Time_stop);
        lbl_04_02_Time_stop.setBounds(930, 60, 60, 25);

        lbl_04_03_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_03_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_03_Date_start.setText("-");
        lbl_04_03_Date_start.setBorder(null);
        add(lbl_04_03_Date_start);
        lbl_04_03_Date_start.setBounds(0, 90, 90, 25);

        lbl_04_03_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_03_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_03_Time_start.setText("-");
        lbl_04_03_Time_start.setBorder(null);
        add(lbl_04_03_Time_start);
        lbl_04_03_Time_start.setBounds(90, 90, 60, 25);

        lblAnimation_04_03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_04_03);
        lblAnimation_04_03.setBounds(230, 90, 25, 25);

        lbl_04_03_Title.setText("4.3 Откачка газовой смеси");
        lbl_04_03_Title.setBorder(null);
        lbl_04_03_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04_03_TitleMouseClicked(evt);
            }
        });
        add(lbl_04_03_Title);
        lbl_04_03_Title.setBounds(260, 90, 440, 25);

        chk_04_03_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_04_03_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_04_03_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_04_03_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_04_03_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_04_03_AutoStart);
        chk_04_03_AutoStart.setBounds(700, 90, 30, 30);

        lbl_04_03_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_03_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_04_03_IcoStep);
        lbl_04_03_IcoStep.setBounds(730, 90, 30, 25);

        btn_04_03_Next.setText("Далее");
        btn_04_03_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_03_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_03_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_03_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_03_NextActionPerformed(evt);
            }
        });
        add(btn_04_03_Next);
        btn_04_03_Next.setBounds(770, 90, 60, 30);

        lbl_04_03_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_03_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_03_Date_stop.setText("-");
        lbl_04_03_Date_stop.setBorder(null);
        add(lbl_04_03_Date_stop);
        lbl_04_03_Date_stop.setBounds(840, 90, 90, 25);

        lbl_04_03_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_03_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_03_Time_stop.setText("-");
        lbl_04_03_Time_stop.setBorder(null);
        add(lbl_04_03_Time_stop);
        lbl_04_03_Time_stop.setBounds(930, 90, 60, 25);

        lbl_04_04_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_04_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_04_Date_start.setText("-");
        lbl_04_04_Date_start.setBorder(null);
        add(lbl_04_04_Date_start);
        lbl_04_04_Date_start.setBounds(0, 120, 90, 25);

        lbl_04_04_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_04_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_04_Time_start.setText("-");
        lbl_04_04_Time_start.setBorder(null);
        add(lbl_04_04_Time_start);
        lbl_04_04_Time_start.setBounds(90, 120, 60, 25);

        lblAnimation_04_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_04_04);
        lblAnimation_04_04.setBounds(230, 120, 25, 25);

        lbl_04_04_Title.setText("4.4 Напуск кислород-неона в приборы");
        lbl_04_04_Title.setBorder(null);
        lbl_04_04_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04_04_TitleMouseClicked(evt);
            }
        });
        add(lbl_04_04_Title);
        lbl_04_04_Title.setBounds(260, 120, 440, 25);

        chk_04_04_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_04_04_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_04_04_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_04_04_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_04_04_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_04_04_AutoStart);
        chk_04_04_AutoStart.setBounds(700, 120, 30, 30);

        lbl_04_04_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_04_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_04_04_IcoStep);
        lbl_04_04_IcoStep.setBounds(730, 120, 30, 25);

        btn_04_04_Next.setText("Далее");
        btn_04_04_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_04_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_04_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_04_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_04_NextActionPerformed(evt);
            }
        });
        add(btn_04_04_Next);
        btn_04_04_Next.setBounds(770, 120, 60, 30);

        lbl_04_04_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_04_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_04_Date_stop.setText("-");
        lbl_04_04_Date_stop.setBorder(null);
        add(lbl_04_04_Date_stop);
        lbl_04_04_Date_stop.setBounds(840, 120, 90, 25);

        lbl_04_04_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_04_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_04_Time_stop.setText("-");
        lbl_04_04_Time_stop.setBorder(null);
        add(lbl_04_04_Time_stop);
        lbl_04_04_Time_stop.setBounds(930, 120, 60, 25);

        lbl_04_05_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_05_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_05_Date_start.setText("-");
        lbl_04_05_Date_start.setBorder(null);
        add(lbl_04_05_Date_start);
        lbl_04_05_Date_start.setBounds(0, 150, 90, 25);

        lbl_04_05_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_05_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_05_Time_start.setText("-");
        lbl_04_05_Time_start.setBorder(null);
        add(lbl_04_05_Time_start);
        lbl_04_05_Time_start.setBounds(90, 150, 60, 25);

        lblAnimation_04_05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_04_05);
        lblAnimation_04_05.setBounds(230, 150, 25, 25);

        lbl_04_05_Title.setText("4.5 Обработка. 2ой цикл");
        lbl_04_05_Title.setBorder(null);
        lbl_04_05_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04_05_TitleMouseClicked(evt);
            }
        });
        add(lbl_04_05_Title);
        lbl_04_05_Title.setBounds(260, 150, 440, 25);

        chk_04_05_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_04_05_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_04_05_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_04_05_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_04_05_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_04_05_AutoStart);
        chk_04_05_AutoStart.setBounds(700, 150, 30, 30);

        lbl_04_05_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_05_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_04_05_IcoStep);
        lbl_04_05_IcoStep.setBounds(730, 150, 30, 25);

        btn_04_05_Next.setText("Далее");
        btn_04_05_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_05_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_05_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_05_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_05_NextActionPerformed(evt);
            }
        });
        add(btn_04_05_Next);
        btn_04_05_Next.setBounds(770, 150, 60, 30);

        lbl_04_05_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_05_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_05_Date_stop.setText("-");
        lbl_04_05_Date_stop.setBorder(null);
        add(lbl_04_05_Date_stop);
        lbl_04_05_Date_stop.setBounds(840, 150, 90, 25);

        lbl_04_05_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_05_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_05_Time_stop.setText("-");
        lbl_04_05_Time_stop.setBorder(null);
        add(lbl_04_05_Time_stop);
        lbl_04_05_Time_stop.setBounds(930, 150, 60, 25);

        lbl_04_06_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_06_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_06_Date_start.setText("-");
        lbl_04_06_Date_start.setBorder(null);
        add(lbl_04_06_Date_start);
        lbl_04_06_Date_start.setBounds(0, 180, 90, 25);

        lbl_04_06_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_06_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_06_Time_start.setText("-");
        lbl_04_06_Time_start.setBorder(null);
        add(lbl_04_06_Time_start);
        lbl_04_06_Time_start.setBounds(90, 180, 60, 25);

        lblAnimation_04_06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_04_06);
        lblAnimation_04_06.setBounds(230, 180, 25, 25);

        lbl_04_06_Title.setText("4.6 Откачка газовой смеси");
        lbl_04_06_Title.setBorder(null);
        lbl_04_06_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04_06_TitleMouseClicked(evt);
            }
        });
        add(lbl_04_06_Title);
        lbl_04_06_Title.setBounds(260, 180, 440, 25);

        chk_04_06_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_04_06_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_04_06_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_04_06_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_04_06_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_04_06_AutoStart);
        chk_04_06_AutoStart.setBounds(700, 180, 30, 30);

        lbl_04_06_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_06_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_04_06_IcoStep);
        lbl_04_06_IcoStep.setBounds(730, 180, 30, 25);

        btn_04_06_Next.setText("Далее");
        btn_04_06_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_06_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_06_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_06_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_06_NextActionPerformed(evt);
            }
        });
        add(btn_04_06_Next);
        btn_04_06_Next.setBounds(770, 180, 60, 30);

        lbl_04_06_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_06_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_06_Date_stop.setText("-");
        lbl_04_06_Date_stop.setBorder(null);
        add(lbl_04_06_Date_stop);
        lbl_04_06_Date_stop.setBounds(840, 180, 90, 25);

        lbl_04_06_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_06_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_06_Time_stop.setText("-");
        lbl_04_06_Time_stop.setBorder(null);
        add(lbl_04_06_Time_stop);
        lbl_04_06_Time_stop.setBounds(930, 180, 60, 25);

        lbl_04_07_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_07_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_07_Date_start.setText("-");
        lbl_04_07_Date_start.setBorder(null);
        add(lbl_04_07_Date_start);
        lbl_04_07_Date_start.setBounds(0, 210, 90, 25);

        lbl_04_07_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_07_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_07_Time_start.setText("-");
        lbl_04_07_Time_start.setBorder(null);
        add(lbl_04_07_Time_start);
        lbl_04_07_Time_start.setBounds(90, 210, 60, 25);

        lblAnimation_04_07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_04_07);
        lblAnimation_04_07.setBounds(230, 210, 25, 25);

        lbl_04_07_Title.setText("4.7 Переход на основную откачку");
        lbl_04_07_Title.setBorder(null);
        lbl_04_07_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_04_07_TitleMouseClicked(evt);
            }
        });
        add(lbl_04_07_Title);
        lbl_04_07_Title.setBounds(260, 210, 440, 25);

        chk_04_07_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_04_07_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_04_07_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_04_07_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_04_07_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_04_07_AutoStart);
        chk_04_07_AutoStart.setBounds(700, 210, 30, 30);

        lbl_04_07_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_07_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_04_07_IcoStep);
        lbl_04_07_IcoStep.setBounds(730, 210, 30, 25);

        btn_04_07_Next.setText("Далее");
        btn_04_07_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_07_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_07_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_07_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_07_NextActionPerformed(evt);
            }
        });
        add(btn_04_07_Next);
        btn_04_07_Next.setBounds(770, 210, 60, 30);

        lbl_04_07_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_07_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_07_Date_stop.setText("-");
        lbl_04_07_Date_stop.setBorder(null);
        add(lbl_04_07_Date_stop);
        lbl_04_07_Date_stop.setBounds(840, 210, 90, 25);

        lbl_04_07_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_04_07_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_04_07_Time_stop.setText("-");
        lbl_04_07_Time_stop.setBorder(null);
        add(lbl_04_07_Time_stop);
        lbl_04_07_Time_stop.setBounds(930, 210, 60, 25);

        btn_04_01_Start.setText("Старт");
        btn_04_01_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_01_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_01_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_01_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_01_StartActionPerformed(evt);
            }
        });
        add(btn_04_01_Start);
        btn_04_01_Start.setBounds(160, 30, 60, 30);

        btn_04_02_Start.setText("Старт");
        btn_04_02_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_02_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_02_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_02_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_02_StartActionPerformed(evt);
            }
        });
        add(btn_04_02_Start);
        btn_04_02_Start.setBounds(160, 60, 60, 30);

        btn_04_03_Start.setText("Старт");
        btn_04_03_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_03_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_03_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_03_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_03_StartActionPerformed(evt);
            }
        });
        add(btn_04_03_Start);
        btn_04_03_Start.setBounds(160, 90, 60, 30);

        btn_04_04_Start.setText("Старт");
        btn_04_04_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_04_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_04_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_04_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_04_StartActionPerformed(evt);
            }
        });
        add(btn_04_04_Start);
        btn_04_04_Start.setBounds(160, 120, 60, 30);

        btn_04_05_Start.setText("Старт");
        btn_04_05_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_05_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_05_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_05_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_05_StartActionPerformed(evt);
            }
        });
        add(btn_04_05_Start);
        btn_04_05_Start.setBounds(160, 150, 60, 30);

        btn_04_06_Start.setText("Старт");
        btn_04_06_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_06_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_06_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_06_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_06_StartActionPerformed(evt);
            }
        });
        add(btn_04_06_Start);
        btn_04_06_Start.setBounds(160, 180, 60, 30);

        btn_04_07_Start.setText("Старт");
        btn_04_07_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_04_07_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_04_07_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_04_07_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04_07_StartActionPerformed(evt);
            }
        });
        add(btn_04_07_Start);
        btn_04_07_Start.setBounds(160, 210, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_04_00_IcoStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04_00_IcoStepMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_04_00_IcoStepMouseClicked

    private void lbl_04_00_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04_00_TitleMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_04_00_TitleMouseClicked

    private void btn_04_01_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_01_NextActionPerformed
        DefaultNextButtonProcessing( "061", "Старт напуска кислород-неона", "Завершение напуска кислород-неона",
                                       "062", "Старт 1-го цикла обработки в кислород-неоне", chk_04_02_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_01_NextActionPerformed

    private void btn_04_02_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_02_NextActionPerformed
        DefaultNextButtonProcessing( "062", "Старт 1-го цикла обработки в кислород-неоне", "Завершение 1-го цикла обработки в кислород-неоне",
                                       "063", "Старт откачки кислород-неона", chk_04_03_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_02_NextActionPerformed

    private void btn_04_03_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_03_NextActionPerformed
        DefaultNextButtonProcessing( "063", "Старт откачки кислород-неона", "Завершение откачки кислород-неона",
                                       "064", "Старт напуска кислород-неона", chk_04_04_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_03_NextActionPerformed

    private void btn_04_04_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_04_NextActionPerformed
        DefaultNextButtonProcessing( "064", "Старт напуска кислород-неона", "Завершение напуска кислород-неона",
                                       "065", "Старт 2-го цикла обработки в кислород-неоне", chk_04_05_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_04_NextActionPerformed

    private void btn_04_05_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_05_NextActionPerformed
        DefaultNextButtonProcessing( "065", "Старт 2-го цикла обработки в кислород-неоне", "Завершение 2-го цикла обработки в кислород-неоне",
                                       "066", "Старт откачки кислород-неона", chk_04_06_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_05_NextActionPerformed

    private void btn_04_06_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_06_NextActionPerformed
        DefaultNextButtonProcessing( "066", "Старт откачки кислород-неона", "Завершение откачки кислород-неона",
                                       "067", "Старт программы перехода на основную откачку", chk_04_07_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_06_NextActionPerformed

    private void btn_04_07_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_07_NextActionPerformed
        if( theApp.IsCurrentStepInProgress() == false)
            return;
        
        //мы в процессе исполнения подэтапа XXX, переходим к следующему подэтапу XXX+1
        if( theApp.IsStepMapContainsKey( "067")) {
            TechProcessStepInfo info = theApp.GetStepInfo( "067");

            info.SetStopDateAsCurrent();
            info.SetStopReportTitle( "Завершение программы перехода на основную откачку");
            info.SetStopP5( theApp.GetDoubleFromPoller( "005.01"));
            info.SetStopP6( theApp.GetDoubleFromPoller( "006.01"));
            info.SetStopP7( theApp.GetDoubleFromPoller( "007.01"));

            theApp.NextCurrentStep();

            info = new TechProcessStepInfo( theApp);
            info.SetStartDateAsCurrent();
            //startReportTitle смотри ниже, под if'ом
            info.SetStartP5( theApp.GetDoubleFromPoller( "005.01"));
            info.SetStartP6( theApp.GetDoubleFromPoller( "006.01"));
            info.SetStartP7( theApp.GetDoubleFromPoller( "007.01"));

            

            theApp.SaveStepInfo( "081", info, true);

            if( theApp.m_pMainWnd.m_pPanel.pnlStep5.chk_05_01_AutoStart.isSelected()) {
                info.SetStartReportTitle( "Установка печек (этап пройден автоматически)");
                
                info.SetStopDateAsCurrent();
                info.SetStopReportTitle( "");
                info.SetStopP5( theApp.GetDoubleFromPoller( "005.01"));
                info.SetStopP6( theApp.GetDoubleFromPoller( "006.01"));
                info.SetStopP7( theApp.GetDoubleFromPoller( "007.01"));
            
                theApp.NextCurrentStep();

                info = new TechProcessStepInfo( theApp);
                
                info.SetStartReportTitle( "Старт термообезгаживания");
                info.SetStartDateAsCurrent();
                info.SetStartP5( theApp.GetDoubleFromPoller( "005.01"));
                info.SetStartP6( theApp.GetDoubleFromPoller( "006.01"));
                info.SetStartP7( theApp.GetDoubleFromPoller( "007.01"));

                theApp.SaveStepInfo( "082", info, true);

                theApp.ShowDlg5_2();
            }
            else {
                info.SetStartReportTitle( "Установка печек (ручное подтверждение)");
                theApp.ShowDlg5_1();
            }

            theApp.m_pMainWnd.m_pPanel.SetStates();

            theApp.m_ReportGenerator.Generate();

            theApp.m_pMainWnd.m_pPanel.Reposition();
        }
        else {
            logger.fatal( "Мы заканчиваем этап " + "067" + ", а инфы на него до сих пор нет!");
        }
    }//GEN-LAST:event_btn_04_07_NextActionPerformed

    private void btn_04_01_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_01_StartActionPerformed
        DefaultStartButtonProcessing( "061", "Старт напуска кислород-неона", "Завершение напуска кислород-неона",
                                       "062", "Старт 1-го цикла обработки в кислород-неоне", chk_04_02_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_01_StartActionPerformed

    private void btn_04_02_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_02_StartActionPerformed
        DefaultStartButtonProcessing( "062", "Старт 1-го цикла обработки в кислород-неоне", "Завершение 1-го цикла обработки в кислород-неоне",
                                       "063", "Старт откачки кислород-неона", chk_04_03_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_02_StartActionPerformed

    private void btn_04_03_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_03_StartActionPerformed
        DefaultStartButtonProcessing( "063", "Старт откачки кислород-неона", "Завершение откачки кислород-неона",
                                       "064", "Старт напуска кислород-неона", chk_04_04_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_03_StartActionPerformed

    private void btn_04_04_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_04_StartActionPerformed
        DefaultStartButtonProcessing( "064", "Старт напуска кислород-неона", "Завершение напуска кислород-неона",
                                       "065", "Старт 2-го цикла обработки в кислород-неоне", chk_04_05_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_04_StartActionPerformed

    private void btn_04_05_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_05_StartActionPerformed
        DefaultStartButtonProcessing( "065", "Старт 2-го цикла обработки в кислород-неоне", "Завершение 2-го цикла обработки в кислород-неоне",
                                       "066", "Старт откачки кислород-неона", chk_04_06_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_05_StartActionPerformed

    private void btn_04_06_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_06_StartActionPerformed
        DefaultStartButtonProcessing( "066", "Старт откачки кислород-неона", "Завершение откачки кислород-неона",
                                       "067", "Старт программы перехода на основную откачку", chk_04_07_AutoStart, logger, false);
    }//GEN-LAST:event_btn_04_06_StartActionPerformed

    private void btn_04_07_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_04_07_StartActionPerformed
        if( theApp.IsCurrentStepInProgress() == true)
            return;
        
        //мы начинаем процесс
        TechProcessStepInfo info = new TechProcessStepInfo( theApp);
        
        info.SetStartDateAsCurrent();
        info.SetStartReportTitle( "Старт программы перехода на основную откачку");
        info.SetStartP5( theApp.GetDoubleFromPoller( "005.01"));
        info.SetStartP6( theApp.GetDoubleFromPoller( "006.01"));
        info.SetStartP7( theApp.GetDoubleFromPoller( "007.01"));

        theApp.SaveStepInfo( "067", info, true);

        theApp.m_ReportGenerator.Generate();

        theApp.SetCurrentStepInProgress( true);
        StartProgramExecutor executor = new StartProgramExecutor( theApp, "AdminStep_4.7.xml");
        executor.StartThread();

        SetState();
    }//GEN-LAST:event_btn_04_07_StartActionPerformed

    private void lbl_04_00_Date_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04_00_Date_startMouseClicked
        ProcessHeaderDateTimeClick( 4);
    }//GEN-LAST:event_lbl_04_00_Date_startMouseClicked

    private void lbl_04_00_Time_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04_00_Time_startMouseClicked
        ProcessHeaderDateTimeClick( 4);
    }//GEN-LAST:event_lbl_04_00_Time_startMouseClicked

    private void lbl_04_01_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04_01_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 61);
        }
    }//GEN-LAST:event_lbl_04_01_TitleMouseClicked

    private void lbl_04_02_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04_02_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 62);
        }
    }//GEN-LAST:event_lbl_04_02_TitleMouseClicked

    private void lbl_04_03_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04_03_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 63);
        }
    }//GEN-LAST:event_lbl_04_03_TitleMouseClicked

    private void lbl_04_04_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04_04_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 64);
        }
    }//GEN-LAST:event_lbl_04_04_TitleMouseClicked

    private void lbl_04_05_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04_05_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 65);
        }
    }//GEN-LAST:event_lbl_04_05_TitleMouseClicked

    private void lbl_04_06_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04_06_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 66);
        }
    }//GEN-LAST:event_lbl_04_06_TitleMouseClicked

    private void lbl_04_07_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_04_07_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 67);
        }
    }//GEN-LAST:event_lbl_04_07_TitleMouseClicked
    
    public void SetState() {
        if( theApp.GetCurrentStep() / 20 == 3)
            m_bCollapsed = false;
        
        //4. Обработка в среде кислород-неона.
        FillHeaderStepDates( "061", lbl_04_00_Date_start, lbl_04_00_Time_start, "067", lbl_04_00_Date_stop, lbl_04_00_Time_stop);
        
        lbl_04_00_IcoStep.setIcon( m_bCollapsed ? theApp.GetResources().getIconTriaRight() : theApp.GetResources().getIconTriaDown());
        
        lbl_04_00_Title.setFont( theApp.GetCurrentStep() / 20 == 3 ? theApp.GetBoldFont() : theApp.GetUsualFont());
        lbl_04_00_Title.setEnabled( theApp.GetCurrentStep() / 20 <= 3);
        
        
        if( m_bCollapsed == false) {
            //4.1 Напуск кислород-неона в приборы
            FillAutoExecutedSubStep( 61, lbl_04_01_Date_start, lbl_04_01_Time_start, lblAnimation_04_01,
                                        btn_04_01_Start, lbl_04_01_Title, chk_04_01_AutoStart, lbl_04_01_IcoStep, btn_04_01_Next,
                                        lbl_04_01_Date_stop, lbl_04_01_Time_stop);
            
            // 4.2 Обработка. 1ый цикл.
            FillAutoExecutedSubStep( 62, lbl_04_02_Date_start, lbl_04_02_Time_start, lblAnimation_04_02, 
                                        btn_04_02_Start, lbl_04_02_Title, chk_04_02_AutoStart, lbl_04_02_IcoStep, btn_04_02_Next,
                                        lbl_04_02_Date_stop, lbl_04_02_Time_stop);
            
            //4.3 Откачка газовой смеси
            FillAutoExecutedSubStep( 63, lbl_04_03_Date_start, lbl_04_03_Time_start,  lblAnimation_04_03,
                                        btn_04_03_Start, lbl_04_03_Title, chk_04_03_AutoStart, lbl_04_03_IcoStep, btn_04_03_Next,
                                        lbl_04_03_Date_stop, lbl_04_03_Time_stop);
            
            //4.4 Напуск кислород-неона в приборы
            FillAutoExecutedSubStep( 64, lbl_04_04_Date_start, lbl_04_04_Time_start,  lblAnimation_04_04,
                                        btn_04_04_Start, lbl_04_04_Title, chk_04_04_AutoStart, lbl_04_04_IcoStep, btn_04_04_Next,
                                        lbl_04_04_Date_stop, lbl_04_04_Time_stop);
            
            //4.5 Обработка. 2ой цикл.
            FillAutoExecutedSubStep( 65, lbl_04_05_Date_start, lbl_04_05_Time_start,  lblAnimation_04_05,
                                        btn_04_05_Start, lbl_04_05_Title, chk_04_05_AutoStart, lbl_04_05_IcoStep, btn_04_05_Next,
                                        lbl_04_05_Date_stop, lbl_04_05_Time_stop);

            //4.6 Откачка газовой смеси
            FillAutoExecutedSubStep( 66, lbl_04_06_Date_start, lbl_04_06_Time_start,  lblAnimation_04_06,
                                        btn_04_06_Start, lbl_04_06_Title, chk_04_06_AutoStart, lbl_04_06_IcoStep, btn_04_06_Next,
                                        lbl_04_06_Date_stop, lbl_04_06_Time_stop);
            
            //4.7 Откачка газовой смеси
            FillAutoExecutedSubStep( 67, lbl_04_07_Date_start, lbl_04_07_Time_start,  lblAnimation_04_07,
                                        btn_04_07_Start, lbl_04_07_Title, chk_04_07_AutoStart, lbl_04_07_IcoStep, btn_04_07_Next,
                                        lbl_04_07_Date_stop, lbl_04_07_Time_stop);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_04_01_Next;
    public javax.swing.JButton btn_04_01_Start;
    public javax.swing.JButton btn_04_02_Next;
    public javax.swing.JButton btn_04_02_Start;
    public javax.swing.JButton btn_04_03_Next;
    public javax.swing.JButton btn_04_03_Start;
    public javax.swing.JButton btn_04_04_Next;
    public javax.swing.JButton btn_04_04_Start;
    public javax.swing.JButton btn_04_05_Next;
    public javax.swing.JButton btn_04_05_Start;
    public javax.swing.JButton btn_04_06_Next;
    public javax.swing.JButton btn_04_06_Start;
    public javax.swing.JButton btn_04_07_Next;
    public javax.swing.JButton btn_04_07_Start;
    public javax.swing.JCheckBox chk_04_01_AutoStart;
    public javax.swing.JCheckBox chk_04_02_AutoStart;
    public javax.swing.JCheckBox chk_04_03_AutoStart;
    public javax.swing.JCheckBox chk_04_04_AutoStart;
    public javax.swing.JCheckBox chk_04_05_AutoStart;
    public javax.swing.JCheckBox chk_04_06_AutoStart;
    public javax.swing.JCheckBox chk_04_07_AutoStart;
    public javax.swing.JLabel lblAnimation_04_01;
    public javax.swing.JLabel lblAnimation_04_02;
    public javax.swing.JLabel lblAnimation_04_03;
    public javax.swing.JLabel lblAnimation_04_04;
    public javax.swing.JLabel lblAnimation_04_05;
    public javax.swing.JLabel lblAnimation_04_06;
    public javax.swing.JLabel lblAnimation_04_07;
    public javax.swing.JLabel lbl_04_00_Date_start;
    public javax.swing.JLabel lbl_04_00_Date_stop;
    public javax.swing.JLabel lbl_04_00_IcoStep;
    public javax.swing.JLabel lbl_04_00_Time_start;
    public javax.swing.JLabel lbl_04_00_Time_stop;
    public javax.swing.JLabel lbl_04_00_Title;
    public javax.swing.JLabel lbl_04_01_Date_start;
    public javax.swing.JLabel lbl_04_01_Date_stop;
    public javax.swing.JLabel lbl_04_01_IcoStep;
    public javax.swing.JLabel lbl_04_01_Time_start;
    public javax.swing.JLabel lbl_04_01_Time_stop;
    public javax.swing.JLabel lbl_04_01_Title;
    public javax.swing.JLabel lbl_04_02_Date_start;
    public javax.swing.JLabel lbl_04_02_Date_stop;
    public javax.swing.JLabel lbl_04_02_IcoStep;
    public javax.swing.JLabel lbl_04_02_Time_start;
    public javax.swing.JLabel lbl_04_02_Time_stop;
    public javax.swing.JLabel lbl_04_02_Title;
    public javax.swing.JLabel lbl_04_03_Date_start;
    public javax.swing.JLabel lbl_04_03_Date_stop;
    public javax.swing.JLabel lbl_04_03_IcoStep;
    public javax.swing.JLabel lbl_04_03_Time_start;
    public javax.swing.JLabel lbl_04_03_Time_stop;
    public javax.swing.JLabel lbl_04_03_Title;
    public javax.swing.JLabel lbl_04_04_Date_start;
    public javax.swing.JLabel lbl_04_04_Date_stop;
    public javax.swing.JLabel lbl_04_04_IcoStep;
    public javax.swing.JLabel lbl_04_04_Time_start;
    public javax.swing.JLabel lbl_04_04_Time_stop;
    public javax.swing.JLabel lbl_04_04_Title;
    public javax.swing.JLabel lbl_04_05_Date_start;
    public javax.swing.JLabel lbl_04_05_Date_stop;
    public javax.swing.JLabel lbl_04_05_IcoStep;
    public javax.swing.JLabel lbl_04_05_Time_start;
    public javax.swing.JLabel lbl_04_05_Time_stop;
    public javax.swing.JLabel lbl_04_05_Title;
    public javax.swing.JLabel lbl_04_06_Date_start;
    public javax.swing.JLabel lbl_04_06_Date_stop;
    public javax.swing.JLabel lbl_04_06_IcoStep;
    public javax.swing.JLabel lbl_04_06_Time_start;
    public javax.swing.JLabel lbl_04_06_Time_stop;
    public javax.swing.JLabel lbl_04_06_Title;
    public javax.swing.JLabel lbl_04_07_Date_start;
    public javax.swing.JLabel lbl_04_07_Date_stop;
    public javax.swing.JLabel lbl_04_07_IcoStep;
    public javax.swing.JLabel lbl_04_07_Time_start;
    public javax.swing.JLabel lbl_04_07_Time_stop;
    public javax.swing.JLabel lbl_04_07_Title;
    // End of variables declaration//GEN-END:variables
}
