package hvv_admin.dialogs.step02;

import hvv_admin.dialogs.step01.TechProcessStep01Panel;
import hvv_admin.HVV_Admin;
import hvv_admin.comm.executor.to.StartProgramExecutor;
import hvv_admin.steps.info.TechProcessStepInfo;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import org.apache.log4j.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yaroslav
 */
public class TechProcessStep02_3_Dlg extends javax.swing.JDialog {

    static Logger logger = Logger.getLogger( TechProcessStep02_3_Dlg.class);
    final private HVV_Admin theApp;
    
    Timer tWaiting;
    /**
     * Creates new form TechProcessStep2_1_Dlg
     */
    public TechProcessStep02_3_Dlg( HVV_Admin app, java.awt.Frame parent, boolean modal) {
        super( parent, modal);
        theApp = app;
        initComponents();
        tWaiting = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrGet1 = new javax.swing.ButtonGroup();
        btnGrGet2 = new javax.swing.ButtonGroup();
        btnGrGet3 = new javax.swing.ButtonGroup();
        btnGrGet4 = new javax.swing.ButtonGroup();
        btnGrGet5 = new javax.swing.ButtonGroup();
        btnGrGet6 = new javax.swing.ButtonGroup();
        btnGrGet7 = new javax.swing.ButtonGroup();
        btnGrGet8 = new javax.swing.ButtonGroup();
        btnNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnYes = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        btnStart_231 = new javax.swing.JButton();
        lblStep_232 = new javax.swing.JLabel();
        lblIcoProcessing_231_2 = new javax.swing.JLabel();
        btnReturn_22 = new javax.swing.JButton();
        lblStep_231 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("2.3 Проверка герметичности установки приборов");
        setMinimumSize(new java.awt.Dimension(640, 400));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        getContentPane().setLayout(null);

        btnNext.setText("Далее");
        btnNext.setEnabled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext);
        btnNext.setBounds(540, 220, 90, 40);

        jLabel1.setText("При помощи течеискателя проверьте герметичность установленных приборов.");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 620, 30);

        btnYes.setText("Да, приборы установлены герметично. Перейти к пункту 2.4");
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });
        getContentPane().add(btnYes);
        btnYes.setBounds(10, 50, 620, 40);

        btnNo.setText("Обнаружена течь. Требуется переустановить приборы.");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNo);
        btnNo.setBounds(10, 120, 620, 40);

        btnStart_231.setText("Запустить наполнение азотом приборов.");
        btnStart_231.setEnabled(false);
        btnStart_231.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart_231ActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart_231);
        btnStart_231.setBounds(10, 170, 620, 40);

        lblStep_232.setText("Приборы заполнены азотом. Переустановите приборы.");
        lblStep_232.setEnabled(false);
        getContentPane().add(lblStep_232);
        lblStep_232.setBounds(10, 270, 620, 40);

        lblIcoProcessing_231_2.setBorder(null);
        getContentPane().add(lblIcoProcessing_231_2);
        lblIcoProcessing_231_2.setBounds(15, 225, 30, 30);

        btnReturn_22.setText("Приборы переустановлены. Вернуться в основную программу на пункт 2.2");
        btnReturn_22.setEnabled(false);
        btnReturn_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturn_22ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn_22);
        btnReturn_22.setBounds(10, 320, 620, 40);

        lblStep_231.setText("Идёт процесс наполнения азотом приборов.");
        lblStep_231.setEnabled(false);
        getContentPane().add(lblStep_231);
        lblStep_231.setBounds(50, 220, 480, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        lblIcoProcessing_231_2.setIcon( null);
        
        lblStep_231.setEnabled( false);
        
        lblStep_232.setEnabled( true);
        lblStep_232.setFont( theApp.GetBoldFont());
        
        btnNext.setEnabled( false);
        
        btnReturn_22.setEnabled( true);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        logger.debug( "In");
        //т.к. подэтап 2.3 ручной, мы просто переходим к следующему подэтапу (2.4)
        if( theApp.IsStepMapContainsKey( "023")) {
            TechProcessStepInfo info = theApp.GetStepInfo( "023");
            
            info.SetStopDateAsCurrent();
            info.SetStopReportTitle( "Проверка герметичности установки приборов");    
            info.SetStopP5( theApp.GetFromPoller( "005.01"));
            info.SetStopP6( theApp.GetFromPoller( "006.01"));
            info.SetStopP7( theApp.GetFromPoller( "007.01"));
                
            theApp.NextCurrentStep();
            
            if( theApp.m_pMainWnd.m_pPanel.pnlStep2.chk_02_04_AutoStart.isSelected()) {
                info = new TechProcessStepInfo( theApp);
                
                info.SetStartDateAsCurrent();
                info.SetStartReportTitle( "Старт основной откачки");    
                info.SetStartP5( theApp.GetFromPoller( "005.01"));
                info.SetStartP6( theApp.GetFromPoller( "006.01"));
                info.SetStartP7( theApp.GetFromPoller( "007.01"));
                
                theApp.SaveStepInfo( "024", info, true);
                
                //theApp.m_pMainWnd.m_EmuTimer.start();
                theApp.SetCurrentStepInProgress( true);
                StartProgramExecutor executor = new StartProgramExecutor( theApp, "AdminStep_2.4.xml");
                executor.StartThread();
            }
            
            theApp.m_ReportGenerator.Generate();
            theApp.GetStateKeeper().SaveState();
            
            theApp.m_pMainWnd.m_pPanel.SetStates();
            theApp.m_pMainWnd.m_pPanel.Reposition();
        }
        else {
            logger.fatal( "Мы заканчиваем этап 023, а инфы на него до сих пор нет!");
        }
        
        if( tWaiting != null && tWaiting.isRunning())
            tWaiting.stop();
        dispose();
        logger.debug( "Out");
    }//GEN-LAST:event_btnYesActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        logger.debug( "In");
        btnNo.setFont( theApp.GetBoldFont());
        btnYes.setEnabled( false);
        btnNo.setEnabled( false);
        btnStart_231.setEnabled( true);
        logger.debug( "Out");
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnStart_231ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart_231ActionPerformed
        btnStart_231.setEnabled( false);
        btnStart_231.setFont( theApp.GetBoldFont());
        
        theApp.m_bSpecial231ExecFinish = false;
        if( tWaiting != null && tWaiting.isRunning())
            tWaiting.stop();
        
        tWaiting = new Timer( 1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if( theApp.m_bSpecial231ExecFinish == true) {
                    tWaiting.stop();
                    lblIcoProcessing_231_2.setIcon( null);
        
                    lblStep_231.setEnabled( false);

                    lblStep_232.setEnabled( true);
                    lblStep_232.setFont( theApp.GetBoldFont());

                    btnNext.setEnabled( false);

                    btnReturn_22.setEnabled( true);
                }
            }
        });
        tWaiting.start();
        
        StartProgramExecutor executor = new StartProgramExecutor( theApp, "AdminStep_2.3.1.xml");
        executor.StartThread();
            
        lblIcoProcessing_231_2.setIcon( theApp.GetResources().getIconAnimatedProgress30());
        
        lblStep_231.setEnabled( true);
        lblStep_231.setFont( theApp.GetBoldFont());
        btnNext.setEnabled( true);
    }//GEN-LAST:event_btnStart_231ActionPerformed

    private void btnReturn_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturn_22ActionPerformed
        theApp.SpecialCase_23();
        
        if( theApp.m_pMainWnd.m_pPanel.pnlStep2.chk_02_02_AutoStart.isSelected()) {
            TechProcessStepInfo info = new TechProcessStepInfo( theApp);

            info.SetStartDateAsCurrent();
            info.SetStartReportTitle( "Старт предварительной откачки");
            info.SetStartP5( theApp.GetFromPoller( "005.01"));
            info.SetStartP6( theApp.GetFromPoller( "006.01"));
            info.SetStartP7( theApp.GetFromPoller( "007.01"));

            theApp.SaveStepInfo( "022", info, true);

            //theApp.m_pMainWnd.m_EmuTimer.start();
            theApp.SetCurrentStepInProgress( true);
            StartProgramExecutor executor = new StartProgramExecutor( theApp, "AdminStep_2.2.xml");
            executor.StartThread();
        }
        
        theApp.m_pMainWnd.m_pPanel.SetStates();
        theApp.m_pMainWnd.m_pPanel.Reposition();
            
        if( tWaiting != null && tWaiting.isRunning())
            tWaiting.stop();
        
        dispose();
    }//GEN-LAST:event_btnReturn_22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep02_3_Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep02_3_Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep02_3_Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep02_3_Dlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TechProcessStep02_3_Dlg dialog = new TechProcessStep02_3_Dlg( null, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrGet1;
    private javax.swing.ButtonGroup btnGrGet2;
    private javax.swing.ButtonGroup btnGrGet3;
    private javax.swing.ButtonGroup btnGrGet4;
    private javax.swing.ButtonGroup btnGrGet5;
    private javax.swing.ButtonGroup btnGrGet6;
    private javax.swing.ButtonGroup btnGrGet7;
    private javax.swing.ButtonGroup btnGrGet8;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnReturn_22;
    private javax.swing.JButton btnStart_231;
    private javax.swing.JButton btnYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIcoProcessing_231_2;
    private javax.swing.JLabel lblStep_231;
    private javax.swing.JLabel lblStep_232;
    // End of variables declaration//GEN-END:variables
}
