/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin.dialogs.step02;

import hvv_admin.HVV_Admin;
import hvv_admin.comm.executor.to.StartProgramExecutor;
import hvv_admin.steps.info.TechProcessStepInfo;
import hvv_admin.dialogs.TechProcessStepPanelTemplate;
import java.awt.event.MouseEvent;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class TechProcessStep02Panel extends TechProcessStepPanelTemplate {
    public final int MAXIMIZED_HEIGHT = 150;
    static Logger logger = Logger.getLogger(TechProcessStep02Panel.class);
    
    /**
     * Creates new form TechProcessStep1Panel
     */
    public TechProcessStep02Panel( HVV_Admin app, boolean bCollapsed) {
        initComponents();
        theApp = app;
        m_bCollapsed = bCollapsed;
        m_nPageNumber = 1;
        m_bFirstOfDoubleClickHeaderDateTime = false;
        
        String strTitle = theApp.GetStepName( 20);
        if( strTitle != null) lbl_02_00_Title.setText( "2. " + strTitle);
        strTitle = theApp.GetStepName( 21);
        if( strTitle != null) lbl_02_01_Title.setText( "2.1 " + strTitle);
        strTitle = theApp.GetStepName( 22);
        if( strTitle != null) lbl_02_02_Title.setText( "2.2 " + strTitle);
        strTitle = theApp.GetStepName( 23);
        if( strTitle != null) lbl_02_03_Title.setText( "2.3 " + strTitle);
        strTitle = theApp.GetStepName( 24);
        if( strTitle != null) lbl_02_04_Title.setText( "2.4 " + strTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_02_00_Date_start = new javax.swing.JLabel();
        lbl_02_00_Time_start = new javax.swing.JLabel();
        lbl_02_00_IcoStep = new javax.swing.JLabel();
        lbl_02_00_Title = new javax.swing.JLabel();
        lbl_02_00_Date_stop = new javax.swing.JLabel();
        lbl_02_00_Time_stop = new javax.swing.JLabel();
        lbl_02_01_Date_start = new javax.swing.JLabel();
        lbl_02_01_Time_start = new javax.swing.JLabel();
        lbl_02_01_Title = new javax.swing.JLabel();
        lbl_02_01_IcoStep = new javax.swing.JLabel();
        btn_02_01_Next = new javax.swing.JButton();
        lbl_02_01_Date_stop = new javax.swing.JLabel();
        lbl_02_01_Time_stop = new javax.swing.JLabel();
        lbl_02_02_Date_start = new javax.swing.JLabel();
        lbl_02_02_Time_start = new javax.swing.JLabel();
        lblAnimation_02_02 = new javax.swing.JLabel();
        lbl_02_02_Title = new javax.swing.JLabel();
        chk_02_02_AutoStart = new javax.swing.JCheckBox();
        lbl_02_02_IcoStep = new javax.swing.JLabel();
        btn_02_02_Next = new javax.swing.JButton();
        lbl_02_02_Date_stop = new javax.swing.JLabel();
        lbl_02_02_Time_stop = new javax.swing.JLabel();
        lbl_02_03_Date_start = new javax.swing.JLabel();
        lbl_02_03_Time_start = new javax.swing.JLabel();
        lbl_02_03_Title = new javax.swing.JLabel();
        lbl_02_03_IcoStep = new javax.swing.JLabel();
        btn_02_03_Next = new javax.swing.JButton();
        lbl_02_03_Date_stop = new javax.swing.JLabel();
        lbl_02_03_Time_stop = new javax.swing.JLabel();
        lbl_02_04_Date_start = new javax.swing.JLabel();
        lbl_02_04_Time_start = new javax.swing.JLabel();
        lblAnimation_02_04 = new javax.swing.JLabel();
        lbl_02_04_Title = new javax.swing.JLabel();
        chk_02_04_AutoStart = new javax.swing.JCheckBox();
        lbl_02_04_IcoStep = new javax.swing.JLabel();
        btn_02_04_Next = new javax.swing.JButton();
        lbl_02_04_Date_stop = new javax.swing.JLabel();
        lbl_02_04_Time_stop = new javax.swing.JLabel();
        btn_02_01_Start = new javax.swing.JButton();
        btn_02_02_Start = new javax.swing.JButton();
        btn_02_03_Start = new javax.swing.JButton();
        btn_02_04_Start = new javax.swing.JButton();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1000, 150));
        setMinimumSize(new java.awt.Dimension(1000, 30));
        setLayout(null);

        lbl_02_00_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_00_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_00_Date_start.setText("-");
        lbl_02_00_Date_start.setBorder(null);
        lbl_02_00_Date_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_02_00_Date_startMouseClicked(evt);
            }
        });
        add(lbl_02_00_Date_start);
        lbl_02_00_Date_start.setBounds(0, 0, 90, 25);

        lbl_02_00_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_00_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_00_Time_start.setText("-");
        lbl_02_00_Time_start.setBorder(null);
        lbl_02_00_Time_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_02_00_Time_startMouseClicked(evt);
            }
        });
        add(lbl_02_00_Time_start);
        lbl_02_00_Time_start.setBounds(90, 0, 60, 25);

        lbl_02_00_IcoStep.setBorder(null);
        lbl_02_00_IcoStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_02_00_IcoStepMouseClicked(evt);
            }
        });
        add(lbl_02_00_IcoStep);
        lbl_02_00_IcoStep.setBounds(150, 0, 30, 25);

        lbl_02_00_Title.setText("2. Установка приборов");
        lbl_02_00_Title.setBorder(null);
        lbl_02_00_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_02_00_TitleMouseClicked(evt);
            }
        });
        add(lbl_02_00_Title);
        lbl_02_00_Title.setBounds(180, 0, 470, 25);

        lbl_02_00_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_00_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_00_Date_stop.setText("-");
        lbl_02_00_Date_stop.setBorder(null);
        add(lbl_02_00_Date_stop);
        lbl_02_00_Date_stop.setBounds(840, 0, 90, 25);

        lbl_02_00_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_00_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_00_Time_stop.setText("-");
        lbl_02_00_Time_stop.setBorder(null);
        add(lbl_02_00_Time_stop);
        lbl_02_00_Time_stop.setBounds(930, 0, 60, 25);

        lbl_02_01_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_01_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_01_Date_start.setText("-");
        lbl_02_01_Date_start.setBorder(null);
        add(lbl_02_01_Date_start);
        lbl_02_01_Date_start.setBounds(0, 30, 90, 25);

        lbl_02_01_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_01_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_01_Time_start.setText("-");
        lbl_02_01_Time_start.setBorder(null);
        add(lbl_02_01_Time_start);
        lbl_02_01_Time_start.setBounds(90, 30, 60, 25);

        lbl_02_01_Title.setText("2.1 Занесение информации об установленных приборах");
        lbl_02_01_Title.setBorder(null);
        lbl_02_01_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_02_01_TitleMouseClicked(evt);
            }
        });
        add(lbl_02_01_Title);
        lbl_02_01_Title.setBounds(260, 30, 440, 25);

        lbl_02_01_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_01_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_02_01_IcoStep);
        lbl_02_01_IcoStep.setBounds(730, 30, 30, 25);

        btn_02_01_Next.setText("Далее");
        btn_02_01_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_02_01_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_02_01_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_02_01_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_02_01_NextActionPerformed(evt);
            }
        });
        add(btn_02_01_Next);
        btn_02_01_Next.setBounds(770, 30, 60, 30);

        lbl_02_01_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_01_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_01_Date_stop.setText("-");
        lbl_02_01_Date_stop.setBorder(null);
        add(lbl_02_01_Date_stop);
        lbl_02_01_Date_stop.setBounds(840, 30, 90, 25);

        lbl_02_01_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_01_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_01_Time_stop.setText("-");
        lbl_02_01_Time_stop.setBorder(null);
        add(lbl_02_01_Time_stop);
        lbl_02_01_Time_stop.setBounds(930, 30, 60, 25);

        lbl_02_02_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_02_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_02_Date_start.setText("-");
        lbl_02_02_Date_start.setBorder(null);
        add(lbl_02_02_Date_start);
        lbl_02_02_Date_start.setBounds(0, 60, 90, 25);

        lbl_02_02_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_02_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_02_Time_start.setText("-");
        lbl_02_02_Time_start.setBorder(null);
        add(lbl_02_02_Time_start);
        lbl_02_02_Time_start.setBounds(90, 60, 60, 25);

        lblAnimation_02_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_02_02);
        lblAnimation_02_02.setBounds(230, 60, 25, 25);

        lbl_02_02_Title.setText("2.2 Предварительная откачка");
        lbl_02_02_Title.setBorder(null);
        lbl_02_02_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_02_02_TitleMouseClicked(evt);
            }
        });
        add(lbl_02_02_Title);
        lbl_02_02_Title.setBounds(260, 60, 440, 25);

        chk_02_02_AutoStart.setEnabled(false);
        chk_02_02_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_02_02_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_02_02_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_02_02_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_02_02_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_02_02_AutoStart);
        chk_02_02_AutoStart.setBounds(700, 60, 30, 30);

        lbl_02_02_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_02_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_02_02_IcoStep);
        lbl_02_02_IcoStep.setBounds(730, 60, 30, 25);

        btn_02_02_Next.setText("Далее");
        btn_02_02_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_02_02_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_02_02_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_02_02_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_02_02_NextActionPerformed(evt);
            }
        });
        add(btn_02_02_Next);
        btn_02_02_Next.setBounds(770, 60, 60, 30);

        lbl_02_02_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_02_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_02_Date_stop.setText("-");
        lbl_02_02_Date_stop.setBorder(null);
        add(lbl_02_02_Date_stop);
        lbl_02_02_Date_stop.setBounds(840, 60, 90, 25);

        lbl_02_02_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_02_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_02_Time_stop.setText("-");
        lbl_02_02_Time_stop.setBorder(null);
        add(lbl_02_02_Time_stop);
        lbl_02_02_Time_stop.setBounds(930, 60, 60, 25);

        lbl_02_03_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_03_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_03_Date_start.setText("-");
        lbl_02_03_Date_start.setBorder(null);
        add(lbl_02_03_Date_start);
        lbl_02_03_Date_start.setBounds(0, 90, 90, 25);

        lbl_02_03_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_03_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_03_Time_start.setText("-");
        lbl_02_03_Time_start.setBorder(null);
        add(lbl_02_03_Time_start);
        lbl_02_03_Time_start.setBounds(90, 90, 60, 25);

        lbl_02_03_Title.setText("2.3 Проверка герметичности установки приборов");
        lbl_02_03_Title.setBorder(null);
        lbl_02_03_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_02_03_TitleMouseClicked(evt);
            }
        });
        add(lbl_02_03_Title);
        lbl_02_03_Title.setBounds(260, 90, 440, 25);

        lbl_02_03_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_03_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_02_03_IcoStep);
        lbl_02_03_IcoStep.setBounds(730, 90, 30, 25);

        btn_02_03_Next.setText("Далее");
        btn_02_03_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_02_03_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_02_03_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_02_03_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_02_03_NextActionPerformed(evt);
            }
        });
        add(btn_02_03_Next);
        btn_02_03_Next.setBounds(770, 90, 60, 30);

        lbl_02_03_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_03_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_03_Date_stop.setText("-");
        lbl_02_03_Date_stop.setBorder(null);
        add(lbl_02_03_Date_stop);
        lbl_02_03_Date_stop.setBounds(840, 90, 90, 25);

        lbl_02_03_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_03_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_03_Time_stop.setText("-");
        lbl_02_03_Time_stop.setBorder(null);
        add(lbl_02_03_Time_stop);
        lbl_02_03_Time_stop.setBounds(930, 90, 60, 25);

        lbl_02_04_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_04_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_04_Date_start.setText("-");
        lbl_02_04_Date_start.setBorder(null);
        add(lbl_02_04_Date_start);
        lbl_02_04_Date_start.setBounds(0, 120, 90, 25);

        lbl_02_04_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_04_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_04_Time_start.setText("-");
        lbl_02_04_Time_start.setBorder(null);
        add(lbl_02_04_Time_start);
        lbl_02_04_Time_start.setBounds(90, 120, 60, 25);

        lblAnimation_02_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_02_04);
        lblAnimation_02_04.setBounds(230, 120, 25, 25);

        lbl_02_04_Title.setText("2.4 Основная откачка");
        lbl_02_04_Title.setBorder(null);
        lbl_02_04_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_02_04_TitleMouseClicked(evt);
            }
        });
        add(lbl_02_04_Title);
        lbl_02_04_Title.setBounds(260, 120, 440, 25);

        chk_02_04_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_02_04_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_02_04_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_02_04_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_02_04_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_02_04_AutoStart);
        chk_02_04_AutoStart.setBounds(700, 120, 30, 30);

        lbl_02_04_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_04_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_02_04_IcoStep);
        lbl_02_04_IcoStep.setBounds(730, 120, 30, 25);

        btn_02_04_Next.setText("Далее");
        btn_02_04_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_02_04_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_02_04_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_02_04_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_02_04_NextActionPerformed(evt);
            }
        });
        add(btn_02_04_Next);
        btn_02_04_Next.setBounds(770, 120, 60, 30);

        lbl_02_04_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_04_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_04_Date_stop.setText("-");
        lbl_02_04_Date_stop.setBorder(null);
        add(lbl_02_04_Date_stop);
        lbl_02_04_Date_stop.setBounds(840, 120, 90, 25);

        lbl_02_04_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_02_04_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_02_04_Time_stop.setText("-");
        lbl_02_04_Time_stop.setBorder(null);
        add(lbl_02_04_Time_stop);
        lbl_02_04_Time_stop.setBounds(930, 120, 60, 25);

        btn_02_01_Start.setText("Старт");
        btn_02_01_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_02_01_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_02_01_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_02_01_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_02_01_StartActionPerformed(evt);
            }
        });
        add(btn_02_01_Start);
        btn_02_01_Start.setBounds(160, 30, 60, 30);

        btn_02_02_Start.setText("Старт");
        btn_02_02_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_02_02_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_02_02_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_02_02_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_02_02_StartActionPerformed(evt);
            }
        });
        add(btn_02_02_Start);
        btn_02_02_Start.setBounds(160, 60, 60, 30);

        btn_02_03_Start.setText("Старт");
        btn_02_03_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_02_03_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_02_03_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_02_03_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_02_03_StartActionPerformed(evt);
            }
        });
        add(btn_02_03_Start);
        btn_02_03_Start.setBounds(160, 90, 60, 30);

        btn_02_04_Start.setText("Старт");
        btn_02_04_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_02_04_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_02_04_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_02_04_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_02_04_StartActionPerformed(evt);
            }
        });
        add(btn_02_04_Start);
        btn_02_04_Start.setBounds(160, 120, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_02_00_IcoStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_02_00_IcoStepMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_02_00_IcoStepMouseClicked

    private void lbl_02_00_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_02_00_TitleMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_02_00_TitleMouseClicked
    
    public void SetState() {
        if( theApp.GetCurrentStep() / 20 == 1)
            m_bCollapsed = false;
        
        //2. Установка приборов
        FillHeaderStepDates( "021", lbl_02_00_Date_start, lbl_02_00_Time_start, "024", lbl_02_00_Date_stop, lbl_02_00_Time_stop);
        
        lbl_02_00_IcoStep.setIcon( m_bCollapsed ? theApp.GetResources().getIconTriaRight() : theApp.GetResources().getIconTriaDown());
        
        lbl_02_00_Title.setFont( theApp.GetCurrentStep() / 20 == 1 ? theApp.GetBoldFont() : theApp.GetUsualFont());
        lbl_02_00_Title.setEnabled( theApp.GetCurrentStep() / 20 <= 1);
        
        
        if( m_bCollapsed == false) {
            //2.1 Занесение информации об установленных приборах
            FillStepDates( "021", lbl_02_01_Date_start, lbl_02_01_Time_start, lbl_02_01_Date_stop, lbl_02_01_Time_stop);

            lbl_02_01_Title.setFont( theApp.GetCurrentStep() == 21 ? theApp.GetBoldFont() : theApp.GetUsualFont());
            lbl_02_01_Title.setEnabled( theApp.GetCurrentStep() <= 21);

            //РУЧНОЙ ПОДЭТАП
            btn_02_01_Next.setVisible( false); //theApp.GetCurrentStep() == 21);
            btn_02_01_Start.setVisible( false);
            
            //2.2 Предварительная откачка
            FillStepDates( "022", lbl_02_02_Date_start, lbl_02_02_Time_start, lbl_02_02_Date_stop, lbl_02_02_Time_stop);

            /*
            if( theApp.GetCurrentStep() == 22 && theApp.m_pMainWnd.m_EmuTimer.isRunning())
                lblAnimation_02_02.setIcon( theApp.GetResources().getIconAnimatedProgress25());
            else
                lblAnimation_02_02.setIcon( null);
            */
            
            lbl_02_02_Title.setFont( theApp.GetCurrentStep() == 22 ? theApp.GetBoldFont() : theApp.GetUsualFont());
            lbl_02_02_Title.setEnabled( theApp.GetCurrentStep() <= 22);

            //chk_02_02_AutoStart.setEnabled( theApp.GetCurrentStep() < 22);
            chk_02_02_AutoStart.setEnabled( false);
            
            if( theApp.IsStepMapContainsKey( "022")) {
                TechProcessStepInfo info = theApp.GetStepInfo( "022");
                lbl_02_02_IcoStep.setIcon( info.GetExecApproved() ?  theApp.GetResources().getIconLittleBrightGreen() : null);
            }
            else
                lbl_02_02_IcoStep.setIcon( null);
            
            //АВТО-POSSIBLE ПОДЭТАП
            if( theApp.GetCurrentStep() == 22) {
                btn_02_02_Start.setVisible( !theApp.IsCurrentStepInProgress());
                btn_02_02_Next.setVisible( theApp.IsCurrentStepInProgress());
            }
            else {
                btn_02_02_Start.setVisible( false);
                btn_02_02_Next.setVisible( false);
            }
            
            //2.3 Проверка герметичности установки приборов ( ?? да   ?? нет)
            FillStepDates( "023", lbl_02_03_Date_start, lbl_02_03_Time_start, lbl_02_03_Date_stop, lbl_02_03_Time_stop);

            lbl_02_03_Title.setFont( theApp.GetCurrentStep() == 23 ? theApp.GetBoldFont() : theApp.GetUsualFont());
            lbl_02_03_Title.setEnabled( theApp.GetCurrentStep() <= 23);

            //РУЧНОЙ ПОДЭТАП
            btn_02_03_Start.setVisible( false);
            btn_02_03_Next.setVisible( false); //theApp.GetCurrentStep() == 23);
            
            
            //2.4 Основная откачка
            FillStepDates( "024", lbl_02_04_Date_start, lbl_02_04_Time_start, lbl_02_04_Date_stop, lbl_02_04_Time_stop);

            /*
            if( theApp.GetCurrentStep() == 24 && theApp.m_pMainWnd.m_EmuTimer.isRunning())
                lblAnimation_02_04.setIcon( theApp.GetResources().getIconAnimatedProgress25());
            else
                lblAnimation_02_04.setIcon( null);
            */
            
            lbl_02_04_Title.setFont( theApp.GetCurrentStep() == 24 ? theApp.GetBoldFont() : theApp.GetUsualFont());
            lbl_02_04_Title.setEnabled( theApp.GetCurrentStep() <= 24);

            chk_02_04_AutoStart.setEnabled( theApp.GetCurrentStep() < 24);
            
            if( theApp.IsStepMapContainsKey( "024")) {
                TechProcessStepInfo info = theApp.GetStepInfo( "024");
                lbl_02_04_IcoStep.setIcon( info.GetExecApproved() ?  theApp.GetResources().getIconLittleBrightGreen() : null);
            }
            else
                lbl_02_04_IcoStep.setIcon( null);
            
            //АВТО-POSSIBLE ПОДЭТАП
            if( theApp.GetCurrentStep() == 24) {
                btn_02_04_Start.setVisible( !theApp.IsCurrentStepInProgress());
                btn_02_04_Next.setVisible( theApp.IsCurrentStepInProgress());
            }
            else {
                btn_02_04_Start.setVisible( false);
                btn_02_04_Next.setVisible( false);
            }
        }
    }
    
    private void btn_02_02_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_02_02_NextActionPerformed
        if( theApp.IsCurrentStepInProgress() == false) {
            //мы ещё не начинали этапа
            return;
        }
        
        //мы в процессе исполнения подэтапа 2.2 переходим к следующему подэтапу 2.3
        //theApp.m_pMainWnd.m_EmuTimer.stop();
        if( theApp.IsStepMapContainsKey( "022")) {
            TechProcessStepInfo info = theApp.GetStepInfo( "022");
            
            info.SetStopDateAsCurrent();
            info.SetStopReportTitle( "Завершение предварительной откачки");
            info.SetStopP5( theApp.GetFromPoller( "005.01"));
            info.SetStopP6( theApp.GetFromPoller( "006.01"));
            info.SetStopP7( theApp.GetFromPoller( "007.01"));

            theApp.NextCurrentStep();

            info = new TechProcessStepInfo( theApp);
            
            info.SetStartReportTitle( "");
            info.SetStartDateAsCurrent();
            info.SetStartP5( theApp.GetFromPoller( "005.01"));
            info.SetStartP6( theApp.GetFromPoller( "006.01"));
            info.SetStartP7( theApp.GetFromPoller( "007.01"));

            theApp.SaveStepInfo( "023", info, true);

            theApp.m_ReportGenerator.Generate();
            SetState();
            theApp.m_pMainWnd.m_pPanel.Reposition();

            theApp.ShowDlg2_3();
        }
        else {
            logger.fatal( "Мы заканчиваем этап 022, а инфы на него до сих пор нет!");
        }
    }//GEN-LAST:event_btn_02_02_NextActionPerformed

    private void btn_02_03_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_02_03_NextActionPerformed
        //полный STUB т.к. эту кнопка не видно никогда и нажать на неё нельзя        
        /*
        //т.к. подэтап 2.3 ручной, мы просто переходим к следующему подэтапу (2.4)
        if( theApp.GetMapSteps().containsKey( "023")) {
            TechProcessStepInfo info = ( TechProcessStepInfo) theApp.GetMapSteps().get( "023");
            info.SetStopDateAsCurrent();
            
            theApp.NextCurrentStep();
            
            if( chk_02_04_AutoStart.isSelected()) {
                info = new TechProcessStepInfo( theApp);
                info.SetStartDateAsCurrent();
                theApp.GetMapSteps().put( "024", info);
                theApp.m_pMainWnd.m_EmuTimer.start();
            }
            
            SetState();
            theApp.m_pMainWnd.m_pPanel.Reposition();
        }
        else {
            logger.fatal( "Мы заканчиваем этап 023, а инфы на него до сих пор нет!");
        }
        */
    }//GEN-LAST:event_btn_02_03_NextActionPerformed

    private void btn_02_04_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_02_04_NextActionPerformed
        if( theApp.IsCurrentStepInProgress() == false)
            return;
        
        //мы в процессе исполнения подэтапа 2.4, переходим к следующему подэтапу 3.1
        //theApp.m_pMainWnd.m_EmuTimer.stop();
        if( theApp.IsStepMapContainsKey( "024")) {
            TechProcessStepInfo info = theApp.GetStepInfo( "024");

            info.SetStopDateAsCurrent();
            info.SetStopReportTitle( "Завершение основной откачки");
            info.SetStopP5( theApp.GetFromPoller( "005.01"));
            info.SetStopP6( theApp.GetFromPoller( "006.01"));
            info.SetStopP7( theApp.GetFromPoller( "007.01"));

            theApp.NextCurrentStep();

            if( theApp.m_pMainWnd.m_pPanel.pnlStep3.chk_03_01_AutoStart.isSelected()) {
                info = new TechProcessStepInfo( theApp);
                
                info.SetStartDateAsCurrent();
                info.SetStartReportTitle( "Старт напуска кислорода");
                info.SetStartP5( theApp.GetFromPoller( "005.01"));
                info.SetStartP6( theApp.GetFromPoller( "006.01"));
                info.SetStartP7( theApp.GetFromPoller( "007.01"));

                theApp.SaveStepInfo( "041", info, true);

                //theApp.m_pMainWnd.m_EmuTimer.start();
                StartProgramExecutor executor = new StartProgramExecutor( theApp, "AdminStep_3.1.xml");
                executor.StartThread();
                theApp.SetCurrentStepInProgress( true);
            }

            theApp.m_ReportGenerator.Generate();
            theApp.m_pMainWnd.m_pPanel.SetStates();
            theApp.m_pMainWnd.m_pPanel.Reposition();
        }
        else {
            logger.fatal( "Мы заканчиваем этап 024, а инфы на него до сих пор нет!");
        }
        
    }//GEN-LAST:event_btn_02_04_NextActionPerformed

    private void btn_02_01_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_02_01_NextActionPerformed
        //полный STUB т.к. эту кнопка не видно никогда и нажать на неё нельзя
        
        /*        
        //т.к. этап 2.1 ручной, мы переходим к следующему подэтапу (2.2)
        if( theApp.GetMapSteps().containsKey( "021")) {
            TechProcessStepInfo info = ( TechProcessStepInfo) theApp.GetMapSteps().get( "021");
            info.SetStopDateAsCurrent();

            theApp.NextCurrentStep();

            if( chk_02_02_AutoStart.isSelected()) {
                info = new TechProcessStepInfo( theApp);
                info.SetStartDateAsCurrent();
                theApp.GetMapSteps().put( "022", info);
                theApp.m_pMainWnd.m_EmuTimer.start();
            }

            SetState();
            theApp.m_pMainWnd.m_pPanel.Reposition();
        }
        else {
            logger.fatal( "Мы заканчиваем этап 021, а инфы на него до сих пор нет!");
        }
        */
    }//GEN-LAST:event_btn_02_01_NextActionPerformed

    private void btn_02_01_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_02_01_StartActionPerformed
        //EMPTY STUB - ручной этап
    }//GEN-LAST:event_btn_02_01_StartActionPerformed

    private void btn_02_02_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_02_02_StartActionPerformed
        if( theApp.IsCurrentStepInProgress() == true)
            return;

        //мы начинаем процесс
        TechProcessStepInfo info = new TechProcessStepInfo( theApp);
        info.SetStartDateAsCurrent();
        info.SetStartReportTitle( "Старт предварительной откачки");
        info.SetStartP5( theApp.GetFromPoller( "005.01"));
        info.SetStartP6( theApp.GetFromPoller( "006.01"));
        info.SetStartP7( theApp.GetFromPoller( "007.01"));

        theApp.SaveStepInfo( "022", info, true);
        theApp.m_ReportGenerator.Generate();

        //theApp.m_pMainWnd.m_EmuTimer.start();
        theApp.SetCurrentStepInProgress( true);
        StartProgramExecutor executor = new StartProgramExecutor( theApp, "AdminStep_2.2.xml");
        executor.StartThread();

        SetState();    
    }//GEN-LAST:event_btn_02_02_StartActionPerformed

    private void btn_02_03_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_02_03_StartActionPerformed
        //EMPTY STUB - ручной этап
    }//GEN-LAST:event_btn_02_03_StartActionPerformed

    private void btn_02_04_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_02_04_StartActionPerformed
        //мы начинаем процесс
        TechProcessStepInfo info = new TechProcessStepInfo( theApp);
        
        info.SetStartDateAsCurrent();
        info.SetStartReportTitle( "Старт основной откачки");
        info.SetStartP5( theApp.GetFromPoller( "005.01"));
        info.SetStartP6( theApp.GetFromPoller( "006.01"));
        info.SetStartP7( theApp.GetFromPoller( "007.01"));

        theApp.SaveStepInfo( "024", info, true);

        theApp.m_ReportGenerator.Generate();

        //theApp.m_pMainWnd.m_EmuTimer.start();
        theApp.SetCurrentStepInProgress( true);
        StartProgramExecutor executor = new StartProgramExecutor( theApp, "AdminStep_2.4.xml");
        executor.StartThread();

        SetState();
    }//GEN-LAST:event_btn_02_04_StartActionPerformed

    private void lbl_02_00_Date_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_02_00_Date_startMouseClicked
        /*Date prev = theApp.GetLocalDate();
        SimpleDateFormat sdf = new SimpleDateFormat( "yyyy-MM-dd HH:mm");
        
        String strDate = theApp.m_pMainWnd.m_pPanel.pnlStep1.lbl_01_00_Date_start.getText();
        String strTime = theApp.m_pMainWnd.m_pPanel.pnlStep1.lbl_01_00_Time_start.getText();
        Date curr = theApp.GetLocalDate();
        try {
            curr = sdf.parse( strDate.substring( 3) + " " + strTime);
        } catch( ParseException ex) {
            logger.error( "ParseException caught!", ex);
        }
        ProcessHeaderDateTimeClick( 2, prev, curr);*/
        ProcessHeaderDateTimeClick( 2);
    }//GEN-LAST:event_lbl_02_00_Date_startMouseClicked

    private void lbl_02_00_Time_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_02_00_Time_startMouseClicked
        /*Date prev = theApp.GetLocalDate();
        
        String strDate = theApp.m_pMainWnd.m_pPanel.pnlStep1.lbl_01_00_Date_start.getText();
        String strTime = theApp.m_pMainWnd.m_pPanel.pnlStep1.lbl_01_00_Time_start.getText();
        
        SimpleDateFormat sdf = new SimpleDateFormat( "yyyy-MM-dd HH:mm");
        Date curr = theApp.GetLocalDate();
        try {
            curr = sdf.parse( strDate.substring( 3) + " " + strTime);
        } catch( ParseException ex) {
            logger.error( "ParseException caught!", ex);
        }
        ProcessHeaderDateTimeClick( 2, prev, curr);*/
        ProcessHeaderDateTimeClick( 2);
    }//GEN-LAST:event_lbl_02_00_Time_startMouseClicked

    private void lbl_02_01_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_02_01_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 21);
        }
    }//GEN-LAST:event_lbl_02_01_TitleMouseClicked

    private void lbl_02_02_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_02_02_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 22);
        }
    }//GEN-LAST:event_lbl_02_02_TitleMouseClicked

    private void lbl_02_03_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_02_03_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 23);
        }
    }//GEN-LAST:event_lbl_02_03_TitleMouseClicked

    private void lbl_02_04_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_02_04_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 24);
        }
    }//GEN-LAST:event_lbl_02_04_TitleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_02_01_Next;
    public javax.swing.JButton btn_02_01_Start;
    public javax.swing.JButton btn_02_02_Next;
    public javax.swing.JButton btn_02_02_Start;
    public javax.swing.JButton btn_02_03_Next;
    public javax.swing.JButton btn_02_03_Start;
    public javax.swing.JButton btn_02_04_Next;
    public javax.swing.JButton btn_02_04_Start;
    public javax.swing.JCheckBox chk_02_02_AutoStart;
    public javax.swing.JCheckBox chk_02_04_AutoStart;
    public javax.swing.JLabel lblAnimation_02_02;
    public javax.swing.JLabel lblAnimation_02_04;
    public javax.swing.JLabel lbl_02_00_Date_start;
    public javax.swing.JLabel lbl_02_00_Date_stop;
    public javax.swing.JLabel lbl_02_00_IcoStep;
    public javax.swing.JLabel lbl_02_00_Time_start;
    public javax.swing.JLabel lbl_02_00_Time_stop;
    public javax.swing.JLabel lbl_02_00_Title;
    public javax.swing.JLabel lbl_02_01_Date_start;
    public javax.swing.JLabel lbl_02_01_Date_stop;
    public javax.swing.JLabel lbl_02_01_IcoStep;
    public javax.swing.JLabel lbl_02_01_Time_start;
    public javax.swing.JLabel lbl_02_01_Time_stop;
    public javax.swing.JLabel lbl_02_01_Title;
    public javax.swing.JLabel lbl_02_02_Date_start;
    public javax.swing.JLabel lbl_02_02_Date_stop;
    public javax.swing.JLabel lbl_02_02_IcoStep;
    public javax.swing.JLabel lbl_02_02_Time_start;
    public javax.swing.JLabel lbl_02_02_Time_stop;
    public javax.swing.JLabel lbl_02_02_Title;
    public javax.swing.JLabel lbl_02_03_Date_start;
    public javax.swing.JLabel lbl_02_03_Date_stop;
    public javax.swing.JLabel lbl_02_03_IcoStep;
    public javax.swing.JLabel lbl_02_03_Time_start;
    public javax.swing.JLabel lbl_02_03_Time_stop;
    public javax.swing.JLabel lbl_02_03_Title;
    public javax.swing.JLabel lbl_02_04_Date_start;
    public javax.swing.JLabel lbl_02_04_Date_stop;
    public javax.swing.JLabel lbl_02_04_IcoStep;
    public javax.swing.JLabel lbl_02_04_Time_start;
    public javax.swing.JLabel lbl_02_04_Time_stop;
    public javax.swing.JLabel lbl_02_04_Title;
    // End of variables declaration//GEN-END:variables

}
