package obsolete;

import java.awt.event.MouseEvent;
import java.util.HashMap;
import javax.swing.JProgressBar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yaroslav
 */
public class TechProcessPanel3 extends javax.swing.JPanel {

    boolean [] m_bCollapses;
    TestDialog3 m_pParent;
    
    /**
     * Creates new form TechProcessPanel
     */
    public TechProcessPanel3( TestDialog3 pParent) {
        initComponents();
        
        m_pParent = pParent;
        
        m_bCollapses = new boolean [12];
        m_bCollapses[ 0] = true;
        m_bCollapses[ 1] = true;
        m_bCollapses[ 2] = true;
        m_bCollapses[ 3] = true;
        m_bCollapses[ 4] = true;
        m_bCollapses[ 5] = true;
        m_bCollapses[ 6] = true;
        m_bCollapses[ 7] = true;
        m_bCollapses[ 8] = true;
        m_bCollapses[ 9] = true;
        m_bCollapses[10] = true;
        m_bCollapses[11] = true;
        
        Reposition();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl01_00 = new javax.swing.JLabel();
        lbl02_00 = new javax.swing.JLabel();
        lbl02_01 = new javax.swing.JLabel();
        lbl02_02 = new javax.swing.JLabel();
        lbl02_03 = new javax.swing.JLabel();
        lbl02_04 = new javax.swing.JLabel();
        lbl03_00 = new javax.swing.JLabel();
        lbl03_01 = new javax.swing.JLabel();
        lbl03_02 = new javax.swing.JLabel();
        lbl03_03 = new javax.swing.JLabel();
        lbl03_04 = new javax.swing.JLabel();
        lbl03_05 = new javax.swing.JLabel();
        lbl03_06 = new javax.swing.JLabel();
        lbl04_00 = new javax.swing.JLabel();
        lbl04_01 = new javax.swing.JLabel();
        lbl04_05 = new javax.swing.JLabel();
        lbl04_02 = new javax.swing.JLabel();
        lbl04_03 = new javax.swing.JLabel();
        lbl04_04 = new javax.swing.JLabel();
        lbl04_06 = new javax.swing.JLabel();
        lbl05_00 = new javax.swing.JLabel();
        lbl05_01 = new javax.swing.JLabel();
        lbl05_02 = new javax.swing.JLabel();
        lbl05_03 = new javax.swing.JLabel();
        lbl05_04 = new javax.swing.JLabel();
        lbl05_05 = new javax.swing.JLabel();
        lbl06_00 = new javax.swing.JLabel();
        lbl06_01 = new javax.swing.JLabel();
        lbl06_02 = new javax.swing.JLabel();
        lbl06_03 = new javax.swing.JLabel();
        lbl06_04 = new javax.swing.JLabel();
        lbl07_00 = new javax.swing.JLabel();
        lbl07_01 = new javax.swing.JLabel();
        lbl07_02 = new javax.swing.JLabel();
        lbl07_03 = new javax.swing.JLabel();
        lbl07_04 = new javax.swing.JLabel();
        lbl07_05 = new javax.swing.JLabel();
        lbl07_06 = new javax.swing.JLabel();
        lbl07_07 = new javax.swing.JLabel();
        lbl07_08 = new javax.swing.JLabel();
        lbl07_09 = new javax.swing.JLabel();
        lbl07_10 = new javax.swing.JLabel();
        lbl08_00 = new javax.swing.JLabel();
        lbl08_01 = new javax.swing.JLabel();
        lbl08_02 = new javax.swing.JLabel();
        lbl08_03 = new javax.swing.JLabel();
        lbl09_00 = new javax.swing.JLabel();
        lbl09_01 = new javax.swing.JLabel();
        lbl09_02 = new javax.swing.JLabel();
        lbl09_03 = new javax.swing.JLabel();
        lbl09_04 = new javax.swing.JLabel();
        lbl09_05 = new javax.swing.JLabel();
        lbl09_06 = new javax.swing.JLabel();
        lbl10_00 = new javax.swing.JLabel();
        lbl10_01 = new javax.swing.JLabel();
        lbl10_02 = new javax.swing.JLabel();
        lbl10_03 = new javax.swing.JLabel();
        lbl11_00 = new javax.swing.JLabel();
        lbl11_01 = new javax.swing.JLabel();
        lbl11_02 = new javax.swing.JLabel();
        lbl11_03 = new javax.swing.JLabel();
        lbl11_04 = new javax.swing.JLabel();
        lbl12_00 = new javax.swing.JLabel();
        lbl12_01 = new javax.swing.JLabel();
        lbl12_02 = new javax.swing.JLabel();
        lbl12_03 = new javax.swing.JLabel();
        lbl12_04 = new javax.swing.JLabel();
        lbl12_05 = new javax.swing.JLabel();
        lblIcoStep02 = new javax.swing.JLabel();
        lblIcoStep03 = new javax.swing.JLabel();
        lblIcoStep04 = new javax.swing.JLabel();
        lblIcoStep05 = new javax.swing.JLabel();
        lblIcoStep06 = new javax.swing.JLabel();
        lblIcoStep07 = new javax.swing.JLabel();
        lblIcoStep08 = new javax.swing.JLabel();
        lblIcoStep09 = new javax.swing.JLabel();
        lblIcoStep10 = new javax.swing.JLabel();
        lblIcoStep11 = new javax.swing.JLabel();
        lblIcoStep12 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(400, 510));
        setMinimumSize(new java.awt.Dimension(400, 510));
        setPreferredSize(new java.awt.Dimension(400, 510));
        setLayout(null);

        lbl01_00.setText("1. Заполнение рабочей камеры азотом");
        lbl01_00.setBorder(null);
        add(lbl01_00);
        lbl01_00.setBounds(30, 0, 470, 25);

        lbl02_00.setText("2. Установка приборов");
        lbl02_00.setBorder(null);
        lbl02_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl02_00MouseClicked(evt);
            }
        });
        add(lbl02_00);
        lbl02_00.setBounds(30, 30, 470, 25);

        lbl02_01.setText("2.1 Занесение информации об установленных приборах");
        lbl02_01.setBorder(null);
        add(lbl02_01);
        lbl02_01.setBounds(60, 60, 440, 25);

        lbl02_02.setText("2.2 Предварительная откачка");
        lbl02_02.setBorder(null);
        add(lbl02_02);
        lbl02_02.setBounds(60, 90, 440, 25);

        lbl02_03.setText("2.3 Проверка герметичности установки приборов");
        lbl02_03.setBorder(null);
        add(lbl02_03);
        lbl02_03.setBounds(60, 120, 440, 25);

        lbl02_04.setText("2.4 Основная откачка");
        lbl02_04.setBorder(null);
        add(lbl02_04);
        lbl02_04.setBounds(60, 150, 440, 25);

        lbl03_00.setText("3. Обработка в среде кислорода");
        lbl03_00.setBorder(null);
        lbl03_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl03_00MouseClicked(evt);
            }
        });
        add(lbl03_00);
        lbl03_00.setBounds(30, 180, 470, 25);

        lbl03_01.setText("3.1 Напуск кислорода в приборы");
        lbl03_01.setBorder(null);
        add(lbl03_01);
        lbl03_01.setBounds(60, 210, 440, 25);

        lbl03_02.setText("3.2 Обработка. 1ый цикл");
        lbl03_02.setBorder(null);
        add(lbl03_02);
        lbl03_02.setBounds(60, 240, 440, 25);

        lbl03_03.setText("3.3 Откачка кислорода");
        lbl03_03.setBorder(null);
        add(lbl03_03);
        lbl03_03.setBounds(60, 270, 440, 25);

        lbl03_04.setText("3.4 Напуск кислорода в приборы");
        lbl03_04.setBorder(null);
        add(lbl03_04);
        lbl03_04.setBounds(60, 300, 440, 25);

        lbl03_05.setText("3.5 Обработка. 2ой цикл");
        lbl03_05.setBorder(null);
        add(lbl03_05);
        lbl03_05.setBounds(60, 330, 440, 25);

        lbl03_06.setText("3.6 Откачка кислорода");
        lbl03_06.setBorder(null);
        add(lbl03_06);
        lbl03_06.setBounds(60, 360, 440, 25);

        lbl04_00.setText("4. Обработка в среде кислород-неона");
        lbl04_00.setBorder(null);
        lbl04_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl04_00MouseClicked(evt);
            }
        });
        add(lbl04_00);
        lbl04_00.setBounds(30, 390, 470, 25);

        lbl04_01.setText("4.1 Напуск кислород-неона в приборы");
        lbl04_01.setBorder(null);
        add(lbl04_01);
        lbl04_01.setBounds(60, 420, 440, 25);

        lbl04_05.setText("4.5 Обработка. 2ой цикл");
        lbl04_05.setBorder(null);
        add(lbl04_05);
        lbl04_05.setBounds(60, 540, 440, 25);

        lbl04_02.setText("4.2 Обработка. 1ый цикл");
        lbl04_02.setBorder(null);
        add(lbl04_02);
        lbl04_02.setBounds(60, 450, 440, 25);

        lbl04_03.setText("4.3 Откачка газовой смеси");
        lbl04_03.setBorder(null);
        add(lbl04_03);
        lbl04_03.setBounds(60, 480, 440, 25);

        lbl04_04.setText("4.4 Напуск кислород-неона в приборы");
        lbl04_04.setBorder(null);
        add(lbl04_04);
        lbl04_04.setBounds(60, 510, 440, 25);

        lbl04_06.setText("4.6 Откачка газовой смеси");
        lbl04_06.setBorder(null);
        add(lbl04_06);
        lbl04_06.setBounds(60, 570, 440, 25);

        lbl05_00.setText("5. Термообезгаживание");
        lbl05_00.setBorder(null);
        lbl05_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl05_00MouseClicked(evt);
            }
        });
        add(lbl05_00);
        lbl05_00.setBounds(30, 600, 470, 25);

        lbl05_01.setText("5.1 Переход на основную откачку");
        lbl05_01.setBorder(null);
        add(lbl05_01);
        lbl05_01.setBounds(60, 630, 440, 25);

        lbl05_02.setText("5.2 Установка печек");
        lbl05_02.setBorder(null);
        add(lbl05_02);
        lbl05_02.setBounds(60, 660, 440, 25);

        lbl05_03.setText("5.3 Включение PID-регулирования печек");
        lbl05_03.setBorder(null);
        add(lbl05_03);
        lbl05_03.setBounds(60, 690, 440, 25);

        lbl05_04.setText("5.4 Снятие печек");
        lbl05_04.setBorder(null);
        add(lbl05_04);
        lbl05_04.setBounds(60, 720, 440, 25);

        lbl05_05.setText("5.5 Заполнение рабочей смесью");
        lbl05_05.setBorder(null);
        add(lbl05_05);
        lbl05_05.setBounds(60, 750, 440, 25);

        lbl06_00.setText("6. Предварительная оценка параметров приборов");
        lbl06_00.setBorder(null);
        lbl06_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl06_00MouseClicked(evt);
            }
        });
        add(lbl06_00);
        lbl06_00.setBounds(30, 780, 470, 25);

        lbl06_01.setText("6.1 Внесение комментариев");
        lbl06_01.setBorder(null);
        add(lbl06_01);
        lbl06_01.setBounds(60, 810, 440, 25);

        lbl06_02.setText("6.2 Внесение пороговых токов");
        lbl06_02.setBorder(null);
        add(lbl06_02);
        lbl06_02.setBounds(60, 840, 440, 25);

        lbl06_03.setText("6.3 Измерение ВАХ");
        lbl06_03.setBorder(null);
        add(lbl06_03);
        lbl06_03.setBounds(60, 870, 440, 25);

        lbl06_04.setText("6.4 Промежуточная оценка параметров (снятие не годных)");
        lbl06_04.setBorder(null);
        add(lbl06_04);
        lbl06_04.setBounds(60, 900, 440, 25);

        lbl07_00.setText("7. Тренировка катода");
        lbl07_00.setBorder(null);
        lbl07_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl07_00MouseClicked(evt);
            }
        });
        add(lbl07_00);
        lbl07_00.setBounds(30, 930, 470, 25);

        lbl07_01.setText("7.1 Откачка рабочей смеси");
        lbl07_01.setBorder(null);
        add(lbl07_01);
        lbl07_01.setBounds(60, 960, 440, 25);

        lbl07_02.setText("7.2 Напуск тренировочной смеси в приборы");
        lbl07_02.setBorder(null);
        add(lbl07_02);
        lbl07_02.setBounds(60, 990, 440, 25);

        lbl07_03.setText("7.3 Обработка. 1ый цикл");
        lbl07_03.setBorder(null);
        add(lbl07_03);
        lbl07_03.setBounds(60, 1020, 440, 25);

        lbl07_04.setText("7.4 Откачка тренировочной смеси");
        lbl07_04.setBorder(null);
        add(lbl07_04);
        lbl07_04.setBounds(60, 1050, 440, 25);

        lbl07_05.setText("7.5 Напуск тренировочной смеси в приборы");
        lbl07_05.setBorder(null);
        add(lbl07_05);
        lbl07_05.setBounds(60, 1080, 440, 25);

        lbl07_06.setText("7.6 Обработка. 2ой цикл");
        lbl07_06.setBorder(null);
        add(lbl07_06);
        lbl07_06.setBounds(60, 1110, 440, 25);

        lbl07_07.setText("7.7 Откачка тренировочной смеси");
        lbl07_07.setBorder(null);
        add(lbl07_07);
        lbl07_07.setBounds(60, 1140, 440, 25);

        lbl07_08.setText("7.8 Напуск тренировочной смеси в приборы");
        lbl07_08.setBorder(null);
        add(lbl07_08);
        lbl07_08.setBounds(60, 1170, 440, 25);

        lbl07_09.setText("7.9 Обработка. 3ий цикл");
        lbl07_09.setBorder(null);
        add(lbl07_09);
        lbl07_09.setBounds(60, 1200, 440, 25);

        lbl07_10.setText("7.10 Откачка тренировочной смеси");
        lbl07_10.setBorder(null);
        add(lbl07_10);
        lbl07_10.setBounds(60, 1230, 440, 25);

        lbl08_00.setText("8. Обезгаживание рабочих геттеров");
        lbl08_00.setBorder(null);
        lbl08_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl08_00MouseClicked(evt);
            }
        });
        add(lbl08_00);
        lbl08_00.setBounds(30, 1260, 470, 25);

        lbl08_01.setText("8.1 Переход на основную откачку");
        lbl08_01.setBorder(null);
        add(lbl08_01);
        lbl08_01.setBounds(60, 1290, 440, 25);

        lbl08_02.setText("8.2 Подготовка");
        lbl08_02.setBorder(null);
        add(lbl08_02);
        lbl08_02.setBounds(60, 1320, 440, 25);

        lbl08_03.setText("8.3 Обезгаживание");
        lbl08_03.setBorder(null);
        add(lbl08_03);
        lbl08_03.setBounds(60, 1350, 440, 25);

        lbl09_00.setText("9. Тренировка в тренировочной смеси");
        lbl09_00.setBorder(null);
        lbl09_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl09_00MouseClicked(evt);
            }
        });
        add(lbl09_00);
        lbl09_00.setBounds(30, 1380, 470, 25);

        lbl09_01.setText("9.1  Напуск тренировочной смеси в приборы");
        lbl09_01.setBorder(null);
        add(lbl09_01);
        lbl09_01.setBounds(60, 1410, 440, 25);

        lbl09_02.setText("9.2 Обработка. 1ый цикл");
        lbl09_02.setBorder(null);
        add(lbl09_02);
        lbl09_02.setBounds(60, 1440, 440, 25);

        lbl09_03.setText("9.3 Откачка тренировочной смеси");
        lbl09_03.setBorder(null);
        add(lbl09_03);
        lbl09_03.setBounds(60, 1470, 440, 25);

        lbl09_04.setText("9.4 Напуск тренировочной смеси в приборы");
        lbl09_04.setBorder(null);
        add(lbl09_04);
        lbl09_04.setBounds(60, 1500, 440, 25);

        lbl09_05.setText("9.5 Обработка. 2ой цикл");
        lbl09_05.setBorder(null);
        add(lbl09_05);
        lbl09_05.setBounds(60, 1530, 440, 25);

        lbl09_06.setText("9.6 Откачка тренировочной смеси");
        lbl09_06.setBorder(null);
        add(lbl09_06);
        lbl09_06.setBounds(60, 1560, 440, 25);

        lbl10_00.setText("10. Активация рабочих геттеров");
        lbl10_00.setBorder(null);
        lbl10_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl10_00MouseClicked(evt);
            }
        });
        add(lbl10_00);
        lbl10_00.setBounds(30, 1590, 470, 25);

        lbl10_01.setText("10.1 Переход на основную откачку");
        lbl10_01.setBorder(null);
        add(lbl10_01);
        lbl10_01.setBounds(60, 1620, 440, 25);

        lbl10_02.setText("10.2 Подготовка");
        lbl10_02.setBorder(null);
        lbl10_02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl10_02MouseClicked(evt);
            }
        });
        add(lbl10_02);
        lbl10_02.setBounds(60, 1650, 440, 25);

        lbl10_03.setText("10.3 Активация");
        lbl10_03.setBorder(null);
        add(lbl10_03);
        lbl10_03.setBounds(60, 1680, 440, 25);

        lbl11_00.setText("11. Выходная оценка параметров приборов");
        lbl11_00.setBorder(null);
        lbl11_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl11_00MouseClicked(evt);
            }
        });
        add(lbl11_00);
        lbl11_00.setBounds(30, 1710, 470, 25);

        lbl11_01.setText("11.1 Заполнение рабочей смесью");
        lbl11_01.setBorder(null);
        add(lbl11_01);
        lbl11_01.setBounds(60, 1740, 440, 25);

        lbl11_02.setText("11.2 Внесение пороговых токов");
        lbl11_02.setBorder(null);
        add(lbl11_02);
        lbl11_02.setBounds(60, 1770, 440, 25);

        lbl11_03.setText("11.3 Измерение ВАХ");
        lbl11_03.setBorder(null);
        add(lbl11_03);
        lbl11_03.setBounds(60, 1800, 440, 25);

        lbl11_04.setText("11.4 Герметизация годных приборов");
        lbl11_04.setBorder(null);
        add(lbl11_04);
        lbl11_04.setBounds(60, 1830, 440, 25);

        lbl12_00.setText("12. Снятие непрошедших приборов (опционально)");
        lbl12_00.setBorder(null);
        lbl12_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl12_00MouseClicked(evt);
            }
        });
        add(lbl12_00);
        lbl12_00.setBounds(30, 1860, 470, 25);

        lbl12_01.setText("12.1 Напуск азота в приборы");
        lbl12_01.setBorder(null);
        add(lbl12_01);
        lbl12_01.setBounds(60, 1890, 440, 25);

        lbl12_02.setText("12.2 Снятие непрошедших приборов");
        lbl12_02.setBorder(null);
        add(lbl12_02);
        lbl12_02.setBounds(60, 1920, 440, 25);

        lbl12_03.setText("12.3 Предварительная откачка");
        lbl12_03.setBorder(null);
        add(lbl12_03);
        lbl12_03.setBounds(60, 1950, 440, 25);

        lbl12_04.setText("12.4 Проверка герметичности (?? да  ?? нет)");
        lbl12_04.setBorder(null);
        add(lbl12_04);
        lbl12_04.setBounds(60, 1980, 440, 25);

        lbl12_05.setText("12.5 Основная откачка");
        lbl12_05.setBorder(null);
        add(lbl12_05);
        lbl12_05.setBounds(60, 2010, 440, 25);

        lblIcoStep02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoStep02MouseClicked(evt);
            }
        });
        add(lblIcoStep02);
        lblIcoStep02.setBounds(0, 30, 30, 25);

        lblIcoStep03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoStep03MouseClicked(evt);
            }
        });
        add(lblIcoStep03);
        lblIcoStep03.setBounds(0, 180, 30, 25);

        lblIcoStep04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoStep04MouseClicked(evt);
            }
        });
        add(lblIcoStep04);
        lblIcoStep04.setBounds(0, 390, 30, 25);

        lblIcoStep05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoStep05MouseClicked(evt);
            }
        });
        add(lblIcoStep05);
        lblIcoStep05.setBounds(0, 600, 30, 25);

        lblIcoStep06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoStep06MouseClicked(evt);
            }
        });
        add(lblIcoStep06);
        lblIcoStep06.setBounds(0, 780, 30, 25);

        lblIcoStep07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoStep07MouseClicked(evt);
            }
        });
        add(lblIcoStep07);
        lblIcoStep07.setBounds(0, 930, 30, 25);

        lblIcoStep08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoStep08MouseClicked(evt);
            }
        });
        add(lblIcoStep08);
        lblIcoStep08.setBounds(0, 1260, 30, 25);

        lblIcoStep09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoStep09MouseClicked(evt);
            }
        });
        add(lblIcoStep09);
        lblIcoStep09.setBounds(0, 1380, 30, 25);

        lblIcoStep10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoStep10MouseClicked(evt);
            }
        });
        add(lblIcoStep10);
        lblIcoStep10.setBounds(0, 1590, 30, 25);

        lblIcoStep11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoStep11MouseClicked(evt);
            }
        });
        add(lblIcoStep11);
        lblIcoStep11.setBounds(0, 1710, 30, 25);

        lblIcoStep12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIcoStep12MouseClicked(evt);
            }
        });
        add(lblIcoStep12);
        lblIcoStep12.setBounds(0, 1860, 30, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl02_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl02_00MouseClicked
        CollapseDeCollapse( 2);
    }//GEN-LAST:event_lbl02_00MouseClicked

    private void lbl03_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl03_00MouseClicked
        CollapseDeCollapse( 3);
    }//GEN-LAST:event_lbl03_00MouseClicked

    private void lbl04_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl04_00MouseClicked
        CollapseDeCollapse( 4);
    }//GEN-LAST:event_lbl04_00MouseClicked

    private void lbl05_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl05_00MouseClicked
        CollapseDeCollapse( 5);
    }//GEN-LAST:event_lbl05_00MouseClicked

    private void lbl06_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl06_00MouseClicked
        CollapseDeCollapse( 6);
    }//GEN-LAST:event_lbl06_00MouseClicked

    private void lbl07_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl07_00MouseClicked
        CollapseDeCollapse( 7);
    }//GEN-LAST:event_lbl07_00MouseClicked

    private void lbl08_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl08_00MouseClicked
        CollapseDeCollapse( 8);
    }//GEN-LAST:event_lbl08_00MouseClicked

    private void lbl09_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl09_00MouseClicked
        CollapseDeCollapse( 9);
    }//GEN-LAST:event_lbl09_00MouseClicked

    private void lbl10_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl10_00MouseClicked
        CollapseDeCollapse( 10);
    }//GEN-LAST:event_lbl10_00MouseClicked

    private void lbl11_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl11_00MouseClicked
        CollapseDeCollapse( 11);
    }//GEN-LAST:event_lbl11_00MouseClicked

    private void lbl12_00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl12_00MouseClicked
        CollapseDeCollapse( 12);
    }//GEN-LAST:event_lbl12_00MouseClicked

    private void lbl10_02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl10_02MouseClicked
        /*if( evt.getButton() == MouseEvent.BUTTON3) {
            nRightClickCnt++;
        }*/
    }//GEN-LAST:event_lbl10_02MouseClicked

    private void lblIcoStep02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoStep02MouseClicked
        CollapseDeCollapse( 2);
    }//GEN-LAST:event_lblIcoStep02MouseClicked

    private void lblIcoStep03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoStep03MouseClicked
        CollapseDeCollapse( 3);
    }//GEN-LAST:event_lblIcoStep03MouseClicked

    private void lblIcoStep04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoStep04MouseClicked
        CollapseDeCollapse( 4);
    }//GEN-LAST:event_lblIcoStep04MouseClicked

    private void lblIcoStep05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoStep05MouseClicked
        CollapseDeCollapse( 5);
    }//GEN-LAST:event_lblIcoStep05MouseClicked

    private void lblIcoStep06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoStep06MouseClicked
        CollapseDeCollapse( 6);
    }//GEN-LAST:event_lblIcoStep06MouseClicked

    private void lblIcoStep07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoStep07MouseClicked
        CollapseDeCollapse( 7);
    }//GEN-LAST:event_lblIcoStep07MouseClicked

    private void lblIcoStep08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoStep08MouseClicked
        CollapseDeCollapse( 8);
    }//GEN-LAST:event_lblIcoStep08MouseClicked

    private void lblIcoStep09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoStep09MouseClicked
        CollapseDeCollapse( 9);
    }//GEN-LAST:event_lblIcoStep09MouseClicked

    private void lblIcoStep10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoStep10MouseClicked
        CollapseDeCollapse( 10);
    }//GEN-LAST:event_lblIcoStep10MouseClicked

    private void lblIcoStep11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoStep11MouseClicked
        CollapseDeCollapse( 11);
    }//GEN-LAST:event_lblIcoStep11MouseClicked

    private void lblIcoStep12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIcoStep12MouseClicked
        CollapseDeCollapse( 12);
    }//GEN-LAST:event_lblIcoStep12MouseClicked

    public void CollapseDeCollapse( int nStep) {
        if( nStep >= 2 && nStep <= 12) {
            m_bCollapses[ nStep - 1] ^= true;
        }
        else {
            System.out.println( "Unknown Item");
            return;
        }
        Reposition();
    }
    
    public void Reposition() {
        int y = 0;

        int nScrlBar = 1650;
        
        
        //1. Заполнение рабочей камеры азотом
        lbl01_00.setLocation( 30, y);
        y += 30;
        
        
        //2. Установка приборов
        //2.1 Занесение информации об установленных приборах
        //2.2 Предварительная откачка
        //2.3 Проверка герметичности установки приборов ( ?? да   ?? нет)
        //2.4 Основная откачка
        lblIcoStep02.setLocation( 0, y);
        lbl02_00.setLocation( 30, y);
        y += 30;
        if( m_bCollapses[1] == true) {
            //collapsed
            lbl02_01.setVisible( false); nScrlBar -= 30;
            lbl02_02.setVisible( false); nScrlBar -= 30;
            lbl02_03.setVisible( false); nScrlBar -= 30;
            lbl02_04.setVisible( false); nScrlBar -= 30;
            lblIcoStep02.setIcon( m_pParent.m_icoRight);
        
        }
        else {
            //de-collapsed
            lbl02_01.setVisible( true); lbl02_01.setLocation( 60, y); y+= 30;
            lbl02_02.setVisible( true); lbl02_02.setLocation( 60, y); y+= 30;
            lbl02_03.setVisible( true); lbl02_03.setLocation( 60, y); y+= 30;
            lbl02_04.setVisible( true); lbl02_04.setLocation( 60, y); y+= 30;
            
            lblIcoStep02.setIcon( m_pParent.m_icoDown);
        }
        
        
        //3. Обработка в среде кислорода
        //3.1 Напуск кислорода в приборы
        //3.2 Обработка. 1ый цикл
        //3.3 Откачка кислорода
        //3.4 Напуск кислорода в приборы
        //3.5 Обработка. 2ой цикл
        //3.6 Откачка кислорода
        lblIcoStep03.setLocation( 0, y);
        lbl03_00.setLocation( 30, y);
        y += 30;
        if( m_bCollapses[2] == true) {
            //collapsed
            lbl03_01.setVisible( false); nScrlBar -= 30;
            lbl03_02.setVisible( false); nScrlBar -= 30;
            lbl03_03.setVisible( false); nScrlBar -= 30;
            lbl03_04.setVisible( false); nScrlBar -= 30;
            lbl03_05.setVisible( false); nScrlBar -= 30;
            lbl03_06.setVisible( false); nScrlBar -= 30;
            
            lblIcoStep03.setIcon( m_pParent.m_icoRight);
        }
        else {
            //de-collapsed
            lbl03_01.setVisible( true); lbl03_01.setLocation( 60, y); y+= 30;
            lbl03_02.setVisible( true); lbl03_02.setLocation( 60, y); y+= 30;
            lbl03_03.setVisible( true); lbl03_03.setLocation( 60, y); y+= 30;
            lbl03_04.setVisible( true); lbl03_04.setLocation( 60, y); y+= 30;
            lbl03_05.setVisible( true); lbl03_05.setLocation( 60, y); y+= 30;
            lbl03_06.setVisible( true); lbl03_06.setLocation( 60, y); y+= 30;
            
            lblIcoStep03.setIcon( m_pParent.m_icoDown);
        }
        
        
        //4. Обработка в среде кислород-неона.
        //4.1 Напуск кислород-неона в приборы
        //4.2 Обработка. 1ый цикл.
        //4.3 Откачка газовой смеси
        //4.4 Напуск кислород-неона в приборы
        //4.5 Обработка. 2ой цикл.
        //4.6 Откачка газовой смеси
        lblIcoStep04.setLocation( 0, y);
        lbl04_00.setLocation( 30, y);
        y += 30;
        if( m_bCollapses[3] == true) {
            //collapsed
            lbl04_01.setVisible( false); nScrlBar -= 30;
            lbl04_02.setVisible( false); nScrlBar -= 30;
            lbl04_03.setVisible( false); nScrlBar -= 30;
            lbl04_04.setVisible( false); nScrlBar -= 30;
            lbl04_05.setVisible( false); nScrlBar -= 30;
            lbl04_06.setVisible( false); nScrlBar -= 30;
            
            lblIcoStep04.setIcon( m_pParent.m_icoRight);
        }
        else {
            //de-collapsed
            lbl04_01.setVisible( true); lbl04_01.setLocation( 60, y); y+= 30;
            lbl04_02.setVisible( true); lbl04_02.setLocation( 60, y); y+= 30;
            lbl04_03.setVisible( true); lbl04_03.setLocation( 60, y); y+= 30;
            lbl04_04.setVisible( true); lbl04_04.setLocation( 60, y); y+= 30;
            lbl04_05.setVisible( true); lbl04_05.setLocation( 60, y); y+= 30;
            lbl04_06.setVisible( true); lbl04_06.setLocation( 60, y); y+= 30;
            
            lblIcoStep04.setIcon( m_pParent.m_icoDown);
        }
        
        
        //5. Термообезгаживание
        //5.1 Переход на основную откачку (2 и 1)
        //5.2 Установка печек
        //5.3 Включение PID-регулирования печек
        //5.4 Снятие печек
        //5.5 Заполнение рабочей смесью
        lblIcoStep05.setLocation( 0, y);
        lbl05_00.setLocation( 30, y);
        y += 30;
        if( m_bCollapses[4] == true) {
            //collapsed
            lbl05_01.setVisible( false); nScrlBar -= 30;
            lbl05_02.setVisible( false); nScrlBar -= 30;
            lbl05_03.setVisible( false); nScrlBar -= 30;
            lbl05_04.setVisible( false); nScrlBar -= 30;
            lbl05_05.setVisible( false); nScrlBar -= 30;
            lblIcoStep05.setIcon( m_pParent.m_icoRight);
        }
        else {
            //de-collapsed
            lbl05_01.setVisible( true); lbl05_01.setLocation( 60, y); y+= 30;
            lbl05_02.setVisible( true); lbl05_02.setLocation( 60, y); y+= 30;
            lbl05_03.setVisible( true); lbl05_03.setLocation( 60, y); y+= 30;
            lbl05_04.setVisible( true); lbl05_04.setLocation( 60, y); y+= 30;
            lbl05_05.setVisible( true); lbl05_05.setLocation( 60, y); y+= 30;
            lblIcoStep05.setIcon( m_pParent.m_icoDown);
        }
        
        
        //6. Предварительная оценка параметров приборов
        //6.1 Внесение комментариев
        //6.2 Внесение пороговых токов
        //6.3 Измерение ВАХ
        //6.4 Промежуточная оценка параметров (снятие не годных)
        lblIcoStep06.setLocation( 0, y);
        lbl06_00.setLocation( 30, y);
        y += 30;
        if( m_bCollapses[5] == true) {
            //collapsed
            lbl06_01.setVisible( false); nScrlBar -= 30;
            lbl06_02.setVisible( false); nScrlBar -= 30;
            lbl06_03.setVisible( false); nScrlBar -= 30;
            lbl06_04.setVisible( false); nScrlBar -= 30;
            lblIcoStep06.setIcon( m_pParent.m_icoRight);
        }
        else {
            //de-collapsed
            lbl06_01.setVisible( true); lbl06_01.setLocation( 60, y); y+= 30;
            lbl06_02.setVisible( true); lbl06_02.setLocation( 60, y); y+= 30;
            lbl06_03.setVisible( true); lbl06_03.setLocation( 60, y); y+= 30;
            lbl06_04.setVisible( true); lbl06_04.setLocation( 60, y); y+= 30;
            lblIcoStep06.setIcon( m_pParent.m_icoDown);
        }
        
        
        //7. Тренировка катода
        //7.1 Откачка рабочей смеси
        //7.2 Напуск тренировочной смеси в приборы
        //7.3 Обработка. 1ый цикл.
        //7.4 Откачка тренировочной смеси
        //7.5 Напуск тренировочной смеси в приборы
        //7.6 Обработка. 2ой цикл.
        //7.7 Откачка тренировочной смеси
        //7.8 Напуск тренировочной смеси в приборы
        //7.9 Обработка. 3ий цикл.
        //7.10 Откачка тренировочной смеси
        lblIcoStep07.setLocation( 0, y);
        lbl07_00.setLocation( 30, y);
        y += 30;
        if( m_bCollapses[6] == true) {
            //collapsed
            lbl07_01.setVisible( false); nScrlBar -= 30;
            lbl07_02.setVisible( false); nScrlBar -= 30;
            lbl07_03.setVisible( false); nScrlBar -= 30;
            lbl07_04.setVisible( false); nScrlBar -= 30;
            lbl07_05.setVisible( false); nScrlBar -= 30;
            lbl07_06.setVisible( false); nScrlBar -= 30;
            lbl07_07.setVisible( false); nScrlBar -= 30;
            lbl07_08.setVisible( false); nScrlBar -= 30;
            lbl07_09.setVisible( false); nScrlBar -= 30;
            lbl07_10.setVisible( false); nScrlBar -= 30;
            lblIcoStep07.setIcon( m_pParent.m_icoRight);
        }
        else {
            //de-collapsed
            lbl07_01.setVisible( true); lbl07_01.setLocation( 60, y); y+= 30;
            lbl07_02.setVisible( true); lbl07_02.setLocation( 60, y); y+= 30;
            lbl07_03.setVisible( true); lbl07_03.setLocation( 60, y); y+= 30;
            lbl07_04.setVisible( true); lbl07_04.setLocation( 60, y); y+= 30;
            lbl07_05.setVisible( true); lbl07_05.setLocation( 60, y); y+= 30;
            lbl07_06.setVisible( true); lbl07_06.setLocation( 60, y); y+= 30;
            lbl07_07.setVisible( true); lbl07_07.setLocation( 60, y); y+= 30;
            lbl07_08.setVisible( true); lbl07_08.setLocation( 60, y); y+= 30;
            lbl07_09.setVisible( true); lbl07_09.setLocation( 60, y); y+= 30;
            lbl07_10.setVisible( true); lbl07_10.setLocation( 60, y); y+= 30;
            lblIcoStep07.setIcon( m_pParent.m_icoDown);
        }
        
        
        //8. Обезгаживание рабочих геттеров
        //8.1 Переход на основную откачку
        //8.2 Подготовка
        //8.3 Обезгаживание
        lblIcoStep08.setLocation( 0, y);
        lbl08_00.setLocation( 30, y);
        y += 30;
        if( m_bCollapses[7] == true) {
            //collapsed
            lbl08_01.setVisible( false); nScrlBar -= 30;
            lbl08_02.setVisible( false); nScrlBar -= 30;
            lbl08_03.setVisible( false); nScrlBar -= 30;
            lblIcoStep08.setIcon( m_pParent.m_icoRight);
        }
        else {
            //de-collapsed
            lbl08_01.setVisible( true); lbl08_01.setLocation( 60, y); y+= 30;
            lbl08_02.setVisible( true); lbl08_02.setLocation( 60, y); y+= 30;
            lbl08_03.setVisible( true); lbl08_03.setLocation( 60, y); y+= 30;
            lblIcoStep08.setIcon( m_pParent.m_icoDown);
        }
        
        
        //9. Тренировка в тренировочной смеси
        //9.1  Напуск тренировочной смеси в приборы
        //9.2 Обработка. 1ый цикл.
        //9.3 Откачка тренировочной смеси
        //9.4 Напуск тренировочной смеси в приборы
        //9.5 Обработка. 2ой цикл.
        //9.6 Откачка тренировочной смеси
        lblIcoStep09.setLocation( 0, y);
        lbl09_00.setLocation( 30, y);
        y += 30;
        if( m_bCollapses[8] == true) {
            //collapsed
            lbl09_01.setVisible( false); nScrlBar -= 30;
            lbl09_02.setVisible( false); nScrlBar -= 30;
            lbl09_03.setVisible( false); nScrlBar -= 30;
            lbl09_04.setVisible( false); nScrlBar -= 30;
            lbl09_05.setVisible( false); nScrlBar -= 30;
            lbl09_06.setVisible( false); nScrlBar -= 30;
            lblIcoStep09.setIcon( m_pParent.m_icoRight);
        }
        else {
            //de-collapsed
            lbl09_01.setVisible( true); lbl09_01.setLocation( 60, y); y+= 30;
            lbl09_02.setVisible( true); lbl09_02.setLocation( 60, y); y+= 30;
            lbl09_03.setVisible( true); lbl09_03.setLocation( 60, y); y+= 30;
            lbl09_04.setVisible( true); lbl09_04.setLocation( 60, y); y+= 30;
            lbl09_05.setVisible( true); lbl09_05.setLocation( 60, y); y+= 30;
            lbl09_06.setVisible( true); lbl09_06.setLocation( 60, y); y+= 30;
            lblIcoStep09.setIcon( m_pParent.m_icoDown);
        }
        
        //10. Активация рабочих геттеров
        //10.1 Переход на основную откачку
        //10.2 Подготовка
        //10.3 Активация
        lblIcoStep10.setLocation( 0, y);
        lbl10_00.setLocation( 30, y);
        y += 30;
        if( m_bCollapses[9] == true) {
            //collapsed
            lbl10_01.setVisible( false); nScrlBar -= 30;
            lbl10_02.setVisible( false); nScrlBar -= 30;
            lbl10_03.setVisible( false); nScrlBar -= 30;
            lblIcoStep10.setIcon( m_pParent.m_icoRight);
        }
        else {
            //de-collapsed
            lbl10_01.setVisible( true); lbl10_01.setLocation( 60, y); y+= 30;
            lbl10_02.setVisible( true); lbl10_02.setLocation( 60, y); y+= 30;
            lbl10_03.setVisible( true); lbl10_03.setLocation( 60, y); y+= 30;
            lblIcoStep10.setIcon( m_pParent.m_icoDown);
        }
        
        
        //11. Выходная оценка параметров приборов
        //11.1 Заполнение рабочей смесью
        //11.2 Внесение пороговых токов
        //11.3 Измерение ВАХ
        //11.4 Герметизация годных приборов
        lblIcoStep11.setLocation( 0, y);
        lbl11_00.setLocation( 30, y);
        y += 30;
        if( m_bCollapses[10] == true) {
            //collapsed
            lbl11_01.setVisible( false); nScrlBar -= 30;
            lbl11_02.setVisible( false); nScrlBar -= 30;
            lbl11_03.setVisible( false); nScrlBar -= 30;
            lbl11_04.setVisible( false); nScrlBar -= 30;
            lblIcoStep11.setIcon( m_pParent.m_icoRight);
        }
        else {
            //de-collapsed
            lbl11_01.setVisible( true); lbl11_01.setLocation( 60, y); y+= 30;
            lbl11_02.setVisible( true); lbl11_02.setLocation( 60, y); y+= 30;
            lbl11_03.setVisible( true); lbl11_03.setLocation( 60, y); y+= 30;
            lbl11_04.setVisible( true); lbl11_04.setLocation( 60, y); y+= 30;
            lblIcoStep11.setIcon( m_pParent.m_icoDown);
        }
        
        
        //12. Снятие непрошедших приборов (опционально)
        //12.1 Напуск азота в приборы
        //12.2 Снятие непрошедших приборов
        //12.3 Предварительная откачка
        //12.4 Проверкагерметичности (?? да  ?? нет)
        //12.5 Основная откачка
        lblIcoStep12.setLocation( 0, y);
        lbl12_00.setLocation( 30, y);
        y += 30;
        if( m_bCollapses[11] == true) {
            //collapsed
            lbl12_01.setVisible( false); nScrlBar -= 30;
            lbl12_02.setVisible( false); nScrlBar -= 30;
            lbl12_03.setVisible( false); nScrlBar -= 30;
            lbl12_04.setVisible( false); nScrlBar -= 30;
            lbl12_05.setVisible( false); nScrlBar -= 30;
            lblIcoStep12.setIcon( m_pParent.m_icoRight);
        }
        else {
            //de-collapsed
            lbl12_01.setVisible( true); lbl12_01.setLocation( 60, y); y+= 30;
            lbl12_02.setVisible( true); lbl12_02.setLocation( 60, y); y+= 30;
            lbl12_03.setVisible( true); lbl12_03.setLocation( 60, y); y+= 30;
            lbl12_04.setVisible( true); lbl12_04.setLocation( 60, y); y+= 30;
            lbl12_05.setVisible( true); lbl12_05.setLocation( 60, y); y+= 30;
            lblIcoStep12.setIcon( m_pParent.m_icoDown);
        } 
         
        if( nScrlBar <= 5) {
            m_pParent.jScrollBar1.setEnabled( false);
            m_pParent.jScrollBar1.setVisible( false);
            m_pParent.jScrollBar1.setValue( 0);
            //m_pParent.m_pPanel.
                    setBounds( 2, 2, 500, 400);
        }
        else {
            m_pParent.jScrollBar1.setEnabled( true);
            m_pParent.jScrollBar1.setVisible( true);
            m_pParent.jScrollBar1.setMaximum( nScrlBar);
        }
        System.out.println( "" + y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl01_00;
    private javax.swing.JLabel lbl02_00;
    private javax.swing.JLabel lbl02_01;
    private javax.swing.JLabel lbl02_02;
    private javax.swing.JLabel lbl02_03;
    private javax.swing.JLabel lbl02_04;
    private javax.swing.JLabel lbl03_00;
    private javax.swing.JLabel lbl03_01;
    private javax.swing.JLabel lbl03_02;
    private javax.swing.JLabel lbl03_03;
    private javax.swing.JLabel lbl03_04;
    private javax.swing.JLabel lbl03_05;
    private javax.swing.JLabel lbl03_06;
    private javax.swing.JLabel lbl04_00;
    private javax.swing.JLabel lbl04_01;
    private javax.swing.JLabel lbl04_02;
    private javax.swing.JLabel lbl04_03;
    private javax.swing.JLabel lbl04_04;
    private javax.swing.JLabel lbl04_05;
    private javax.swing.JLabel lbl04_06;
    private javax.swing.JLabel lbl05_00;
    private javax.swing.JLabel lbl05_01;
    private javax.swing.JLabel lbl05_02;
    private javax.swing.JLabel lbl05_03;
    private javax.swing.JLabel lbl05_04;
    private javax.swing.JLabel lbl05_05;
    private javax.swing.JLabel lbl06_00;
    private javax.swing.JLabel lbl06_01;
    private javax.swing.JLabel lbl06_02;
    private javax.swing.JLabel lbl06_03;
    private javax.swing.JLabel lbl06_04;
    private javax.swing.JLabel lbl07_00;
    private javax.swing.JLabel lbl07_01;
    private javax.swing.JLabel lbl07_02;
    private javax.swing.JLabel lbl07_03;
    private javax.swing.JLabel lbl07_04;
    private javax.swing.JLabel lbl07_05;
    private javax.swing.JLabel lbl07_06;
    private javax.swing.JLabel lbl07_07;
    private javax.swing.JLabel lbl07_08;
    private javax.swing.JLabel lbl07_09;
    private javax.swing.JLabel lbl07_10;
    private javax.swing.JLabel lbl08_00;
    private javax.swing.JLabel lbl08_01;
    private javax.swing.JLabel lbl08_02;
    private javax.swing.JLabel lbl08_03;
    private javax.swing.JLabel lbl09_00;
    private javax.swing.JLabel lbl09_01;
    private javax.swing.JLabel lbl09_02;
    private javax.swing.JLabel lbl09_03;
    private javax.swing.JLabel lbl09_04;
    private javax.swing.JLabel lbl09_05;
    private javax.swing.JLabel lbl09_06;
    private javax.swing.JLabel lbl10_00;
    private javax.swing.JLabel lbl10_01;
    private javax.swing.JLabel lbl10_02;
    private javax.swing.JLabel lbl10_03;
    private javax.swing.JLabel lbl11_00;
    private javax.swing.JLabel lbl11_01;
    private javax.swing.JLabel lbl11_02;
    private javax.swing.JLabel lbl11_03;
    private javax.swing.JLabel lbl11_04;
    private javax.swing.JLabel lbl12_00;
    private javax.swing.JLabel lbl12_01;
    private javax.swing.JLabel lbl12_02;
    private javax.swing.JLabel lbl12_03;
    private javax.swing.JLabel lbl12_04;
    private javax.swing.JLabel lbl12_05;
    private javax.swing.JLabel lblIcoStep02;
    private javax.swing.JLabel lblIcoStep03;
    private javax.swing.JLabel lblIcoStep04;
    private javax.swing.JLabel lblIcoStep05;
    private javax.swing.JLabel lblIcoStep06;
    private javax.swing.JLabel lblIcoStep07;
    private javax.swing.JLabel lblIcoStep08;
    private javax.swing.JLabel lblIcoStep09;
    private javax.swing.JLabel lblIcoStep10;
    private javax.swing.JLabel lblIcoStep11;
    private javax.swing.JLabel lblIcoStep12;
    // End of variables declaration//GEN-END:variables
}