package obsolete;

import hvv_admin.dialogs.step01.TechProcessStep01Panel;
import hvv_admin.HVV_Admin;
import java.awt.Color;
import org.apache.log4j.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yaroslav
 */
public class TechProcessStep08_2_Dlg_1 extends javax.swing.JDialog {

    static Logger logger = Logger.getLogger( TechProcessStep08_2_Dlg_1.class);
    final private HVV_Admin theApp;
    /**
     * Creates new form TechProcessStep2_1_Dlg
     */
    public TechProcessStep08_2_Dlg_1( HVV_Admin app, java.awt.Frame parent, boolean modal) {
        super( parent, modal);
        theApp = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrGet1 = new javax.swing.ButtonGroup();
        btnGrGet2 = new javax.swing.ButtonGroup();
        btnGrGet3 = new javax.swing.ButtonGroup();
        btnGrGet4 = new javax.swing.ButtonGroup();
        btnGrGet5 = new javax.swing.ButtonGroup();
        btnGrGet6 = new javax.swing.ButtonGroup();
        btnGrGet7 = new javax.swing.ButtonGroup();
        btnGrGet8 = new javax.swing.ButtonGroup();
        lblPlace1 = new javax.swing.JLabel();
        lblPlace2 = new javax.swing.JLabel();
        lblPlace3 = new javax.swing.JLabel();
        lblPlace4 = new javax.swing.JLabel();
        lblPlace5 = new javax.swing.JLabel();
        lblPlace6 = new javax.swing.JLabel();
        lblPlace7 = new javax.swing.JLabel();
        lblPlace8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("2.3 Проверка герметичности установки приборов");
        setMinimumSize(new java.awt.Dimension(640, 400));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        getContentPane().setLayout(null);

        lblPlace1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblPlace1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlace1.setText("1");
        lblPlace1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        getContentPane().add(lblPlace1);
        lblPlace1.setBounds(290, 70, 40, 40);

        lblPlace2.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblPlace2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlace2.setText("8");
        lblPlace2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        getContentPane().add(lblPlace2);
        lblPlace2.setBounds(220, 110, 40, 40);

        lblPlace3.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblPlace3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlace3.setText("2");
        lblPlace3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        getContentPane().add(lblPlace3);
        lblPlace3.setBounds(370, 110, 40, 40);

        lblPlace4.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblPlace4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlace4.setText("3");
        lblPlace4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        getContentPane().add(lblPlace4);
        lblPlace4.setBounds(410, 190, 40, 40);

        lblPlace5.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblPlace5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlace5.setText("4");
        lblPlace5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        getContentPane().add(lblPlace5);
        lblPlace5.setBounds(370, 260, 40, 40);

        lblPlace6.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblPlace6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlace6.setText("5");
        lblPlace6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        getContentPane().add(lblPlace6);
        lblPlace6.setBounds(290, 310, 40, 40);

        lblPlace7.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblPlace7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlace7.setText("6");
        lblPlace7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        getContentPane().add(lblPlace7);
        lblPlace7.setBounds(220, 260, 40, 40);

        lblPlace8.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblPlace8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlace8.setText("7");
        lblPlace8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        getContentPane().add(lblPlace8);
        lblPlace8.setBounds(170, 190, 40, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep08_2_Dlg_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep08_2_Dlg_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep08_2_Dlg_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TechProcessStep08_2_Dlg_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TechProcessStep08_2_Dlg_1 dialog = new TechProcessStep08_2_Dlg_1( null, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrGet1;
    private javax.swing.ButtonGroup btnGrGet2;
    private javax.swing.ButtonGroup btnGrGet3;
    private javax.swing.ButtonGroup btnGrGet4;
    private javax.swing.ButtonGroup btnGrGet5;
    private javax.swing.ButtonGroup btnGrGet6;
    private javax.swing.ButtonGroup btnGrGet7;
    private javax.swing.ButtonGroup btnGrGet8;
    private javax.swing.JLabel lblPlace1;
    private javax.swing.JLabel lblPlace2;
    private javax.swing.JLabel lblPlace3;
    private javax.swing.JLabel lblPlace4;
    private javax.swing.JLabel lblPlace5;
    private javax.swing.JLabel lblPlace6;
    private javax.swing.JLabel lblPlace7;
    private javax.swing.JLabel lblPlace8;
    // End of variables declaration//GEN-END:variables
}
