/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin.dialogs.step03;

import hvv_admin.HVV_Admin;
import hvv_admin.dialogs.TechProcessStepPanelTemplate;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class TechProcessStep03Panel extends TechProcessStepPanelTemplate {
    public final int MAXIMIZED_HEIGHT = 210;
    static Logger logger = Logger.getLogger(TechProcessStep03Panel.class);
    
    /**
     * Creates new form TechProcessStep1Panel
     */
    public TechProcessStep03Panel( HVV_Admin app, boolean bCollapsed) {
        initComponents();
        theApp = app;
        m_bCollapsed = bCollapsed;
        m_nPageNumber = 2;
        m_bFirstOfDoubleClickHeaderDateTime = false;
        
        String strTitle = theApp.GetStepName( 40);
        if( strTitle != null) lbl_03_00_Title.setText( "3. " + strTitle);
        strTitle = theApp.GetStepName( 41);
        if( strTitle != null) lbl_03_01_Title.setText( "3.1 " + strTitle);
        strTitle = theApp.GetStepName( 42);
        if( strTitle != null) lbl_03_02_Title.setText( "3.2 " + strTitle);
        strTitle = theApp.GetStepName( 43);
        if( strTitle != null) lbl_03_03_Title.setText( "3.3 " + strTitle);
        strTitle = theApp.GetStepName( 44);
        if( strTitle != null) lbl_03_04_Title.setText( "3.4 " + strTitle);
        strTitle = theApp.GetStepName( 45);
        if( strTitle != null) lbl_03_05_Title.setText( "3.5 " + strTitle);
        strTitle = theApp.GetStepName( 46);
        if( strTitle != null) lbl_03_06_Title.setText( "3.6 " + strTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_03_00_Date_start = new javax.swing.JLabel();
        lbl_03_00_Time_start = new javax.swing.JLabel();
        lbl_03_00_IcoStep = new javax.swing.JLabel();
        lbl_03_00_Title = new javax.swing.JLabel();
        lbl_03_00_Date_stop = new javax.swing.JLabel();
        lbl_03_00_Time_stop = new javax.swing.JLabel();
        lbl_03_01_Date_start = new javax.swing.JLabel();
        lbl_03_01_Time_start = new javax.swing.JLabel();
        lblAnimation_03_01 = new javax.swing.JLabel();
        lbl_03_01_Title = new javax.swing.JLabel();
        chk_03_01_AutoStart = new javax.swing.JCheckBox();
        lbl_03_01_IcoStep = new javax.swing.JLabel();
        btn_03_01_Next = new javax.swing.JButton();
        lbl_03_01_Date_stop = new javax.swing.JLabel();
        lbl_03_01_Time_stop = new javax.swing.JLabel();
        lbl_03_02_Date_start = new javax.swing.JLabel();
        lbl_03_02_Time_start = new javax.swing.JLabel();
        lblAnimation_03_02 = new javax.swing.JLabel();
        lbl_03_02_Title = new javax.swing.JLabel();
        chk_03_02_AutoStart = new javax.swing.JCheckBox();
        lbl_03_02_IcoStep = new javax.swing.JLabel();
        btn_03_02_Next = new javax.swing.JButton();
        lbl_03_02_Date_stop = new javax.swing.JLabel();
        lbl_03_02_Time_stop = new javax.swing.JLabel();
        lbl_03_03_Date_start = new javax.swing.JLabel();
        lbl_03_03_Time_start = new javax.swing.JLabel();
        lblAnimation_03_03 = new javax.swing.JLabel();
        lbl_03_03_Title = new javax.swing.JLabel();
        chk_03_03_AutoStart = new javax.swing.JCheckBox();
        lbl_03_03_IcoStep = new javax.swing.JLabel();
        btn_03_03_Next = new javax.swing.JButton();
        lbl_03_03_Date_stop = new javax.swing.JLabel();
        lbl_03_03_Time_stop = new javax.swing.JLabel();
        lbl_03_04_Date_start = new javax.swing.JLabel();
        lbl_03_04_Time_start = new javax.swing.JLabel();
        lblAnimation_03_04 = new javax.swing.JLabel();
        lbl_03_04_Title = new javax.swing.JLabel();
        chk_03_04_AutoStart = new javax.swing.JCheckBox();
        lbl_03_04_IcoStep = new javax.swing.JLabel();
        btn_03_04_Next = new javax.swing.JButton();
        lbl_03_04_Date_stop = new javax.swing.JLabel();
        lbl_03_04_Time_stop = new javax.swing.JLabel();
        lbl_03_05_Date_start = new javax.swing.JLabel();
        lbl_03_05_Time_start = new javax.swing.JLabel();
        lblAnimation_03_05 = new javax.swing.JLabel();
        lbl_03_05_Title = new javax.swing.JLabel();
        chk_03_05_AutoStart = new javax.swing.JCheckBox();
        lbl_03_05_IcoStep = new javax.swing.JLabel();
        btn_03_05_Next = new javax.swing.JButton();
        lbl_03_05_Date_stop = new javax.swing.JLabel();
        lbl_03_05_Time_stop = new javax.swing.JLabel();
        lbl_03_06_Date_start = new javax.swing.JLabel();
        lbl_03_06_Time_start = new javax.swing.JLabel();
        lblAnimation_03_06 = new javax.swing.JLabel();
        lbl_03_06_Title = new javax.swing.JLabel();
        chk_03_06_AutoStart = new javax.swing.JCheckBox();
        lbl_03_06_IcoStep = new javax.swing.JLabel();
        btn_03_06_Next = new javax.swing.JButton();
        lbl_03_06_Date_stop = new javax.swing.JLabel();
        lbl_03_06_Time_stop = new javax.swing.JLabel();
        btn_03_01_Start = new javax.swing.JButton();
        btn_03_02_Start = new javax.swing.JButton();
        btn_03_03_Start = new javax.swing.JButton();
        btn_03_04_Start = new javax.swing.JButton();
        btn_03_05_Start = new javax.swing.JButton();
        btn_03_06_Start = new javax.swing.JButton();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1000, 210));
        setMinimumSize(new java.awt.Dimension(1000, 30));
        setLayout(null);

        lbl_03_00_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_00_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_00_Date_start.setText("-");
        lbl_03_00_Date_start.setBorder(null);
        lbl_03_00_Date_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_03_00_Date_startMouseClicked(evt);
            }
        });
        add(lbl_03_00_Date_start);
        lbl_03_00_Date_start.setBounds(0, 0, 90, 25);

        lbl_03_00_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_00_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_00_Time_start.setText("-");
        lbl_03_00_Time_start.setBorder(null);
        lbl_03_00_Time_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_03_00_Time_startMouseClicked(evt);
            }
        });
        add(lbl_03_00_Time_start);
        lbl_03_00_Time_start.setBounds(90, 0, 60, 25);

        lbl_03_00_IcoStep.setBorder(null);
        lbl_03_00_IcoStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_03_00_IcoStepMouseClicked(evt);
            }
        });
        add(lbl_03_00_IcoStep);
        lbl_03_00_IcoStep.setBounds(150, 0, 30, 25);

        lbl_03_00_Title.setText("3. Обработка в среде кислорода");
        lbl_03_00_Title.setBorder(null);
        lbl_03_00_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_03_00_TitleMouseClicked(evt);
            }
        });
        add(lbl_03_00_Title);
        lbl_03_00_Title.setBounds(180, 0, 470, 25);

        lbl_03_00_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_00_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_00_Date_stop.setText("-");
        lbl_03_00_Date_stop.setBorder(null);
        add(lbl_03_00_Date_stop);
        lbl_03_00_Date_stop.setBounds(840, 0, 90, 25);

        lbl_03_00_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_00_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_00_Time_stop.setText("-");
        lbl_03_00_Time_stop.setBorder(null);
        add(lbl_03_00_Time_stop);
        lbl_03_00_Time_stop.setBounds(930, 0, 60, 25);

        lbl_03_01_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_01_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_01_Date_start.setText("-");
        lbl_03_01_Date_start.setBorder(null);
        add(lbl_03_01_Date_start);
        lbl_03_01_Date_start.setBounds(0, 30, 90, 25);

        lbl_03_01_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_01_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_01_Time_start.setText("-");
        lbl_03_01_Time_start.setBorder(null);
        add(lbl_03_01_Time_start);
        lbl_03_01_Time_start.setBounds(90, 30, 60, 25);

        lblAnimation_03_01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_03_01);
        lblAnimation_03_01.setBounds(230, 30, 25, 25);

        lbl_03_01_Title.setText("3.1 Напуск кислорода в приборы");
        lbl_03_01_Title.setBorder(null);
        lbl_03_01_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_03_01_TitleMouseClicked(evt);
            }
        });
        add(lbl_03_01_Title);
        lbl_03_01_Title.setBounds(260, 30, 440, 25);

        chk_03_01_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_03_01_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_03_01_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_03_01_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_03_01_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_03_01_AutoStart);
        chk_03_01_AutoStart.setBounds(700, 30, 30, 30);

        lbl_03_01_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_01_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_03_01_IcoStep);
        lbl_03_01_IcoStep.setBounds(730, 30, 30, 25);

        btn_03_01_Next.setText("Далее");
        btn_03_01_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_01_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_01_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_01_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_01_NextActionPerformed(evt);
            }
        });
        add(btn_03_01_Next);
        btn_03_01_Next.setBounds(770, 30, 60, 30);

        lbl_03_01_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_01_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_01_Date_stop.setText("-");
        lbl_03_01_Date_stop.setBorder(null);
        add(lbl_03_01_Date_stop);
        lbl_03_01_Date_stop.setBounds(840, 30, 90, 25);

        lbl_03_01_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_01_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_01_Time_stop.setText("-");
        lbl_03_01_Time_stop.setBorder(null);
        add(lbl_03_01_Time_stop);
        lbl_03_01_Time_stop.setBounds(930, 30, 60, 25);

        lbl_03_02_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_02_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_02_Date_start.setText("-");
        lbl_03_02_Date_start.setBorder(null);
        add(lbl_03_02_Date_start);
        lbl_03_02_Date_start.setBounds(0, 60, 90, 25);

        lbl_03_02_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_02_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_02_Time_start.setText("-");
        lbl_03_02_Time_start.setBorder(null);
        add(lbl_03_02_Time_start);
        lbl_03_02_Time_start.setBounds(90, 60, 60, 25);

        lblAnimation_03_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_03_02);
        lblAnimation_03_02.setBounds(230, 60, 25, 25);

        lbl_03_02_Title.setText("3.2 Обработка. 1ый цикл");
        lbl_03_02_Title.setBorder(null);
        lbl_03_02_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_03_02_TitleMouseClicked(evt);
            }
        });
        add(lbl_03_02_Title);
        lbl_03_02_Title.setBounds(260, 60, 440, 25);

        chk_03_02_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_03_02_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_03_02_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_03_02_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_03_02_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_03_02_AutoStart);
        chk_03_02_AutoStart.setBounds(700, 60, 30, 30);

        lbl_03_02_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_02_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_03_02_IcoStep);
        lbl_03_02_IcoStep.setBounds(730, 60, 30, 25);

        btn_03_02_Next.setText("Далее");
        btn_03_02_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_02_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_02_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_02_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_02_NextActionPerformed(evt);
            }
        });
        add(btn_03_02_Next);
        btn_03_02_Next.setBounds(770, 60, 60, 30);

        lbl_03_02_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_02_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_02_Date_stop.setText("-");
        lbl_03_02_Date_stop.setBorder(null);
        add(lbl_03_02_Date_stop);
        lbl_03_02_Date_stop.setBounds(840, 60, 90, 25);

        lbl_03_02_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_02_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_02_Time_stop.setText("-");
        lbl_03_02_Time_stop.setBorder(null);
        add(lbl_03_02_Time_stop);
        lbl_03_02_Time_stop.setBounds(930, 60, 60, 25);

        lbl_03_03_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_03_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_03_Date_start.setText("-");
        lbl_03_03_Date_start.setBorder(null);
        add(lbl_03_03_Date_start);
        lbl_03_03_Date_start.setBounds(0, 90, 90, 25);

        lbl_03_03_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_03_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_03_Time_start.setText("-");
        lbl_03_03_Time_start.setBorder(null);
        add(lbl_03_03_Time_start);
        lbl_03_03_Time_start.setBounds(90, 90, 60, 25);

        lblAnimation_03_03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_03_03);
        lblAnimation_03_03.setBounds(230, 90, 25, 25);

        lbl_03_03_Title.setText("3.3 Откачка кислорода");
        lbl_03_03_Title.setBorder(null);
        lbl_03_03_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_03_03_TitleMouseClicked(evt);
            }
        });
        add(lbl_03_03_Title);
        lbl_03_03_Title.setBounds(260, 90, 440, 25);

        chk_03_03_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_03_03_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_03_03_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_03_03_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_03_03_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_03_03_AutoStart);
        chk_03_03_AutoStart.setBounds(700, 90, 30, 30);

        lbl_03_03_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_03_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_03_03_IcoStep);
        lbl_03_03_IcoStep.setBounds(730, 90, 30, 25);

        btn_03_03_Next.setText("Далее");
        btn_03_03_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_03_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_03_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_03_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_03_NextActionPerformed(evt);
            }
        });
        add(btn_03_03_Next);
        btn_03_03_Next.setBounds(770, 90, 60, 30);

        lbl_03_03_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_03_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_03_Date_stop.setText("-");
        lbl_03_03_Date_stop.setBorder(null);
        add(lbl_03_03_Date_stop);
        lbl_03_03_Date_stop.setBounds(840, 90, 90, 25);

        lbl_03_03_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_03_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_03_Time_stop.setText("-");
        lbl_03_03_Time_stop.setBorder(null);
        add(lbl_03_03_Time_stop);
        lbl_03_03_Time_stop.setBounds(930, 90, 60, 25);

        lbl_03_04_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_04_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_04_Date_start.setText("-");
        lbl_03_04_Date_start.setBorder(null);
        add(lbl_03_04_Date_start);
        lbl_03_04_Date_start.setBounds(0, 120, 90, 25);

        lbl_03_04_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_04_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_04_Time_start.setText("-");
        lbl_03_04_Time_start.setBorder(null);
        add(lbl_03_04_Time_start);
        lbl_03_04_Time_start.setBounds(90, 120, 60, 25);

        lblAnimation_03_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_03_04);
        lblAnimation_03_04.setBounds(230, 120, 25, 25);

        lbl_03_04_Title.setText("3.4 Напуск кислорода в приборы");
        lbl_03_04_Title.setBorder(null);
        lbl_03_04_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_03_04_TitleMouseClicked(evt);
            }
        });
        add(lbl_03_04_Title);
        lbl_03_04_Title.setBounds(260, 120, 440, 25);

        chk_03_04_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_03_04_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_03_04_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_03_04_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_03_04_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_03_04_AutoStart);
        chk_03_04_AutoStart.setBounds(700, 120, 30, 30);

        lbl_03_04_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_04_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_03_04_IcoStep);
        lbl_03_04_IcoStep.setBounds(730, 120, 30, 25);

        btn_03_04_Next.setText("Далее");
        btn_03_04_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_04_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_04_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_04_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_04_NextActionPerformed(evt);
            }
        });
        add(btn_03_04_Next);
        btn_03_04_Next.setBounds(770, 120, 60, 30);

        lbl_03_04_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_04_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_04_Date_stop.setText("-");
        lbl_03_04_Date_stop.setBorder(null);
        add(lbl_03_04_Date_stop);
        lbl_03_04_Date_stop.setBounds(840, 120, 90, 25);

        lbl_03_04_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_04_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_04_Time_stop.setText("-");
        lbl_03_04_Time_stop.setBorder(null);
        add(lbl_03_04_Time_stop);
        lbl_03_04_Time_stop.setBounds(930, 120, 60, 25);

        lbl_03_05_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_05_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_05_Date_start.setText("-");
        lbl_03_05_Date_start.setBorder(null);
        add(lbl_03_05_Date_start);
        lbl_03_05_Date_start.setBounds(0, 150, 90, 25);

        lbl_03_05_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_05_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_05_Time_start.setText("-");
        lbl_03_05_Time_start.setBorder(null);
        add(lbl_03_05_Time_start);
        lbl_03_05_Time_start.setBounds(90, 150, 60, 25);

        lblAnimation_03_05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_03_05);
        lblAnimation_03_05.setBounds(230, 150, 25, 25);

        lbl_03_05_Title.setText("3.5 Обработка. 2ой цикл");
        lbl_03_05_Title.setBorder(null);
        lbl_03_05_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_03_05_TitleMouseClicked(evt);
            }
        });
        add(lbl_03_05_Title);
        lbl_03_05_Title.setBounds(260, 150, 440, 25);

        chk_03_05_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_03_05_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_03_05_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_03_05_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_03_05_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_03_05_AutoStart);
        chk_03_05_AutoStart.setBounds(700, 150, 30, 30);

        lbl_03_05_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_05_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_03_05_IcoStep);
        lbl_03_05_IcoStep.setBounds(730, 150, 30, 25);

        btn_03_05_Next.setText("Далее");
        btn_03_05_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_05_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_05_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_05_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_05_NextActionPerformed(evt);
            }
        });
        add(btn_03_05_Next);
        btn_03_05_Next.setBounds(770, 150, 60, 30);

        lbl_03_05_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_05_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_05_Date_stop.setText("-");
        lbl_03_05_Date_stop.setBorder(null);
        add(lbl_03_05_Date_stop);
        lbl_03_05_Date_stop.setBounds(840, 150, 90, 25);

        lbl_03_05_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_05_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_05_Time_stop.setText("-");
        lbl_03_05_Time_stop.setBorder(null);
        add(lbl_03_05_Time_stop);
        lbl_03_05_Time_stop.setBounds(930, 150, 60, 25);

        lbl_03_06_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_06_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_06_Date_start.setText("-");
        lbl_03_06_Date_start.setBorder(null);
        add(lbl_03_06_Date_start);
        lbl_03_06_Date_start.setBounds(0, 180, 90, 25);

        lbl_03_06_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_06_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_06_Time_start.setText("-");
        lbl_03_06_Time_start.setBorder(null);
        add(lbl_03_06_Time_start);
        lbl_03_06_Time_start.setBounds(90, 180, 60, 25);

        lblAnimation_03_06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_03_06);
        lblAnimation_03_06.setBounds(230, 180, 25, 25);

        lbl_03_06_Title.setText("3.6 Откачка кислорода");
        lbl_03_06_Title.setBorder(null);
        lbl_03_06_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_03_06_TitleMouseClicked(evt);
            }
        });
        add(lbl_03_06_Title);
        lbl_03_06_Title.setBounds(260, 180, 440, 25);

        chk_03_06_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_03_06_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_03_06_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_03_06_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_03_06_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_03_06_AutoStart);
        chk_03_06_AutoStart.setBounds(700, 180, 30, 30);

        lbl_03_06_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_06_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_03_06_IcoStep);
        lbl_03_06_IcoStep.setBounds(730, 180, 30, 25);

        btn_03_06_Next.setText("Далее");
        btn_03_06_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_06_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_06_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_06_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_06_NextActionPerformed(evt);
            }
        });
        add(btn_03_06_Next);
        btn_03_06_Next.setBounds(770, 180, 60, 30);

        lbl_03_06_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_06_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_06_Date_stop.setText("-");
        lbl_03_06_Date_stop.setBorder(null);
        add(lbl_03_06_Date_stop);
        lbl_03_06_Date_stop.setBounds(840, 180, 90, 25);

        lbl_03_06_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_03_06_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_03_06_Time_stop.setText("-");
        lbl_03_06_Time_stop.setBorder(null);
        add(lbl_03_06_Time_stop);
        lbl_03_06_Time_stop.setBounds(930, 180, 60, 25);

        btn_03_01_Start.setText("Старт");
        btn_03_01_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_01_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_01_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_01_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_01_StartActionPerformed(evt);
            }
        });
        add(btn_03_01_Start);
        btn_03_01_Start.setBounds(160, 30, 60, 30);

        btn_03_02_Start.setText("Старт");
        btn_03_02_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_02_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_02_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_02_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_02_StartActionPerformed(evt);
            }
        });
        add(btn_03_02_Start);
        btn_03_02_Start.setBounds(160, 60, 60, 30);

        btn_03_03_Start.setText("Старт");
        btn_03_03_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_03_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_03_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_03_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_03_StartActionPerformed(evt);
            }
        });
        add(btn_03_03_Start);
        btn_03_03_Start.setBounds(160, 90, 60, 30);

        btn_03_04_Start.setText("Старт");
        btn_03_04_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_04_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_04_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_04_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_04_StartActionPerformed(evt);
            }
        });
        add(btn_03_04_Start);
        btn_03_04_Start.setBounds(160, 120, 60, 30);

        btn_03_05_Start.setText("Старт");
        btn_03_05_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_05_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_05_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_05_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_05_StartActionPerformed(evt);
            }
        });
        add(btn_03_05_Start);
        btn_03_05_Start.setBounds(160, 150, 60, 30);

        btn_03_06_Start.setText("Старт");
        btn_03_06_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_03_06_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_03_06_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_03_06_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03_06_StartActionPerformed(evt);
            }
        });
        add(btn_03_06_Start);
        btn_03_06_Start.setBounds(160, 180, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_03_00_IcoStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03_00_IcoStepMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_03_00_IcoStepMouseClicked

    private void lbl_03_00_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03_00_TitleMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_03_00_TitleMouseClicked
    
    public void SetState() {
        if( theApp.GetCurrentStep() / 20 == 2)
            m_bCollapsed = false;
        
        //3. Обработка в среде кислорода
        FillHeaderStepDates( "041", lbl_03_00_Date_start, lbl_03_00_Time_start, "046", lbl_03_00_Date_stop, lbl_03_00_Time_stop);
        
        lbl_03_00_IcoStep.setIcon( m_bCollapsed ? theApp.GetResources().getIconTriaRight() : theApp.GetResources().getIconTriaDown());
        
        lbl_03_00_Title.setFont( theApp.GetCurrentStep() / 20 == 2 ? theApp.GetBoldFont() : theApp.GetUsualFont());
        lbl_03_00_Title.setEnabled( theApp.GetCurrentStep() / 20 <= 2);
        
        
        if( m_bCollapsed == false) {
            //3.1 Напуск кислорода в приборы
            FillAutoExecutedSubStep(41, lbl_03_01_Date_start, lbl_03_01_Time_start, lblAnimation_03_01,
                                        btn_03_01_Start, lbl_03_01_Title, chk_03_01_AutoStart, lbl_03_01_IcoStep, btn_03_01_Next,
                                        lbl_03_01_Date_stop,lbl_03_01_Time_stop);
            
            //3.2 Обработка. 1ый цикл        
            FillAutoExecutedSubStep(42, lbl_03_02_Date_start, lbl_03_02_Time_start, lblAnimation_03_02, 
                                        btn_03_02_Start, lbl_03_02_Title, chk_03_02_AutoStart, lbl_03_02_IcoStep, btn_03_02_Next,
                                        lbl_03_02_Date_stop,lbl_03_02_Time_stop);
            
            //3.3 Откачка кислорода
            FillAutoExecutedSubStep(43, lbl_03_03_Date_start, lbl_03_03_Time_start, lblAnimation_03_03,
                                        btn_03_03_Start, lbl_03_03_Title, chk_03_03_AutoStart, lbl_03_03_IcoStep, btn_03_03_Next,
                                        lbl_03_03_Date_stop,lbl_03_03_Time_stop);
            
            //3.4 Напуск кислорода в приборы
            FillAutoExecutedSubStep(44, lbl_03_04_Date_start, lbl_03_04_Time_start, lblAnimation_03_04,
                                        btn_03_04_Start, lbl_03_04_Title, chk_03_04_AutoStart, lbl_03_04_IcoStep, btn_03_04_Next,
                                        lbl_03_04_Date_stop,lbl_03_04_Time_stop);
            
            //3.5 Обработка. 2ой цикл.
            FillAutoExecutedSubStep(45, lbl_03_05_Date_start, lbl_03_05_Time_start, lblAnimation_03_05,
                                        btn_03_05_Start, lbl_03_05_Title, chk_03_05_AutoStart, lbl_03_05_IcoStep, btn_03_05_Next,
                                        lbl_03_05_Date_stop,lbl_03_05_Time_stop);
            
            //3.6 Откачка кислорода
            FillAutoExecutedSubStep(46, lbl_03_06_Date_start, lbl_03_06_Time_start, lblAnimation_03_06,
                                        btn_03_06_Start, lbl_03_06_Title, chk_03_06_AutoStart, lbl_03_06_IcoStep, btn_03_06_Next,
                                        lbl_03_06_Date_stop,lbl_03_06_Time_stop);
        }
    }
    
    private void btn_03_01_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_01_NextActionPerformed
        DefaultNextButtonProcessing( "041", "Старт напуска кислорода", "Завершение напуска кислорода",
                                        "042", "Старт 1-го цикла обработки в кислороде", chk_03_02_AutoStart, logger, false);
    }//GEN-LAST:event_btn_03_01_NextActionPerformed

    private void btn_03_02_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_02_NextActionPerformed
        DefaultNextButtonProcessing( "042", "Старт 1-го цикла обработки в кислороде", "Завершение 1-го цикла обработки в кислороде",
                                        "043", "Старт откачки кислорода", chk_03_03_AutoStart, logger, false);
    }//GEN-LAST:event_btn_03_02_NextActionPerformed

    private void btn_03_03_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_03_NextActionPerformed
        DefaultNextButtonProcessing( "043", "Старт откачки кислорода", "Завершение откачки кислорода",
                                        "044", "Старт напуска кислорода", chk_03_04_AutoStart, logger, false);
    }//GEN-LAST:event_btn_03_03_NextActionPerformed

    private void btn_03_04_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_04_NextActionPerformed
        DefaultNextButtonProcessing( "044", "Старт напуска кислорода", "Завершение напуска кислорода",
                                        "045", "Старт 2-го цикла обработки в кислороде", chk_03_05_AutoStart, logger, false);
    }//GEN-LAST:event_btn_03_04_NextActionPerformed

    private void btn_03_05_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_05_NextActionPerformed
        DefaultNextButtonProcessing( "045", "Старт 2-го цикла обработки в кислороде", "Завершение 2-го цикла обработки в кислороде",
                                        "046", "Старт откачки кислорода", chk_03_06_AutoStart, logger, false);
    }//GEN-LAST:event_btn_03_05_NextActionPerformed

    private void btn_03_06_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_06_NextActionPerformed
        DefaultNextButtonProcessing( "046", "Старт откачки кислорода", "Завершение откачки кислорода",
                                        "061", "Старт напуска кислород-неона", theApp.m_pMainWnd.m_pPanel.pnlStep4.chk_04_01_AutoStart, logger, true);
    }//GEN-LAST:event_btn_03_06_NextActionPerformed

    private void btn_03_01_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_01_StartActionPerformed
        DefaultStartButtonProcessing( "041", "Старт напуска кислорода", "Завершение напуска кислорода",
                                        "042", "Старт 1-го цикла обработки в кислороде", chk_03_02_AutoStart, logger, false);
    }//GEN-LAST:event_btn_03_01_StartActionPerformed

    private void btn_03_02_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_02_StartActionPerformed
        DefaultStartButtonProcessing( "042", "Старт 1-го цикла обработки в кислороде", "Завершение 1-го цикла обработки в кислороде",
                                        "043", "Старт откачки кислорода", chk_03_03_AutoStart, logger, false);
    }//GEN-LAST:event_btn_03_02_StartActionPerformed

    private void btn_03_03_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_03_StartActionPerformed
        DefaultStartButtonProcessing( "043", "Старт откачки кислорода", "Завершение откачки кислорода",
                                        "044", "Старт напуска кислорода", chk_03_04_AutoStart, logger, false);
    }//GEN-LAST:event_btn_03_03_StartActionPerformed

    private void btn_03_04_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_04_StartActionPerformed
        DefaultStartButtonProcessing( "044", "Старт напуска кислорода", "Завершение напуска кислорода",
                                        "045", "Старт 2-го цикла обработки в кислороде", chk_03_05_AutoStart, logger, false);
    }//GEN-LAST:event_btn_03_04_StartActionPerformed

    private void btn_03_05_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_05_StartActionPerformed
        DefaultStartButtonProcessing( "045", "Старт 2-го цикла обработки в кислороде", "Завершение 2-го цикла обработки в кислороде",
                                        "046", "Старт откачки кислорода", chk_03_06_AutoStart, logger, false);
    }//GEN-LAST:event_btn_03_05_StartActionPerformed

    private void btn_03_06_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_03_06_StartActionPerformed
        DefaultStartButtonProcessing( "046", "Старт откачки кислорода", "Завершение откачки кислорода",
                                        "061", "Старт напуска кислород-неона", theApp.m_pMainWnd.m_pPanel.pnlStep4.chk_04_01_AutoStart, logger, true);
    }//GEN-LAST:event_btn_03_06_StartActionPerformed

    private void lbl_03_00_Date_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03_00_Date_startMouseClicked
        ProcessHeaderDateTimeClick( 3);
    }//GEN-LAST:event_lbl_03_00_Date_startMouseClicked

    private void lbl_03_00_Time_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03_00_Time_startMouseClicked
        ProcessHeaderDateTimeClick( 3);
    }//GEN-LAST:event_lbl_03_00_Time_startMouseClicked

    private void lbl_03_01_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03_01_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 41);
        }
    }//GEN-LAST:event_lbl_03_01_TitleMouseClicked

    private void lbl_03_02_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03_02_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 42);
        }
    }//GEN-LAST:event_lbl_03_02_TitleMouseClicked

    private void lbl_03_03_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03_03_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 43);
        }
    }//GEN-LAST:event_lbl_03_03_TitleMouseClicked

    private void lbl_03_04_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03_04_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 44);
        }
    }//GEN-LAST:event_lbl_03_04_TitleMouseClicked

    private void lbl_03_05_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03_05_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 45);
        }
    }//GEN-LAST:event_lbl_03_05_TitleMouseClicked

    private void lbl_03_06_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_03_06_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 46);
        }
    }//GEN-LAST:event_lbl_03_06_TitleMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_03_01_Next;
    public javax.swing.JButton btn_03_01_Start;
    public javax.swing.JButton btn_03_02_Next;
    public javax.swing.JButton btn_03_02_Start;
    public javax.swing.JButton btn_03_03_Next;
    public javax.swing.JButton btn_03_03_Start;
    public javax.swing.JButton btn_03_04_Next;
    public javax.swing.JButton btn_03_04_Start;
    public javax.swing.JButton btn_03_05_Next;
    public javax.swing.JButton btn_03_05_Start;
    public javax.swing.JButton btn_03_06_Next;
    public javax.swing.JButton btn_03_06_Start;
    public javax.swing.JCheckBox chk_03_01_AutoStart;
    public javax.swing.JCheckBox chk_03_02_AutoStart;
    public javax.swing.JCheckBox chk_03_03_AutoStart;
    public javax.swing.JCheckBox chk_03_04_AutoStart;
    public javax.swing.JCheckBox chk_03_05_AutoStart;
    public javax.swing.JCheckBox chk_03_06_AutoStart;
    public javax.swing.JLabel lblAnimation_03_01;
    public javax.swing.JLabel lblAnimation_03_02;
    public javax.swing.JLabel lblAnimation_03_03;
    public javax.swing.JLabel lblAnimation_03_04;
    public javax.swing.JLabel lblAnimation_03_05;
    public javax.swing.JLabel lblAnimation_03_06;
    public javax.swing.JLabel lbl_03_00_Date_start;
    public javax.swing.JLabel lbl_03_00_Date_stop;
    public javax.swing.JLabel lbl_03_00_IcoStep;
    public javax.swing.JLabel lbl_03_00_Time_start;
    public javax.swing.JLabel lbl_03_00_Time_stop;
    public javax.swing.JLabel lbl_03_00_Title;
    public javax.swing.JLabel lbl_03_01_Date_start;
    public javax.swing.JLabel lbl_03_01_Date_stop;
    public javax.swing.JLabel lbl_03_01_IcoStep;
    public javax.swing.JLabel lbl_03_01_Time_start;
    public javax.swing.JLabel lbl_03_01_Time_stop;
    public javax.swing.JLabel lbl_03_01_Title;
    public javax.swing.JLabel lbl_03_02_Date_start;
    public javax.swing.JLabel lbl_03_02_Date_stop;
    public javax.swing.JLabel lbl_03_02_IcoStep;
    public javax.swing.JLabel lbl_03_02_Time_start;
    public javax.swing.JLabel lbl_03_02_Time_stop;
    public javax.swing.JLabel lbl_03_02_Title;
    public javax.swing.JLabel lbl_03_03_Date_start;
    public javax.swing.JLabel lbl_03_03_Date_stop;
    public javax.swing.JLabel lbl_03_03_IcoStep;
    public javax.swing.JLabel lbl_03_03_Time_start;
    public javax.swing.JLabel lbl_03_03_Time_stop;
    public javax.swing.JLabel lbl_03_03_Title;
    public javax.swing.JLabel lbl_03_04_Date_start;
    public javax.swing.JLabel lbl_03_04_Date_stop;
    public javax.swing.JLabel lbl_03_04_IcoStep;
    public javax.swing.JLabel lbl_03_04_Time_start;
    public javax.swing.JLabel lbl_03_04_Time_stop;
    public javax.swing.JLabel lbl_03_04_Title;
    public javax.swing.JLabel lbl_03_05_Date_start;
    public javax.swing.JLabel lbl_03_05_Date_stop;
    public javax.swing.JLabel lbl_03_05_IcoStep;
    public javax.swing.JLabel lbl_03_05_Time_start;
    public javax.swing.JLabel lbl_03_05_Time_stop;
    public javax.swing.JLabel lbl_03_05_Title;
    public javax.swing.JLabel lbl_03_06_Date_start;
    public javax.swing.JLabel lbl_03_06_Date_stop;
    public javax.swing.JLabel lbl_03_06_IcoStep;
    public javax.swing.JLabel lbl_03_06_Time_start;
    public javax.swing.JLabel lbl_03_06_Time_stop;
    public javax.swing.JLabel lbl_03_06_Title;
    // End of variables declaration//GEN-END:variables
}
