/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin.dialogs.step06;

import hvv_admin.HVV_Admin;
import hvv_admin.dialogs.TechProcessStepPanelTemplate;
import java.awt.event.MouseEvent;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class TechProcessStep06Panel extends TechProcessStepPanelTemplate {
    public final int MAXIMIZED_HEIGHT = 150;
    static Logger logger = Logger.getLogger(TechProcessStep06Panel.class);
    
    /**
     * Creates new form TechProcessStep1Panel
     */
    public TechProcessStep06Panel( HVV_Admin app, boolean bCollapsed) {
        initComponents();
        theApp = app;
        m_bCollapsed = bCollapsed;
        m_nPageNumber = 5;
        m_bFirstOfDoubleClickHeaderDateTime = false;
        
        String strTitle = theApp.GetStepName( 100);
        if( strTitle != null) lbl_06_00_Title.setText( "6. " + strTitle);
        strTitle = theApp.GetStepName( 101);
        if( strTitle != null) lbl_06_01_Title.setText( "6.1 " + strTitle);
        strTitle = theApp.GetStepName( 102);
        if( strTitle != null) lbl_06_02_Title.setText( "6.2 " + strTitle);
        strTitle = theApp.GetStepName( 103);
        if( strTitle != null) lbl_06_03_Title.setText( "6.3 " + strTitle);
        strTitle = theApp.GetStepName( 104);
        if( strTitle != null) lbl_06_04_Title.setText( "6.4 " + strTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_06_00_Date_start = new javax.swing.JLabel();
        lbl_06_00_Time_start = new javax.swing.JLabel();
        lbl_06_00_IcoStep = new javax.swing.JLabel();
        lbl_06_00_Title = new javax.swing.JLabel();
        lbl_06_00_Date_stop = new javax.swing.JLabel();
        lbl_06_00_Time_stop = new javax.swing.JLabel();
        lbl_06_01_Date_start = new javax.swing.JLabel();
        lbl_06_01_Time_start = new javax.swing.JLabel();
        lblAnimation_06_01 = new javax.swing.JLabel();
        lbl_06_01_Title = new javax.swing.JLabel();
        lbl_06_01_IcoStep = new javax.swing.JLabel();
        btn_06_01_Next = new javax.swing.JButton();
        lbl_06_01_Date_stop = new javax.swing.JLabel();
        lbl_06_01_Time_stop = new javax.swing.JLabel();
        lbl_06_02_Date_start = new javax.swing.JLabel();
        lbl_06_02_Time_start = new javax.swing.JLabel();
        lblAnimation_06_02 = new javax.swing.JLabel();
        lbl_06_02_Title = new javax.swing.JLabel();
        lbl_06_02_IcoStep = new javax.swing.JLabel();
        btn_06_02_Next = new javax.swing.JButton();
        lbl_06_02_Date_stop = new javax.swing.JLabel();
        lbl_06_02_Time_stop = new javax.swing.JLabel();
        lbl_06_03_Date_start = new javax.swing.JLabel();
        lbl_06_03_Time_start = new javax.swing.JLabel();
        lblAnimation_06_03 = new javax.swing.JLabel();
        lbl_06_03_Title = new javax.swing.JLabel();
        lbl_06_03_IcoStep = new javax.swing.JLabel();
        btn_06_03_Next = new javax.swing.JButton();
        lbl_06_03_Date_stop = new javax.swing.JLabel();
        lbl_06_03_Time_stop = new javax.swing.JLabel();
        lbl_06_04_Date_start = new javax.swing.JLabel();
        lbl_06_04_Time_start = new javax.swing.JLabel();
        lblAnimation_06_04 = new javax.swing.JLabel();
        lbl_06_04_Title = new javax.swing.JLabel();
        chk_06_04_AutoStart = new javax.swing.JCheckBox();
        lbl_06_04_IcoStep = new javax.swing.JLabel();
        btn_06_04_Next = new javax.swing.JButton();
        lbl_06_04_Date_stop = new javax.swing.JLabel();
        lbl_06_04_Time_stop = new javax.swing.JLabel();
        btn_06_01_Start = new javax.swing.JButton();
        btn_06_02_Start = new javax.swing.JButton();
        btn_06_03_Start = new javax.swing.JButton();
        btn_06_04_Start = new javax.swing.JButton();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1000, 150));
        setMinimumSize(new java.awt.Dimension(1000, 30));
        setLayout(null);

        lbl_06_00_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_00_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_00_Date_start.setText("-");
        lbl_06_00_Date_start.setBorder(null);
        lbl_06_00_Date_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_06_00_Date_startMouseClicked(evt);
            }
        });
        add(lbl_06_00_Date_start);
        lbl_06_00_Date_start.setBounds(0, 0, 90, 25);

        lbl_06_00_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_00_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_00_Time_start.setText("-");
        lbl_06_00_Time_start.setBorder(null);
        lbl_06_00_Time_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_06_00_Time_startMouseClicked(evt);
            }
        });
        add(lbl_06_00_Time_start);
        lbl_06_00_Time_start.setBounds(90, 0, 60, 25);

        lbl_06_00_IcoStep.setBorder(null);
        lbl_06_00_IcoStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_06_00_IcoStepMouseClicked(evt);
            }
        });
        add(lbl_06_00_IcoStep);
        lbl_06_00_IcoStep.setBounds(150, 0, 30, 25);

        lbl_06_00_Title.setText("6. Предварительная оценка параметров приборов");
        lbl_06_00_Title.setBorder(null);
        lbl_06_00_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_06_00_TitleMouseClicked(evt);
            }
        });
        add(lbl_06_00_Title);
        lbl_06_00_Title.setBounds(180, 0, 470, 25);

        lbl_06_00_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_00_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_00_Date_stop.setText("-");
        lbl_06_00_Date_stop.setBorder(null);
        add(lbl_06_00_Date_stop);
        lbl_06_00_Date_stop.setBounds(840, 0, 90, 25);

        lbl_06_00_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_00_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_00_Time_stop.setText("-");
        lbl_06_00_Time_stop.setBorder(null);
        add(lbl_06_00_Time_stop);
        lbl_06_00_Time_stop.setBounds(930, 0, 60, 25);

        lbl_06_01_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_01_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_01_Date_start.setText("-");
        lbl_06_01_Date_start.setBorder(null);
        add(lbl_06_01_Date_start);
        lbl_06_01_Date_start.setBounds(0, 30, 90, 25);

        lbl_06_01_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_01_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_01_Time_start.setText("-");
        lbl_06_01_Time_start.setBorder(null);
        add(lbl_06_01_Time_start);
        lbl_06_01_Time_start.setBounds(90, 30, 60, 25);

        lblAnimation_06_01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_06_01);
        lblAnimation_06_01.setBounds(230, 30, 25, 25);

        lbl_06_01_Title.setText("6.1 Измерение ВАХ");
        lbl_06_01_Title.setBorder(null);
        lbl_06_01_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_06_01_TitleMouseClicked(evt);
            }
        });
        add(lbl_06_01_Title);
        lbl_06_01_Title.setBounds(260, 30, 440, 25);

        lbl_06_01_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_01_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_06_01_IcoStep);
        lbl_06_01_IcoStep.setBounds(730, 30, 30, 25);

        btn_06_01_Next.setText("Далее");
        btn_06_01_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_06_01_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_06_01_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_06_01_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_06_01_NextActionPerformed(evt);
            }
        });
        add(btn_06_01_Next);
        btn_06_01_Next.setBounds(770, 30, 60, 30);

        lbl_06_01_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_01_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_01_Date_stop.setText("-");
        lbl_06_01_Date_stop.setBorder(null);
        add(lbl_06_01_Date_stop);
        lbl_06_01_Date_stop.setBounds(840, 30, 90, 25);

        lbl_06_01_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_01_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_01_Time_stop.setText("-");
        lbl_06_01_Time_stop.setBorder(null);
        add(lbl_06_01_Time_stop);
        lbl_06_01_Time_stop.setBounds(930, 30, 60, 25);

        lbl_06_02_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_02_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_02_Date_start.setText("-");
        lbl_06_02_Date_start.setBorder(null);
        add(lbl_06_02_Date_start);
        lbl_06_02_Date_start.setBounds(0, 60, 90, 25);

        lbl_06_02_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_02_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_02_Time_start.setText("-");
        lbl_06_02_Time_start.setBorder(null);
        add(lbl_06_02_Time_start);
        lbl_06_02_Time_start.setBounds(90, 60, 60, 25);

        lblAnimation_06_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_06_02);
        lblAnimation_06_02.setBounds(230, 60, 25, 25);

        lbl_06_02_Title.setText("6.2 Измерение пороговых токов");
        lbl_06_02_Title.setBorder(null);
        lbl_06_02_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_06_02_TitleMouseClicked(evt);
            }
        });
        add(lbl_06_02_Title);
        lbl_06_02_Title.setBounds(260, 60, 440, 25);

        lbl_06_02_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_02_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_06_02_IcoStep);
        lbl_06_02_IcoStep.setBounds(730, 60, 30, 25);

        btn_06_02_Next.setText("Далее");
        btn_06_02_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_06_02_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_06_02_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_06_02_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_06_02_NextActionPerformed(evt);
            }
        });
        add(btn_06_02_Next);
        btn_06_02_Next.setBounds(770, 60, 60, 30);

        lbl_06_02_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_02_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_02_Date_stop.setText("-");
        lbl_06_02_Date_stop.setBorder(null);
        add(lbl_06_02_Date_stop);
        lbl_06_02_Date_stop.setBounds(840, 60, 90, 25);

        lbl_06_02_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_02_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_02_Time_stop.setText("-");
        lbl_06_02_Time_stop.setBorder(null);
        add(lbl_06_02_Time_stop);
        lbl_06_02_Time_stop.setBounds(930, 60, 60, 25);

        lbl_06_03_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_03_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_03_Date_start.setText("-");
        lbl_06_03_Date_start.setBorder(null);
        add(lbl_06_03_Date_start);
        lbl_06_03_Date_start.setBounds(0, 90, 90, 25);

        lbl_06_03_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_03_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_03_Time_start.setText("-");
        lbl_06_03_Time_start.setBorder(null);
        add(lbl_06_03_Time_start);
        lbl_06_03_Time_start.setBounds(90, 90, 60, 25);

        lblAnimation_06_03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_06_03);
        lblAnimation_06_03.setBounds(230, 90, 25, 25);

        lbl_06_03_Title.setText("6.3 Промежуточная оценка параметров");
        lbl_06_03_Title.setBorder(null);
        lbl_06_03_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_06_03_TitleMouseClicked(evt);
            }
        });
        add(lbl_06_03_Title);
        lbl_06_03_Title.setBounds(260, 90, 440, 25);

        lbl_06_03_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_03_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_06_03_IcoStep);
        lbl_06_03_IcoStep.setBounds(730, 90, 30, 25);

        btn_06_03_Next.setText("Далее");
        btn_06_03_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_06_03_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_06_03_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_06_03_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_06_03_NextActionPerformed(evt);
            }
        });
        add(btn_06_03_Next);
        btn_06_03_Next.setBounds(770, 90, 60, 30);

        lbl_06_03_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_03_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_03_Date_stop.setText("-");
        lbl_06_03_Date_stop.setBorder(null);
        add(lbl_06_03_Date_stop);
        lbl_06_03_Date_stop.setBounds(840, 90, 90, 25);

        lbl_06_03_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_03_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_03_Time_stop.setText("-");
        lbl_06_03_Time_stop.setBorder(null);
        add(lbl_06_03_Time_stop);
        lbl_06_03_Time_stop.setBounds(930, 90, 60, 25);

        lbl_06_04_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_04_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_04_Date_start.setText("-");
        lbl_06_04_Date_start.setBorder(null);
        add(lbl_06_04_Date_start);
        lbl_06_04_Date_start.setBounds(0, 120, 90, 25);

        lbl_06_04_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_04_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_04_Time_start.setText("-");
        lbl_06_04_Time_start.setBorder(null);
        add(lbl_06_04_Time_start);
        lbl_06_04_Time_start.setBounds(90, 120, 60, 25);

        lblAnimation_06_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_06_04);
        lblAnimation_06_04.setBounds(230, 120, 25, 25);

        lbl_06_04_Title.setText("6.4 Откачка рабочей смеси");
        lbl_06_04_Title.setBorder(null);
        lbl_06_04_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_06_04_TitleMouseClicked(evt);
            }
        });
        add(lbl_06_04_Title);
        lbl_06_04_Title.setBounds(260, 120, 440, 25);

        chk_06_04_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_06_04_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_06_04_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_06_04_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_06_04_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_06_04_AutoStart);
        chk_06_04_AutoStart.setBounds(700, 120, 30, 30);

        lbl_06_04_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_04_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_06_04_IcoStep);
        lbl_06_04_IcoStep.setBounds(730, 120, 30, 25);

        btn_06_04_Next.setText("Далее");
        btn_06_04_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_06_04_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_06_04_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_06_04_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_06_04_NextActionPerformed(evt);
            }
        });
        add(btn_06_04_Next);
        btn_06_04_Next.setBounds(770, 120, 60, 30);

        lbl_06_04_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_04_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_04_Date_stop.setText("-");
        lbl_06_04_Date_stop.setBorder(null);
        add(lbl_06_04_Date_stop);
        lbl_06_04_Date_stop.setBounds(840, 120, 90, 25);

        lbl_06_04_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_06_04_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_06_04_Time_stop.setText("-");
        lbl_06_04_Time_stop.setBorder(null);
        add(lbl_06_04_Time_stop);
        lbl_06_04_Time_stop.setBounds(930, 120, 60, 25);

        btn_06_01_Start.setText("Старт");
        btn_06_01_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_06_01_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_06_01_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_06_01_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_06_01_StartActionPerformed(evt);
            }
        });
        add(btn_06_01_Start);
        btn_06_01_Start.setBounds(160, 30, 60, 30);

        btn_06_02_Start.setText("Старт");
        btn_06_02_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_06_02_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_06_02_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_06_02_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_06_02_StartActionPerformed(evt);
            }
        });
        add(btn_06_02_Start);
        btn_06_02_Start.setBounds(160, 60, 60, 30);

        btn_06_03_Start.setText("Старт");
        btn_06_03_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_06_03_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_06_03_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_06_03_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_06_03_StartActionPerformed(evt);
            }
        });
        add(btn_06_03_Start);
        btn_06_03_Start.setBounds(160, 90, 60, 30);

        btn_06_04_Start.setText("Старт");
        btn_06_04_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_06_04_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_06_04_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_06_04_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_06_04_StartActionPerformed(evt);
            }
        });
        add(btn_06_04_Start);
        btn_06_04_Start.setBounds(160, 120, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_06_00_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_06_00_TitleMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_06_00_TitleMouseClicked

    private void lbl_06_00_IcoStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_06_00_IcoStepMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_06_00_IcoStepMouseClicked

    private void btn_06_01_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_06_01_NextActionPerformed
        //DefaultActionButtonProcessing( "101", "102", chk_06_01_AutoStart, logger, false);
    }//GEN-LAST:event_btn_06_01_NextActionPerformed

    private void btn_06_02_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_06_02_NextActionPerformed
        //DefaultActionButtonProcessing( "102", "103", chk_06_02_AutoStart, logger, false);
    }//GEN-LAST:event_btn_06_02_NextActionPerformed

    private void btn_06_03_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_06_03_NextActionPerformed
        //DefaultActionButtonProcessing( "103", "104", chk_06_03_AutoStart, logger, false);
    }//GEN-LAST:event_btn_06_03_NextActionPerformed

    private void btn_06_04_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_06_04_NextActionPerformed
        DefaultNextButtonProcessing( "104", "Старт откачки рабочей смеси", "Завершение откачки рабочей смеси",
                                        "121", "Старт напуска тренировочной смеси", theApp.m_pMainWnd.m_pPanel.pnlStep7.chk_07_01_AutoStart, logger, true);
    }//GEN-LAST:event_btn_06_04_NextActionPerformed

    private void btn_06_01_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_06_01_StartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_06_01_StartActionPerformed

    private void btn_06_02_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_06_02_StartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_06_02_StartActionPerformed

    private void btn_06_03_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_06_03_StartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_06_03_StartActionPerformed

    private void btn_06_04_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_06_04_StartActionPerformed
        DefaultStartButtonProcessing( "104", "Старт откачки рабочей смеси", "Завершение откачки рабочей смеси",
                                        "121", "Старт напуска тренировочной смеси", theApp.m_pMainWnd.m_pPanel.pnlStep7.chk_07_01_AutoStart, logger, true);
    }//GEN-LAST:event_btn_06_04_StartActionPerformed

    private void lbl_06_00_Date_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_06_00_Date_startMouseClicked
        ProcessHeaderDateTimeClick( 6);
    }//GEN-LAST:event_lbl_06_00_Date_startMouseClicked

    private void lbl_06_00_Time_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_06_00_Time_startMouseClicked
        ProcessHeaderDateTimeClick( 6);
    }//GEN-LAST:event_lbl_06_00_Time_startMouseClicked

    private void lbl_06_01_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_06_01_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 101);
        }
    }//GEN-LAST:event_lbl_06_01_TitleMouseClicked

    private void lbl_06_02_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_06_02_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 102);
        }
    }//GEN-LAST:event_lbl_06_02_TitleMouseClicked

    private void lbl_06_03_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_06_03_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 103);
        }
    }//GEN-LAST:event_lbl_06_03_TitleMouseClicked

    private void lbl_06_04_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_06_04_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 104);
        }
    }//GEN-LAST:event_lbl_06_04_TitleMouseClicked

    public void SetState() {
        if( theApp.GetCurrentStep() / 20 == m_nPageNumber)
            m_bCollapsed = false;
        
        //6. Предварительная оценка параметров приборов
        FillHeaderStepDates( "101", lbl_06_00_Date_start, lbl_06_00_Time_start, "104", lbl_06_00_Date_stop, lbl_06_00_Time_stop);
        
        lbl_06_00_IcoStep.setIcon( m_bCollapsed ? theApp.GetResources().getIconTriaRight() : theApp.GetResources().getIconTriaDown());
        
        lbl_06_00_Title.setFont( theApp.GetCurrentStep() / 20 == m_nPageNumber ? theApp.GetBoldFont() : theApp.GetUsualFont());
        lbl_06_00_Title.setEnabled( theApp.GetCurrentStep() / 20 <= m_nPageNumber);
        
        
        if( m_bCollapsed == false) {
            //6.1 Измерение ВАХ
            FillStepDates( "101", lbl_06_01_Date_start, lbl_06_01_Time_start, lbl_06_01_Date_stop, lbl_06_01_Time_stop);

            lbl_06_01_Title.setFont( theApp.GetCurrentStep() == 101 ? theApp.GetBoldFont() : theApp.GetUsualFont());
            lbl_06_01_Title.setEnabled( theApp.GetCurrentStep() <= 101);
            
            btn_06_01_Start.setVisible( false);
            btn_06_01_Next.setVisible( false);
            
            //6.2 Внесение пороговых токов
            FillStepDates( "102", lbl_06_02_Date_start, lbl_06_02_Time_start, lbl_06_02_Date_stop, lbl_06_02_Time_stop);

            lbl_06_02_Title.setFont( theApp.GetCurrentStep() == 102 ? theApp.GetBoldFont() : theApp.GetUsualFont());
            lbl_06_02_Title.setEnabled( theApp.GetCurrentStep() <= 102);
            
            btn_06_02_Start.setVisible( false);
            btn_06_02_Next.setVisible( false);
            
            // 6.3 Внесение комментариев
            FillStepDates( "103", lbl_06_03_Date_start, lbl_06_03_Time_start, lbl_06_03_Date_stop, lbl_06_03_Time_stop);

            lbl_06_03_Title.setFont( theApp.GetCurrentStep() == 103 ? theApp.GetBoldFont() : theApp.GetUsualFont());
            lbl_06_03_Title.setEnabled( theApp.GetCurrentStep() <= 103);
            
            btn_06_03_Start.setVisible( false);
            btn_06_03_Next.setVisible( false);
            
            // 6.4 Откачка рабочей смеси
            FillAutoExecutedSubStep(104,
                                    lbl_06_04_Date_start, lbl_06_04_Time_start, lblAnimation_06_04,
                                    btn_06_04_Start, lbl_06_04_Title, chk_06_04_AutoStart, lbl_06_04_IcoStep, btn_06_04_Next,
                                    lbl_06_04_Date_stop, lbl_06_04_Time_stop);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_06_01_Next;
    public javax.swing.JButton btn_06_01_Start;
    private javax.swing.JButton btn_06_02_Next;
    public javax.swing.JButton btn_06_02_Start;
    private javax.swing.JButton btn_06_03_Next;
    public javax.swing.JButton btn_06_03_Start;
    private javax.swing.JButton btn_06_04_Next;
    public javax.swing.JButton btn_06_04_Start;
    public javax.swing.JCheckBox chk_06_04_AutoStart;
    public javax.swing.JLabel lblAnimation_06_01;
    public javax.swing.JLabel lblAnimation_06_02;
    public javax.swing.JLabel lblAnimation_06_03;
    public javax.swing.JLabel lblAnimation_06_04;
    public javax.swing.JLabel lbl_06_00_Date_start;
    private javax.swing.JLabel lbl_06_00_Date_stop;
    private javax.swing.JLabel lbl_06_00_IcoStep;
    public javax.swing.JLabel lbl_06_00_Time_start;
    private javax.swing.JLabel lbl_06_00_Time_stop;
    private javax.swing.JLabel lbl_06_00_Title;
    private javax.swing.JLabel lbl_06_01_Date_start;
    private javax.swing.JLabel lbl_06_01_Date_stop;
    public javax.swing.JLabel lbl_06_01_IcoStep;
    private javax.swing.JLabel lbl_06_01_Time_start;
    private javax.swing.JLabel lbl_06_01_Time_stop;
    private javax.swing.JLabel lbl_06_01_Title;
    private javax.swing.JLabel lbl_06_02_Date_start;
    private javax.swing.JLabel lbl_06_02_Date_stop;
    public javax.swing.JLabel lbl_06_02_IcoStep;
    private javax.swing.JLabel lbl_06_02_Time_start;
    private javax.swing.JLabel lbl_06_02_Time_stop;
    private javax.swing.JLabel lbl_06_02_Title;
    private javax.swing.JLabel lbl_06_03_Date_start;
    private javax.swing.JLabel lbl_06_03_Date_stop;
    public javax.swing.JLabel lbl_06_03_IcoStep;
    private javax.swing.JLabel lbl_06_03_Time_start;
    private javax.swing.JLabel lbl_06_03_Time_stop;
    private javax.swing.JLabel lbl_06_03_Title;
    private javax.swing.JLabel lbl_06_04_Date_start;
    private javax.swing.JLabel lbl_06_04_Date_stop;
    public javax.swing.JLabel lbl_06_04_IcoStep;
    private javax.swing.JLabel lbl_06_04_Time_start;
    private javax.swing.JLabel lbl_06_04_Time_stop;
    private javax.swing.JLabel lbl_06_04_Title;
    // End of variables declaration//GEN-END:variables
}
