/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin.dialogs.step11;

import hvv_admin.HVV_Admin;
import hvv_admin.comm.executor.to.StartProgramExecutor;
import hvv_admin.dialogs.TechProcessStepPanelTemplate;
import hvv_admin.steps.info.TechProcessStepInfo;
import java.awt.event.MouseEvent;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class TechProcessStep11Panel extends TechProcessStepPanelTemplate {
    public final int MAXIMIZED_HEIGHT = 210;
    static Logger logger = Logger.getLogger(TechProcessStep11Panel.class);
    /**
     * Creates new form TechProcessStep1Panel
     */
    public TechProcessStep11Panel( HVV_Admin app, boolean bCollapsed) {
        initComponents();
        theApp = app;
        m_bCollapsed = bCollapsed;
        m_nPageNumber = 10;
        m_bFirstOfDoubleClickHeaderDateTime = false;
        
        String strTitle = theApp.GetStepName( 200);
        if( strTitle != null) lbl_11_00_Title.setText( "11. " + strTitle);
        strTitle = theApp.GetStepName( 201);
        if( strTitle != null) lbl_11_01_Title.setText( "11.1 " + strTitle);
        strTitle = theApp.GetStepName( 202);
        if( strTitle != null) lbl_11_02_Title.setText( "11.2 " + strTitle);
        strTitle = theApp.GetStepName( 203);
        if( strTitle != null) lbl_11_03_Title.setText( "11.3 " + strTitle);
        strTitle = theApp.GetStepName( 204);
        if( strTitle != null) lbl_11_04_Title.setText( "11.4 " + strTitle);
        strTitle = theApp.GetStepName( 205);
        if( strTitle != null) lbl_11_05_Title.setText( "11.5 " + strTitle);
        strTitle = theApp.GetStepName( 206);
        if( strTitle != null) lbl_11_06_Title.setText( "11.6 " + strTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_11_00_Date_start = new javax.swing.JLabel();
        lbl_11_00_Time_start = new javax.swing.JLabel();
        lbl_11_00_IcoStep = new javax.swing.JLabel();
        lbl_11_00_Title = new javax.swing.JLabel();
        lbl_11_00_Date_stop = new javax.swing.JLabel();
        lbl_11_00_Time_stop = new javax.swing.JLabel();
        lbl_11_01_Date_start = new javax.swing.JLabel();
        lbl_11_01_Time_start = new javax.swing.JLabel();
        lblAnimation_11_01 = new javax.swing.JLabel();
        lbl_11_01_Title = new javax.swing.JLabel();
        chk_11_01_AutoStart = new javax.swing.JCheckBox();
        lbl_11_01_IcoStep = new javax.swing.JLabel();
        btn_11_01_Next = new javax.swing.JButton();
        lbl_11_01_Date_stop = new javax.swing.JLabel();
        lbl_11_01_Time_stop = new javax.swing.JLabel();
        lbl_11_02_Date_start = new javax.swing.JLabel();
        lbl_11_02_Time_start = new javax.swing.JLabel();
        lblAnimation_11_02 = new javax.swing.JLabel();
        lbl_11_02_Title = new javax.swing.JLabel();
        chk_11_02_AutoStart = new javax.swing.JCheckBox();
        lbl_11_02_IcoStep = new javax.swing.JLabel();
        btn_11_02_Next = new javax.swing.JButton();
        lbl_11_02_Date_stop = new javax.swing.JLabel();
        lbl_11_02_Time_stop = new javax.swing.JLabel();
        lbl_11_03_Date_start = new javax.swing.JLabel();
        lbl_11_03_Time_start = new javax.swing.JLabel();
        lblAnimation_11_03 = new javax.swing.JLabel();
        lbl_11_03_Title = new javax.swing.JLabel();
        lbl_11_03_IcoStep = new javax.swing.JLabel();
        btn_11_03_Next = new javax.swing.JButton();
        lbl_11_03_Date_stop = new javax.swing.JLabel();
        lbl_11_03_Time_stop = new javax.swing.JLabel();
        lbl_11_04_Date_start = new javax.swing.JLabel();
        lbl_11_04_Time_start = new javax.swing.JLabel();
        lblAnimation_11_04 = new javax.swing.JLabel();
        lbl_11_04_Title = new javax.swing.JLabel();
        lbl_11_04_IcoStep = new javax.swing.JLabel();
        btn_11_04_Next = new javax.swing.JButton();
        lbl_11_04_Date_stop = new javax.swing.JLabel();
        lbl_11_04_Time_stop = new javax.swing.JLabel();
        lbl_11_05_Date_start = new javax.swing.JLabel();
        lbl_11_05_Time_start = new javax.swing.JLabel();
        lblAnimation_11_05 = new javax.swing.JLabel();
        lbl_11_05_Title = new javax.swing.JLabel();
        lbl_11_05_IcoStep = new javax.swing.JLabel();
        btn_11_05_Next = new javax.swing.JButton();
        lbl_11_05_Date_stop = new javax.swing.JLabel();
        lbl_11_05_Time_stop = new javax.swing.JLabel();
        lbl_11_06_Date_start = new javax.swing.JLabel();
        lbl_11_06_Time_start = new javax.swing.JLabel();
        lblAnimation_11_06 = new javax.swing.JLabel();
        lbl_11_06_Title = new javax.swing.JLabel();
        lbl_11_06_IcoStep = new javax.swing.JLabel();
        btn_11_06_Next = new javax.swing.JButton();
        lbl_11_06_Date_stop = new javax.swing.JLabel();
        lbl_11_06_Time_stop = new javax.swing.JLabel();
        btn_11_01_Start = new javax.swing.JButton();
        btn_11_02_Start = new javax.swing.JButton();
        btn_11_03_Start = new javax.swing.JButton();
        btn_11_04_Start = new javax.swing.JButton();
        btn_11_05_Start = new javax.swing.JButton();
        btn_11_06_Start = new javax.swing.JButton();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1000, 210));
        setMinimumSize(new java.awt.Dimension(1000, 30));
        setLayout(null);

        lbl_11_00_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_00_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_00_Date_start.setText("-");
        lbl_11_00_Date_start.setBorder(null);
        lbl_11_00_Date_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_11_00_Date_startMouseClicked(evt);
            }
        });
        add(lbl_11_00_Date_start);
        lbl_11_00_Date_start.setBounds(0, 0, 90, 25);

        lbl_11_00_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_00_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_00_Time_start.setText("-");
        lbl_11_00_Time_start.setBorder(null);
        lbl_11_00_Time_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_11_00_Time_startMouseClicked(evt);
            }
        });
        add(lbl_11_00_Time_start);
        lbl_11_00_Time_start.setBounds(90, 0, 60, 25);

        lbl_11_00_IcoStep.setBorder(null);
        lbl_11_00_IcoStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_11_00_IcoStepMouseClicked(evt);
            }
        });
        add(lbl_11_00_IcoStep);
        lbl_11_00_IcoStep.setBounds(150, 0, 30, 25);

        lbl_11_00_Title.setText("11. Выходная оценка параметров приборов");
        lbl_11_00_Title.setBorder(null);
        lbl_11_00_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_11_00_TitleMouseClicked(evt);
            }
        });
        add(lbl_11_00_Title);
        lbl_11_00_Title.setBounds(180, 0, 470, 25);

        lbl_11_00_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_00_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_00_Date_stop.setText("-");
        lbl_11_00_Date_stop.setBorder(null);
        add(lbl_11_00_Date_stop);
        lbl_11_00_Date_stop.setBounds(840, 0, 90, 25);

        lbl_11_00_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_00_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_00_Time_stop.setText("-");
        lbl_11_00_Time_stop.setBorder(null);
        add(lbl_11_00_Time_stop);
        lbl_11_00_Time_stop.setBounds(930, 0, 60, 25);

        lbl_11_01_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_01_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_01_Date_start.setText("-");
        lbl_11_01_Date_start.setBorder(null);
        add(lbl_11_01_Date_start);
        lbl_11_01_Date_start.setBounds(0, 30, 90, 25);

        lbl_11_01_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_01_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_01_Time_start.setText("-");
        lbl_11_01_Time_start.setBorder(null);
        add(lbl_11_01_Time_start);
        lbl_11_01_Time_start.setBounds(90, 30, 60, 25);

        lblAnimation_11_01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_11_01);
        lblAnimation_11_01.setBounds(230, 30, 25, 25);

        lbl_11_01_Title.setText("11.1 Заполнение рабочей смесью");
        lbl_11_01_Title.setBorder(null);
        lbl_11_01_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_11_01_TitleMouseClicked(evt);
            }
        });
        add(lbl_11_01_Title);
        lbl_11_01_Title.setBounds(260, 30, 440, 25);

        chk_11_01_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_11_01_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_11_01_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_11_01_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_11_01_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_11_01_AutoStart);
        chk_11_01_AutoStart.setBounds(700, 30, 30, 30);

        lbl_11_01_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_01_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_11_01_IcoStep);
        lbl_11_01_IcoStep.setBounds(730, 30, 30, 25);

        btn_11_01_Next.setText("Далее");
        btn_11_01_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_01_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_01_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_11_01_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_11_01_NextActionPerformed(evt);
            }
        });
        add(btn_11_01_Next);
        btn_11_01_Next.setBounds(770, 30, 60, 30);

        lbl_11_01_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_01_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_01_Date_stop.setText("-");
        lbl_11_01_Date_stop.setBorder(null);
        add(lbl_11_01_Date_stop);
        lbl_11_01_Date_stop.setBounds(840, 30, 90, 25);

        lbl_11_01_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_01_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_01_Time_stop.setText("-");
        lbl_11_01_Time_stop.setBorder(null);
        add(lbl_11_01_Time_stop);
        lbl_11_01_Time_stop.setBounds(930, 30, 60, 25);

        lbl_11_02_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_02_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_02_Date_start.setText("-");
        lbl_11_02_Date_start.setBorder(null);
        add(lbl_11_02_Date_start);
        lbl_11_02_Date_start.setBounds(0, 60, 90, 25);

        lbl_11_02_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_02_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_02_Time_start.setText("-");
        lbl_11_02_Time_start.setBorder(null);
        add(lbl_11_02_Time_start);
        lbl_11_02_Time_start.setBounds(90, 60, 60, 25);

        lblAnimation_11_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_11_02);
        lblAnimation_11_02.setBounds(230, 60, 25, 25);

        lbl_11_02_Title.setText("11.2 Выдержка");
        lbl_11_02_Title.setBorder(null);
        lbl_11_02_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_11_02_TitleMouseClicked(evt);
            }
        });
        add(lbl_11_02_Title);
        lbl_11_02_Title.setBounds(260, 60, 440, 25);

        chk_11_02_AutoStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk_11_02_AutoStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chk_11_02_AutoStart.setMaximumSize(new java.awt.Dimension(30, 25));
        chk_11_02_AutoStart.setMinimumSize(new java.awt.Dimension(30, 25));
        chk_11_02_AutoStart.setPreferredSize(new java.awt.Dimension(30, 25));
        add(chk_11_02_AutoStart);
        chk_11_02_AutoStart.setBounds(700, 60, 30, 30);

        lbl_11_02_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_02_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_11_02_IcoStep);
        lbl_11_02_IcoStep.setBounds(730, 60, 30, 25);

        btn_11_02_Next.setText("Далее");
        btn_11_02_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_02_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_02_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_11_02_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_11_02_NextActionPerformed(evt);
            }
        });
        add(btn_11_02_Next);
        btn_11_02_Next.setBounds(770, 60, 60, 30);

        lbl_11_02_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_02_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_02_Date_stop.setText("-");
        lbl_11_02_Date_stop.setBorder(null);
        add(lbl_11_02_Date_stop);
        lbl_11_02_Date_stop.setBounds(840, 60, 90, 25);

        lbl_11_02_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_02_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_02_Time_stop.setText("-");
        lbl_11_02_Time_stop.setBorder(null);
        add(lbl_11_02_Time_stop);
        lbl_11_02_Time_stop.setBounds(930, 60, 60, 25);

        lbl_11_03_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_03_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_03_Date_start.setText("-");
        lbl_11_03_Date_start.setBorder(null);
        add(lbl_11_03_Date_start);
        lbl_11_03_Date_start.setBounds(0, 90, 90, 25);

        lbl_11_03_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_03_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_03_Time_start.setText("-");
        lbl_11_03_Time_start.setBorder(null);
        add(lbl_11_03_Time_start);
        lbl_11_03_Time_start.setBounds(90, 90, 60, 25);

        lblAnimation_11_03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_11_03);
        lblAnimation_11_03.setBounds(230, 90, 25, 25);

        lbl_11_03_Title.setText("11.3 Измерение ВАХ");
        lbl_11_03_Title.setBorder(null);
        lbl_11_03_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_11_03_TitleMouseClicked(evt);
            }
        });
        add(lbl_11_03_Title);
        lbl_11_03_Title.setBounds(260, 90, 440, 25);

        lbl_11_03_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_03_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_11_03_IcoStep);
        lbl_11_03_IcoStep.setBounds(730, 90, 30, 25);

        btn_11_03_Next.setText("Далее");
        btn_11_03_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_03_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_03_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        add(btn_11_03_Next);
        btn_11_03_Next.setBounds(770, 90, 60, 30);

        lbl_11_03_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_03_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_03_Date_stop.setText("-");
        lbl_11_03_Date_stop.setBorder(null);
        add(lbl_11_03_Date_stop);
        lbl_11_03_Date_stop.setBounds(840, 90, 90, 25);

        lbl_11_03_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_03_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_03_Time_stop.setText("-");
        lbl_11_03_Time_stop.setBorder(null);
        add(lbl_11_03_Time_stop);
        lbl_11_03_Time_stop.setBounds(930, 90, 60, 25);

        lbl_11_04_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_04_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_04_Date_start.setText("-");
        lbl_11_04_Date_start.setBorder(null);
        add(lbl_11_04_Date_start);
        lbl_11_04_Date_start.setBounds(0, 120, 90, 25);

        lbl_11_04_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_04_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_04_Time_start.setText("-");
        lbl_11_04_Time_start.setBorder(null);
        add(lbl_11_04_Time_start);
        lbl_11_04_Time_start.setBounds(90, 120, 60, 25);

        lblAnimation_11_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_11_04);
        lblAnimation_11_04.setBounds(230, 120, 25, 25);

        lbl_11_04_Title.setText("11.4 Внесение пороговых токов");
        lbl_11_04_Title.setBorder(null);
        lbl_11_04_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_11_04_TitleMouseClicked(evt);
            }
        });
        add(lbl_11_04_Title);
        lbl_11_04_Title.setBounds(260, 120, 440, 25);

        lbl_11_04_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_04_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_11_04_IcoStep);
        lbl_11_04_IcoStep.setBounds(730, 120, 30, 25);

        btn_11_04_Next.setText("Далее");
        btn_11_04_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_04_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_04_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        add(btn_11_04_Next);
        btn_11_04_Next.setBounds(770, 120, 60, 30);

        lbl_11_04_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_04_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_04_Date_stop.setText("-");
        lbl_11_04_Date_stop.setBorder(null);
        add(lbl_11_04_Date_stop);
        lbl_11_04_Date_stop.setBounds(840, 120, 90, 25);

        lbl_11_04_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_04_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_04_Time_stop.setText("-");
        lbl_11_04_Time_stop.setBorder(null);
        add(lbl_11_04_Time_stop);
        lbl_11_04_Time_stop.setBounds(930, 120, 60, 25);

        lbl_11_05_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_05_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_05_Date_start.setText("-");
        lbl_11_05_Date_start.setBorder(null);
        add(lbl_11_05_Date_start);
        lbl_11_05_Date_start.setBounds(0, 150, 90, 25);

        lbl_11_05_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_05_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_05_Time_start.setText("-");
        lbl_11_05_Time_start.setBorder(null);
        add(lbl_11_05_Time_start);
        lbl_11_05_Time_start.setBounds(90, 150, 60, 25);

        lblAnimation_11_05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_11_05);
        lblAnimation_11_05.setBounds(230, 150, 25, 25);

        lbl_11_05_Title.setText("11.5 Оценка параметров приборов");
        lbl_11_05_Title.setBorder(null);
        lbl_11_05_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_11_05_TitleMouseClicked(evt);
            }
        });
        add(lbl_11_05_Title);
        lbl_11_05_Title.setBounds(260, 150, 440, 25);

        lbl_11_05_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_05_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_11_05_IcoStep);
        lbl_11_05_IcoStep.setBounds(730, 150, 30, 25);

        btn_11_05_Next.setText("Далее");
        btn_11_05_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_05_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_05_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        add(btn_11_05_Next);
        btn_11_05_Next.setBounds(770, 150, 60, 30);

        lbl_11_05_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_05_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_05_Date_stop.setText("-");
        lbl_11_05_Date_stop.setBorder(null);
        add(lbl_11_05_Date_stop);
        lbl_11_05_Date_stop.setBounds(840, 150, 90, 25);

        lbl_11_05_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_05_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_05_Time_stop.setText("-");
        lbl_11_05_Time_stop.setBorder(null);
        add(lbl_11_05_Time_stop);
        lbl_11_05_Time_stop.setBounds(930, 150, 60, 25);

        lbl_11_06_Date_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_06_Date_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_06_Date_start.setText("-");
        lbl_11_06_Date_start.setBorder(null);
        add(lbl_11_06_Date_start);
        lbl_11_06_Date_start.setBounds(0, 180, 90, 25);

        lbl_11_06_Time_start.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_06_Time_start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_06_Time_start.setText("-");
        lbl_11_06_Time_start.setBorder(null);
        add(lbl_11_06_Time_start);
        lbl_11_06_Time_start.setBounds(90, 180, 60, 25);

        lblAnimation_11_06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lblAnimation_11_06);
        lblAnimation_11_06.setBounds(230, 180, 25, 25);

        lbl_11_06_Title.setText("11.6 Герметизация годных приборов");
        lbl_11_06_Title.setBorder(null);
        lbl_11_06_Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_11_06_TitleMouseClicked(evt);
            }
        });
        add(lbl_11_06_Title);
        lbl_11_06_Title.setBounds(260, 180, 440, 25);

        lbl_11_06_IcoStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_06_IcoStep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        add(lbl_11_06_IcoStep);
        lbl_11_06_IcoStep.setBounds(730, 180, 30, 25);

        btn_11_06_Next.setText("Далее");
        btn_11_06_Next.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_06_Next.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_06_Next.setPreferredSize(new java.awt.Dimension(120, 25));
        add(btn_11_06_Next);
        btn_11_06_Next.setBounds(770, 180, 60, 30);

        lbl_11_06_Date_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_06_Date_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_06_Date_stop.setText("-");
        lbl_11_06_Date_stop.setBorder(null);
        add(lbl_11_06_Date_stop);
        lbl_11_06_Date_stop.setBounds(840, 180, 90, 25);

        lbl_11_06_Time_stop.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        lbl_11_06_Time_stop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11_06_Time_stop.setText("-");
        lbl_11_06_Time_stop.setBorder(null);
        add(lbl_11_06_Time_stop);
        lbl_11_06_Time_stop.setBounds(930, 180, 60, 25);

        btn_11_01_Start.setText("Старт");
        btn_11_01_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_01_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_01_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_11_01_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_11_01_StartActionPerformed(evt);
            }
        });
        add(btn_11_01_Start);
        btn_11_01_Start.setBounds(160, 30, 60, 30);

        btn_11_02_Start.setText("Старт");
        btn_11_02_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_02_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_02_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        btn_11_02_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_11_02_StartActionPerformed(evt);
            }
        });
        add(btn_11_02_Start);
        btn_11_02_Start.setBounds(160, 60, 60, 30);

        btn_11_03_Start.setText("Старт");
        btn_11_03_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_03_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_03_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        add(btn_11_03_Start);
        btn_11_03_Start.setBounds(160, 90, 60, 30);

        btn_11_04_Start.setText("Старт");
        btn_11_04_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_04_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_04_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        add(btn_11_04_Start);
        btn_11_04_Start.setBounds(160, 120, 60, 30);

        btn_11_05_Start.setText("Старт");
        btn_11_05_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_05_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_05_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        add(btn_11_05_Start);
        btn_11_05_Start.setBounds(160, 150, 60, 30);

        btn_11_06_Start.setText("Старт");
        btn_11_06_Start.setMaximumSize(new java.awt.Dimension(120, 25));
        btn_11_06_Start.setMinimumSize(new java.awt.Dimension(120, 25));
        btn_11_06_Start.setPreferredSize(new java.awt.Dimension(120, 25));
        add(btn_11_06_Start);
        btn_11_06_Start.setBounds(160, 180, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_11_00_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_11_00_TitleMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_11_00_TitleMouseClicked

    private void lbl_11_00_IcoStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_11_00_IcoStepMouseClicked
        CollapseClick( m_nPageNumber);
    }//GEN-LAST:event_lbl_11_00_IcoStepMouseClicked

    private void btn_11_02_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_11_02_NextActionPerformed
        if( theApp.IsCurrentStepInProgress() == false)
            return;
        
        //мы в процессе исполнения подэтапа 11.2 "выдержка", переходим к следующему подэтапу 11.3 "Измерение ВАХ" (процесс ручной)
        //theApp.m_pMainWnd.m_EmuTimer.stop();
        if( theApp.IsStepMapContainsKey( "202")) {
            TechProcessStepInfo info = ( TechProcessStepInfo) theApp.GetStepInfo( "202");

            info.SetStopDateAsCurrent();
            info.SetStopReportTitle( "Завершение выдержки");
            info.SetStopP5( theApp.GetFromPoller( "005.01"));
            info.SetStopP6( theApp.GetFromPoller( "006.01"));
            info.SetStopP7( theApp.GetFromPoller( "007.01"));

            theApp.NextCurrentStep();

            info = new TechProcessStepInfo( theApp);
            
            info.SetStartDateAsCurrent();
            info.SetStartReportTitle( "Измерение ВАХ");
            info.SetStartP5( theApp.GetFromPoller( "005.01"));
            info.SetStartP6( theApp.GetFromPoller( "006.01"));
            info.SetStartP7( theApp.GetFromPoller( "007.01"));

            theApp.SaveStepInfo( "203", info, true);

            theApp.m_pMainWnd.m_pPanel.SetStates();
            theApp.m_ReportGenerator.Generate();
            theApp.m_pMainWnd.m_pPanel.Reposition();

            theApp.ShowDlg11_3A();
        }
        else {
            logger.fatal( "Мы заканчиваем этап 202, а инфы на него до сих пор нет!");
        }
    }//GEN-LAST:event_btn_11_02_NextActionPerformed

    private void btn_11_01_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_11_01_NextActionPerformed
        DefaultNextButtonProcessing( "201", "Старт напуска рабочей смеси", "Завершение напуска рабочей смеси",
                                       "202", "Старт выдержки", chk_11_02_AutoStart, logger, false);
    }//GEN-LAST:event_btn_11_01_NextActionPerformed

    private void btn_11_01_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_11_01_StartActionPerformed
        DefaultStartButtonProcessing( "201", "Старт напуска рабочей смеси", "Завершение напуска рабочей смеси",
                                       "202", "Старт выдержки", chk_11_02_AutoStart, logger, false);
    }//GEN-LAST:event_btn_11_01_StartActionPerformed

    private void btn_11_02_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_11_02_StartActionPerformed
        if( theApp.IsCurrentStepInProgress() == true)
            return;

        /*
        //мы начинаем процесс
        TechProcessStepInfo info = new TechProcessStepInfo( theApp);
        
        info.SetStartDateAsCurrent();
        info.SetStartReportTitle( "Старт выдержки");
        info.SetStartP5( theApp.GetFromPoller( "005.01"));
        info.SetStartP6( theApp.GetFromPoller( "006.01"));
        info.SetStartP7( theApp.GetFromPoller( "007.01"));

        theApp.SaveStepInfo( "202", info);

        theApp.m_ReportGenerator.Generate();

        theApp.SetCurrentStepInProgress( true);
        StartProgramExecutor executor = new StartProgramExecutor( theApp, "AdminStep_11.2.xml");
        executor.StartThread();

        SetState();
        */
        DefaultStartButtonProcessing( "202", "Старт выдержки", "Завершение выдержки",
                                      "203", "Измерение ВАХ", /*chk_11_03_AutoStart*/null, logger, false);
    }//GEN-LAST:event_btn_11_02_StartActionPerformed

    private void lbl_11_00_Date_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_11_00_Date_startMouseClicked
        ProcessHeaderDateTimeClick( 11);
    }//GEN-LAST:event_lbl_11_00_Date_startMouseClicked

    private void lbl_11_00_Time_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_11_00_Time_startMouseClicked
        ProcessHeaderDateTimeClick( 11);
    }//GEN-LAST:event_lbl_11_00_Time_startMouseClicked

    private void lbl_11_01_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_11_01_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 201);
        }
    }//GEN-LAST:event_lbl_11_01_TitleMouseClicked

    private void lbl_11_02_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_11_02_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 202);
        }
    }//GEN-LAST:event_lbl_11_02_TitleMouseClicked

    private void lbl_11_03_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_11_03_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 203);
        }
    }//GEN-LAST:event_lbl_11_03_TitleMouseClicked

    private void lbl_11_04_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_11_04_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 204);
        }
    }//GEN-LAST:event_lbl_11_04_TitleMouseClicked

    private void lbl_11_05_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_11_05_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 205);
        }
    }//GEN-LAST:event_lbl_11_05_TitleMouseClicked

    private void lbl_11_06_TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_11_06_TitleMouseClicked
        if( evt.getButton() == MouseEvent.BUTTON3) {
            theApp.GetPendings().CallPendSettingDialog( 206);
        }
    }//GEN-LAST:event_lbl_11_06_TitleMouseClicked

    public void SetState() {
        if( theApp.GetCurrentStep() / 20 == m_nPageNumber)
            m_bCollapsed = false;
        
 
        //11. Выходная оценка параметров приборов
 
        FillHeaderStepDates( "201", lbl_11_00_Date_start, lbl_11_00_Time_start, "206", lbl_11_00_Date_stop, lbl_11_00_Time_stop);
        
        lbl_11_00_IcoStep.setIcon( m_bCollapsed ? theApp.GetResources().getIconTriaRight() : theApp.GetResources().getIconTriaDown());
        
        lbl_11_00_Title.setFont( theApp.GetCurrentStep() / 20 == m_nPageNumber ? theApp.GetBoldFont() : theApp.GetUsualFont());
        lbl_11_00_Title.setEnabled( theApp.GetCurrentStep() / 20 <= m_nPageNumber);
        
        
        if( m_bCollapsed == false) {
            //11.1 Заполнение рабочей смесью
            FillAutoExecutedSubStep(201,
                                    lbl_11_01_Date_start, lbl_11_01_Time_start, lblAnimation_11_01,
                                    btn_11_01_Start, lbl_11_01_Title, chk_11_01_AutoStart, lbl_11_01_IcoStep, btn_11_01_Next,
                                    lbl_11_01_Date_stop, lbl_11_01_Time_stop);
            
            //11.2 Выдержка
            FillAutoExecutedSubStep(202,
                                    lbl_11_02_Date_start, lbl_11_02_Time_start, lblAnimation_11_02,
                                    btn_11_02_Start, lbl_11_02_Title, chk_11_02_AutoStart, lbl_11_02_IcoStep, btn_11_02_Next,
                                    lbl_11_02_Date_stop, lbl_11_02_Time_stop);
            
            //11.3 Измерение ВАХ
            FillAutoExecutedSubStep(203,
                                    lbl_11_03_Date_start, lbl_11_03_Time_start, lblAnimation_11_03,
                                    btn_11_03_Start, lbl_11_03_Title, null, lbl_11_03_IcoStep, btn_11_03_Next,
                                    lbl_11_03_Date_stop, lbl_11_03_Time_stop);
            
            btn_11_03_Start.setVisible( false);
            btn_11_03_Next.setVisible( false);
            
            
            //11.4 Внесение пороговых токов
            FillAutoExecutedSubStep(204,
                                    lbl_11_04_Date_start, lbl_11_04_Time_start, lblAnimation_11_04,
                                    btn_11_04_Start, lbl_11_04_Title, null, lbl_11_04_IcoStep, btn_11_04_Next,
                                    lbl_11_04_Date_stop, lbl_11_04_Time_stop);
            
            btn_11_04_Start.setVisible( false);
            btn_11_04_Next.setVisible( false);
            
            
            //11.5 Оценка параметров приборов
            FillAutoExecutedSubStep(205,
                                    lbl_11_05_Date_start, lbl_11_05_Time_start, lblAnimation_11_05,
                                    btn_11_05_Start, lbl_11_05_Title, null, lbl_11_05_IcoStep, btn_11_05_Next,
                                    lbl_11_05_Date_stop, lbl_11_05_Time_stop);
            
            btn_11_05_Start.setVisible( false);
            btn_11_05_Next.setVisible( false);
            
            
            //11.6 Герметизация годных приборов
            FillAutoExecutedSubStep(206,
                                    lbl_11_06_Date_start, lbl_11_06_Time_start, lblAnimation_11_06,
                                    btn_11_06_Start, lbl_11_06_Title, null, lbl_11_06_IcoStep, btn_11_06_Next,
                                    lbl_11_06_Date_stop, lbl_11_06_Time_stop);
            
            btn_11_06_Start.setVisible( false);
            btn_11_06_Next.setVisible( false);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_11_01_Next;
    public javax.swing.JButton btn_11_01_Start;
    private javax.swing.JButton btn_11_02_Next;
    public javax.swing.JButton btn_11_02_Start;
    private javax.swing.JButton btn_11_03_Next;
    public javax.swing.JButton btn_11_03_Start;
    private javax.swing.JButton btn_11_04_Next;
    public javax.swing.JButton btn_11_04_Start;
    private javax.swing.JButton btn_11_05_Next;
    public javax.swing.JButton btn_11_05_Start;
    private javax.swing.JButton btn_11_06_Next;
    public javax.swing.JButton btn_11_06_Start;
    public javax.swing.JCheckBox chk_11_01_AutoStart;
    public javax.swing.JCheckBox chk_11_02_AutoStart;
    public javax.swing.JLabel lblAnimation_11_01;
    public javax.swing.JLabel lblAnimation_11_02;
    public javax.swing.JLabel lblAnimation_11_03;
    public javax.swing.JLabel lblAnimation_11_04;
    public javax.swing.JLabel lblAnimation_11_05;
    public javax.swing.JLabel lblAnimation_11_06;
    public javax.swing.JLabel lbl_11_00_Date_start;
    private javax.swing.JLabel lbl_11_00_Date_stop;
    private javax.swing.JLabel lbl_11_00_IcoStep;
    public javax.swing.JLabel lbl_11_00_Time_start;
    private javax.swing.JLabel lbl_11_00_Time_stop;
    private javax.swing.JLabel lbl_11_00_Title;
    private javax.swing.JLabel lbl_11_01_Date_start;
    private javax.swing.JLabel lbl_11_01_Date_stop;
    public javax.swing.JLabel lbl_11_01_IcoStep;
    private javax.swing.JLabel lbl_11_01_Time_start;
    private javax.swing.JLabel lbl_11_01_Time_stop;
    private javax.swing.JLabel lbl_11_01_Title;
    private javax.swing.JLabel lbl_11_02_Date_start;
    private javax.swing.JLabel lbl_11_02_Date_stop;
    public javax.swing.JLabel lbl_11_02_IcoStep;
    private javax.swing.JLabel lbl_11_02_Time_start;
    private javax.swing.JLabel lbl_11_02_Time_stop;
    private javax.swing.JLabel lbl_11_02_Title;
    private javax.swing.JLabel lbl_11_03_Date_start;
    private javax.swing.JLabel lbl_11_03_Date_stop;
    public javax.swing.JLabel lbl_11_03_IcoStep;
    private javax.swing.JLabel lbl_11_03_Time_start;
    private javax.swing.JLabel lbl_11_03_Time_stop;
    private javax.swing.JLabel lbl_11_03_Title;
    private javax.swing.JLabel lbl_11_04_Date_start;
    private javax.swing.JLabel lbl_11_04_Date_stop;
    public javax.swing.JLabel lbl_11_04_IcoStep;
    private javax.swing.JLabel lbl_11_04_Time_start;
    private javax.swing.JLabel lbl_11_04_Time_stop;
    private javax.swing.JLabel lbl_11_04_Title;
    private javax.swing.JLabel lbl_11_05_Date_start;
    private javax.swing.JLabel lbl_11_05_Date_stop;
    public javax.swing.JLabel lbl_11_05_IcoStep;
    private javax.swing.JLabel lbl_11_05_Time_start;
    private javax.swing.JLabel lbl_11_05_Time_stop;
    private javax.swing.JLabel lbl_11_05_Title;
    private javax.swing.JLabel lbl_11_06_Date_start;
    private javax.swing.JLabel lbl_11_06_Date_stop;
    public javax.swing.JLabel lbl_11_06_IcoStep;
    private javax.swing.JLabel lbl_11_06_Time_start;
    private javax.swing.JLabel lbl_11_06_Time_stop;
    private javax.swing.JLabel lbl_11_06_Title;
    // End of variables declaration//GEN-END:variables
}
